- .github/workflows/fork-integration-test.yml
This commit changes the workflow which test executed when building
integration tests of PRs coming from forks (Run Integration Tests
for Forks). It temporarily disables builds to run on MacOS and Windows.
The reason for that is #30, builds are currently failing on windows.
Furthermore, there seems to be a problem with concurrent integration
test execution.
We should revert this change again anlongside the fix for #30.
> Temporarily run integration tests just on linux

- cmd/monaco/test-resources/integration-all-configs/project/kubernetes-credentials/kubernetes.json
As `endpointUrl` needs to be unique, used name (which is generated with timestamp). Using hardcoded `endpointUrl` results in error 
```JSON 
{"error":{"code":400,"message":"Constraints violated.","constraintViolations":[{"path":"endpointUrl","message":"URL is already in use.","parameterLocation":"PAYLOAD_BODY","location":null}]}}
```
Using `name` instead of hardcoded url, because it also contains timestamp when test is started, meaning `endpointUrl` will be different every time tests are executed.
> Fix issue when parallel integrations tests are failing on kubernetes credentials

- pkg/util/logging.go
Actually assign the MultiLogger created in SetupLogging(),
to the shared Log object.
As implemented now, still defaults to non-verbose Console logging,
unless both console and file logging setup works.
Fix #43
@tatomir146 , @didiladi mea culpa...
> Fix: Set console/file multilogger as shared logger

- .github/ISSUE_TEMPLATE/bug_report.md
Let's add our first issue template for BUGs. Please feel free to propose changes.
PS once we are happy with templates, we can also think about deactivating default blank template.
> Add issue template for reporting BUGs

- cmd/monaco/test-resources/integration-all-configs/project/synthetic-monitor/synthetic-monitors.yaml
The all configs integration test currently fails, because the id of the
synthetic location is not existing for the environments, we run the
integration tests for. This was caused by switching out the
environments we run the integration tests against.
fixes #63
> Fix the synthetic location id used in the integration tests

- README.md
I also added a suffix "_ENV_VAR" for the API_TOKENs in the code examples for better understanding. 
PS: The syntax highlighting does not change the appearance in GitHub, but it helps when editing locally in vscode! ; )
> Fixes environment url and adds markdown syntax highlighting

- README.md
Improve documentation of the workaround needed for the calculated log metrics 
configuration. 
There is an additional issue in the current API workaround, that leads to failures for 
dependent configurations on first upload of a log metric - Bug to be created.
> Extend Documentation of Calculated Log Metrics

- cmd/monaco/all_configs_integration_test.go
- cmd/monaco/integration_test_utils.go
- cmd/monaco/multi_project_integration_test.go
- cmd/monaco/multi_tenant_integration_test.go
This commit fixes the following issues listed in #52:
* Unresolved references due to the variables `folder` and
`environmentsFile` being defined in file
`multi_tenant_integration_test.go`. They can be seen when opening
the project in GoLand.
* We create configs for different environments, as we try to clean
after running the integration tests.
* We try to clean up different configs, as we apply in the
integration test run.
Furthermore, the method `RunIntegrationWithCleanup` was simplified to
take a `func(integrationTestReader util.FileReader) {}`. This
simplifies the integration tests, because the `InMemoryFileReader` is
created in the utility function and passed to the test itself. So, the
individual test doesn't need to create a `FileReader` anymore.
Additionally, some documentation was …
> Fix unresolved references errors in GoLand (#52)

- README.md
This commit enhances the documentation by adding the required token
permissions for each API.
fixes #54
> Enhance documentation with Token permissions

- cmd/monaco/main.go
This commit deletes configs only if there were no errors during previous deployment/validation.
fixes #20
> Delete configs only if apply finished without errors (#20)

- README.md
- pkg/project/project.go
- pkg/project/project_loader.go
This commit introduces a log message if the project folder name clashes
with an API folder of the same name, but different lowercase/uppercase
spelling. Additionally, the readme was changed, to indicate that API
folders need to be defined case-sensitive.
Example of a log line:
```
2020-11-30 10:43:07 WARN  Project Application in folder \
skip-deployment-project clashes with API name application. \
Consider using a different name for your project.
```
fixes #58
> Log a warning if project name clashes with API name (#58)

- README.md
- cmd/monaco/main.go
- cmd/monaco/main_test.go
This flags allow you to query the current version of monaco. If the
version flag is present, it will only print the version and the exit the
program.
Fixes #84
> Add --version flag

- cmd/monaco/main.go
- cmd/monaco/main_test.go
When parsing the command line arguments make sure that any slashes or
backslashes are always replaced by the OS-specific path separator.
Fixes both bugs/issues #80 and #90.
> Fix #80 and #93: Allow trailing slash in folder on Windows

- README.md
Add installation instructions for various operating systems
fixes #82
> Define some install steps/requirements

- cmd/monaco/main.go
The verbose flag was missing in the flag definition and has now been
added.
> Fix missing verbose flag in legacy cli

- RELEASE_NOTES.md
- pkg/version/version.go
This commit extends the documentation for `monaco` version 1.2.0 and
sets its version. `monaco` 1.2.0 contains the following changes:
Features:
* 4c53146 and 8611bd5 #19: Download current environment configuration (#122) 
* dfbad92 and f54c278 Fix #45: Introduce new experimental cli design (#100)
Bugfixes:
* fe30566 Fix #136: Handle failing to find project-root-folder path (#137)
* 211dcbe and b74b06b Fix missing verbose flag in legacy cli (#129)
Misc changes:
* c70ca7b Fix #82: Define some install steps/requirements (#109)
> Release version 1.2.0

- README.md
- pkg/rest/request.go
- pkg/util/logging.go
It is sometimes hard to understand what actually gets send to dynatrace
by monaco. For this reason one can now specify a request log file via
setting the `MONACO_REQUEST_LOG` environment variable. If the
environment variable is set, all send requests will get written to this
file.
This fixes #143
**NOTE:** documentation is still missing for now until we agree on the way 
we want to specify the request log file.
> Add possibility to log send requests

- pkg/delete/delete.go
Closes #155. After releasing monaco 1.2.0 delete stopped working. Fixed delete.yaml file path and also added info log in case delete.yaml can't be found.
> Fix #155: delete not working

- cmd/monaco/main.go
- pkg/deploy/deploy.go
- pkg/download/download.go
Due to a misunderstanding how the cli parsing library works, the verbose
flag was never set correctly in the new cli. This has now been fixed.
> Fix verbose flag not working in new cli

- .editorconfig
After editing the README I noticed, that we have some style differences
in there. Hence a .editorconfig file was created to have a standard set
of formating rules such as tabs vs spaces, tab width across all
contributors.
> Add editorconfig to standardize various style related things

- README.md
- cmd/monaco/test-resources/integration-all-configs/delete.yaml
- cmd/monaco/test-resources/integration-all-configs/project/application-mobile/mobile-application.json
- cmd/monaco/test-resources/integration-all-configs/project/application-mobile/mobile-application.yaml
- cmd/monaco/test-resources/integration-all-configs/project/application-web/application.json
- cmd/monaco/test-resources/integration-all-configs/project/application-web/application.yaml
- pkg/api/api.go
- pkg/project/project.go
Added support for the `applications/mobile` endpoint.
- Added endpoint definition in api.go
- Added test files in `integration-all-configs` project
Added a config type for the `applications/web`endpoint
- This already existed before as `application`, but now it is also there as `application-web`
- Added a warning message that with v2.0.0 the `application` config type will be deprecated if it is being used
For issue https://github.com/dynatrace-oss/dynatrace-monitoring-as-code/issues/146
> support for mobile applications

- RELEASE_NOTES.md
- pkg/version/version.go
This commit extends the documentation for `monaco` version 1.3.0 and
sets its version. `monaco` 1.3.0 contains the following changes:
Deprecation Warnings
* #146: `application-web` configuration type replaces `application` in the future
* `application` config type is deprecated with 1.3.0 and will be removed with 2.0.0
Features:
* #146: Add support for `application-mobile`(applications/mobile) configurations
* #66: Add support for `slo` (/api/v2/slo) configruations
Bugfixes:
* f52d297 Fix #138: Fix issue when providing context path without slash (#139)
* 60cf6b1 Fix #155: Fix delete command not working (#157)
* 2f774bc: Show error when more than one argument is provided (#139)
* 7002149: Fix pretty print of json error (#150)
* 4086d87: Fix verbose flag not working in new cli (#159)
* …
> Relase version 1.3.0

- pkg/rest/config_upload.go
- pkg/rest/config_upload_test.go
It can happen that you have a faulty config deployed in your
environment, which has no id or name set. These special cases were not
handled correctly before. Instead, `monaco` crashed when getting the
list of configs. This commit introduces a graceful handling of these
configs in monaco.
If the id is null -> Return an error
If the name is null -> Fill in the id as the name (as done by the
extensions API)
> Cope with faulty configs (name or id is null)

- RELEASE_NOTES.md
- pkg/version/version.go
This commit extends the documentation for monaco version 1.3.1 and
sets its version. monaco 1.3.1 contains the following changes:
Bugfixes:
* 2e0e88a: Cope with faulty configs (name or id is null) (#169)
> Release version 1.3.1

- README.md
- cmd/monaco/test-resources/integration-all-configs/delete.yaml
- cmd/monaco/test-resources/integration-all-configs/project/custom-service-dotnet/warp-drive-service.json
- cmd/monaco/test-resources/integration-all-configs/project/custom-service-dotnet/warp-drive-services.yaml
- cmd/monaco/test-resources/integration-all-configs/project/custom-service-go/warp-drive-service.json
- cmd/monaco/test-resources/integration-all-configs/project/custom-service-go/warp-drive-services.yaml
- cmd/monaco/test-resources/integration-all-configs/project/custom-service-nodejs/warp-drive-service.json
- cmd/monaco/test-resources/integration-all-configs/project/custom-service-nodejs/warp-drive-services.yaml
- cmd/monaco/test-resources/integration-all-configs/project/custom-service-php/warp-drive-service.json
- cmd/monaco/test-resources/integration-all-configs/project/custom-service-php/warp-drive-services.yaml
- pkg/api/api.go
- added config types for custom-service-dotnet, custom-service-go, custom-service-nodejs, custom-service-php.
- added documentation in Readme.md
- added test files in integration-all-configs
In support of https://github.com/dynatrace-oss/dynatrace-monitoring-as-code/issues/158
> support for custom-service dotnet,go,nodejs,php

- pkg/rest/request.go
- pkg/util/logging.go
If for whatever reason there is an error while logging the
request/response, the user now sees this in the monaco log output as a
warning message.
> Log error on request log error

- go.mod
- go.sum
Since addlincense is needed to successfully build, the go.mod entries
should also be checked in.
> Add missing go mod entries for addlincense

- RELEASE_NOTES.md
- pkg/version/version.go
This commit extends the documentation for monaco version 1.5.0 and
sets its version. Monaco 1.5.0 contains the following changes:
Features
* 84c8ef9 Added option to allow deployment to proceed even if error occurred (#127)
* c695dd4 Add response log (#228)
Bugfixes
* 7159440 Add missing license headers to files (#191)
Library updates
* e217ea8 Bump github.com/golang/mock from 1.4.4 to 1.5.0
Misc changes
* e178bc5 Fix path of PUT in how-to-add-a-new-api.md (#235)
* 0faae65 Add missing go mod entries for addlincense
* 080f2f1 Update README.md Updated supported configuration types table
* faa1b01 Add add-license-header make goal
* ac6f001 Fail build if license header is missing
> Release 1.5.0

- pkg/util/template.go
It seems like that golangs `template.ParseFS` needs to be cleaned,
otherwise it fails.
> Fix template loading for abosolute template reference

- cmd/monaco/all_configs_integration_test.go
- cmd/monaco/config_restore_e2e_test.go
- cmd/monaco/continue_deployment_on_error_integration_test.go
- cmd/monaco/integration_test_utils.go
- cmd/monaco/main.go
- cmd/monaco/multi_project_integration_test.go
- cmd/monaco/multi_tenant_integration_test.go
- go.sum
- pkg/config/config.go
- pkg/config/config_test_util.go
- pkg/delete/delete.go
- pkg/deploy/deploy.go
- pkg/download/download.go
- pkg/download/jsoncreator/json_creator.go
- pkg/download/yamlcreator/yaml_creator.go
- pkg/environment/environment_loader.go
- pkg/project/project.go
- pkg/project/project_loader.go
- pkg/project/project_test.go
- pkg/util/afero_utils.go
- pkg/util/template.go
- pkg/util/test_config_rewrite.go
- pkg/util/test_utils_test.go
By definition (1) golangs filesystem abstraction doesn't support
absolute paths. Since we need absolute paths to work, every use of
afero.IOFS has been replaced with just afero.Fs. In order to use golangs
abstraction some further research and prototyping is needed.
(1) https://go.googlesource.com/proposal/+/master/design/draft-iofs.md#file-name-syntax
> Fix absolute paths broken

- RELEASE_NOTES.md
- pkg/version/version.go
This commit extends the documentation for monaco version 1.5.1 and
sets its version. Monaco 1.5.1 contains the following changes:
* 3903c46 fix: Revert "Add new API for reports (for dashboards)" (#284)
* 108cfee feat: Add new API for reports (for dashboards) (#259)
* bb125fb fix: Paging in monaco was not working (#276)
* 7388bbd Fix absolute paths broken
* 7bd5a7f Fix template loading for absolute template reference
* affafab reset env variable at the end of e2e test (#266)
* 559b881 removes fs from config implementation (#266)
* 397a8b2 fix parameters in integration test (#266)
* 2440ee7 e2e test config restore environment (#266)
* 7e38119 Add licensecheck dependencies to go mod (#250)
* 72721cf Handle possible error when creating a new go http request
* cea13c5 Do not unmarshall json …
> Release 1.5.1

- .github/workflows/pr-static-code-analysis.yml
Add a PR action using the [golangci-lint](https://github.com/golangci/golangci-lint)
meta linter/linter aggregator to do analysis of the changeset.
Uses golangci-lint [Default Linters](https://golangci-lint.run/usage/linters/#enabled-by-default-linters)
And the following optional linters:
* [bodyclose](https://github.com/timakin/bodyclose)
* checking http response.Body is closed
* [cyclop](https://github.com/bkielbasa/cyclop)
* checking function & pkg cyclomatic complexity
* [exhaustive](https://github.com/nishanths/exhaustive)
* checking if enum switches are exhaustive
* [godox](https://github.com/matoous/godox)
* checking for TODO, FIXME, etc comments
* [gosec](https://github.com/securego/gosec)
* checking for security vulnerabilities
> ci: Add static code analysis of PRs

- cmd/monaco/test-resources/integration-all-configs/only-post/application-mobile/mobile-application.json
- pkg/rest/config_upload.go
The SLO API returns http status code `200` or `201` when updating an
existing config. Previously, `monaco` just listened for the `204` status
code on update. This commit changes the behavior and makes the response
checking more explicit.
fixes #288
> fix: References on pre-existing SLOs do not work

- RELEASE_NOTES.md
- pkg/version/version.go
This commit extends the documentation for monaco version 1.5.2 and
sets its version. Monaco 1.5.2 contains the following changes:
List of changes:
Bugfixes:
* 422679b fix: Update mobile application config to fix integration tests (#289)
* b3761ee fix: References on pre-existing SLOs do not work (#289)
Misc changes:
* f5303a7 ci: Add static code analysis of PRs (#286)
> Release 1.5.2

- RELEASE_NOTES.md
- pkg/version/version.go
This commit extends the documentation for monaco version 1.5.3 and sets its version. Monaco 1.5.3 contains the following changes:
* 7b0cfae Bugfix #307 multiple dependencies with relative path resolution not working (#307)
> Release 1.5.3

- README.md
The install section mentioned that we distribute monaco as a zip file,
which is not true. Hence the documentation has been adapted to use
executable instead of archive in the install section.
> doc: Fix install section in README

- pkg/rest/config_upload.go
There was an issue with the way we build the upsert urls. If the id of
an object contained any special char such as `%`, it would fail the
upsert request. To overcome this issues, all IDs are now URL-Path
encoded.
*Note:* there seem to be an issue with the dynatrace anomaly-detection api
that prevent updating build-in anomaly-detection-metrics with `%` in their name. 
fixes #248
> fix: Upsert objects with special chars no longer fail

- documentation/docs/configuration/yaml_confg.md
The guide explaining how to utilise json files in another dir had duplicate lines repeating its self 3 times.
> docs: Removed duplicate lines in yaml_config.md

- pkg/rest/extension_upload.go
- pkg/rest/extension_upload_test.go
If a new extension is to be uploaded, there is no current version, so the
validation step returned an error for that. With this we check if an
extension doesn't exist at all before uploading, in which case we can
safely upload this new extension
fix: #125
> fix: Check status code in extension validation to allow uploading new extensions again

- pkg/config/v2/parameter/reference/reference.go
- pkg/manifest/manifest_persitence.go
- pkg/manifest/manifest_writer.go
When persisting reference parameters there was a bug, setting the project property wrong.
The manifest converter doesn't have to write name and path if both are the same for simple projects.
> Small bugfixes in converter

- documentation/docs/configuration/parameters.md
- pkg/config/v2/config.go
- pkg/config/v2/parameter/compound/compound.go
- pkg/config/v2/parameter/compound/compound_test.go
This creates a new parameter type, which is composed of other parameters
within the same config.
This parameter has a value `format`, which specifies a template string
for the actual value of the parameter, and a list of references that are
used by the parameter.
fixes: #394
> feat: Introduce compound parameter type

- .dependencies/templates/dependencies.csv.tmpl
- .github/workflows/dependencies-and-licenses.yml
This commit adds a workflow for generating the bill of materials for
`monaco` and its dependencies (including the documentation). The
workflow needs to be started manually for now. At a later point in time,
we can run it for every release. But for now: let's keep it simple.
The approach is "borrowed" from `keptn/keptn` :)
fixes #466
> feat(workflow): Add workflow for generating bill-of-materials

- cmd/monaco/test-resources/integration-all-configs/project/slo/slo.json
- cmd/monaco/test-resources/integration-all-configs/project/slo/slo.yaml
This commit fixes a breaking change in the SLO api which prevents
storing an SLO config when no management zone is defined by changing the
integration test config used in the all-configs-integration-test.
fixes #484
> fix(integration tests): Fix breaking change in SLO api

- cmd/monaco/test-resources/integration-all-configs/project/service-detection-full-web-request/demorule.json
- cmd/monaco/test-resources/integration-all-configs/project/service-detection-full-web-request/servicedetectionrules.yaml
- cmd/monaco/test-resources/integration-all-configs/project/service-detection-full-web-service/demorule.json
- cmd/monaco/test-resources/integration-all-configs/project/service-detection-full-web-service/servicedetectionrules.yaml
- cmd/monaco/test-resources/integration-all-configs/project/service-detection-opaque-web-request/demorule.json
- cmd/monaco/test-resources/integration-all-configs/project/service-detection-opaque-web-request/servicedetectionrules.yaml
- cmd/monaco/test-resources/integration-all-configs/project/service-detection-opaque-web-service/demorule.json
- cmd/monaco/test-resources/integration-all-configs/project/service-detection-opaque-web-service/servicedetectionrules.yaml
- documentation/docs/configuration/configTypes_tokenPermissions.md
- pkg/api/api.go
- pkg/rest/config_upload.go
This PR builds on the awesome work of @luislira22 in #449.
It adds 4 new APIs:
* service-detection-api-full-web-request
for api endpoint /api/config/v1/service/detectionRules/FULL_WEB_REQUEST
* service-detection-full-web-service
for api endpoint /api/config/v1/service/detectionRules/FULL_WEB_SERVICE
* service-detection-opaque-web-request
for api endpoint /api/config/v1/service/detectionRules/OPAQUE_AND_EXTERNAL_WEB_REQUEST
* service-detection-opaque-web-service
for api endpoint /api/config/v1/service/detectionRules/OPAQUE_AND_EXTERNAL_WEB_SERVICE
> feat(api): Added service detection APIs

- pkg/rest/config_upload.go
This commit adds additional error handling when getting all the existing
configs for an API. Previously, we did not check the HTTP status code of
the response coming from the API.
fixes #479
> fix: do not ignore non-successful responses on GET(all) requests

- pkg/util/parse.go
- pkg/util/parse_test.go
---
`cannot convert YAML` doesn't give any helpful clue. It would be best to print even more details, like: show the YAML along with some visual guide that shows what's wrong along with line number, but I think these messages make troubleshooting way easier already. In this place in the code we don't have access to the line number without a major refactoring.
----
Checked end to end on a real-world case where a file was malformed like this:
```
EmailControl-SESemailbouncelist:
- name: EmailControl - SES email bounce list
- token : {{.Env.DEV_EMAIL_CONTROL_TOKEN}} #the access token is common for dev/sandbox/sprint
```
The value of `token` should be put in double quotes.
The result:
```
$ /home/piotr/repos/dynatrace-monitoring-as-code/bin/monaco --environments environments.yaml …
```
> Improve error messages for YAML conversion issues

- .github/CODEOWNERS
Configure ownership of documentation to mac-doc-owners group.
This initial ownership concept should make maintaining documentation easier by enabling more/dedicated people to review and merge changes
> feat(workflow): Add CODEOWNERS default reviewers

- pkg/util/template.go
- pkg/util/template_test.go
In some cases the value of an environment variable may have an equal sign (for example, within an URL).
Do not try to split in more than two parts.
> fix: do not ignore vars that have "=" in their value

- pkg/config/config.go
- pkg/config/config_test.go
- pkg/rest/config_upload.go
GetObjectNameForEnvironment: Make it clear to the users that defining the property is not enough, but that it has to be non-empty as well
getObjectIdIfAlreadyExists: Log the Error as a warning as the upload does not end in an error.
Signed-off-by: David Laubreiter <david.laubreiter@dynatrace.com>
> feat: Improve some log messages

- pkg/download/download.go
- pkg/download/download_test.go
monaco download will create an empty synthetic-locations config folder, if only PUBLIC locations exist.
after downloading an api it checks, wether it is empty and deletes deletes the folder if needed
fixes: #666
> fix: download-creates-folders-for-empty-configurations

- cmd/monaco/test-resources/integration-all-configs/project/dashboard/dashboard.yaml
- cmd/monaco/test-resources/integration-all-configs/project/dashboard/overview-dashboard.json
- documentation/docs/configuration/yaml_config.md
- pkg/util/json.go
- pkg/util/template.go
- pkg/util/template_test.go
Up to now, it was impossible to use newlines in YAML configurations directly; you had to escape them. 
With this change, it is allowed to use all features yaml gives us to include newlines directly in the yaml variable definition.
Look at the dashboard example for insights on how you can use it.
> feat: Allow newlines in variables

- .github/workflows/build-test.yml
- .github/workflows/release.yml
- Makefile
In order to be libc agnostic, monaco is now build as a static binary.
fix #567
> ci: Build static monaco binary

- pkg/download/download.go
- pkg/download/download_test.go
- pkg/download/jsoncreator/json_creator.go
- pkg/rest/client.go
- pkg/rest/client_test.go
Fixes #704 
Output w/ -v
```2022-07-28 12:09:57 DEBUG request log not activated
2022-07-28 12:09:57 DEBUG response log not activated
2022-07-28 12:09:57 INFO  Dynatrace Monitoring as Code v1.8.1
2022-07-28 12:09:57 INFO  Creating base project name foo
2022-07-28 12:09:57 WARN  You used an old token format. Please consider switching to the new 1.205+ token format.
2022-07-28 12:09:57 WARN  More information: https://www.dynatrace.com/support/help/dynatrace-api/basics/dynatrace-api-authentication/#-dynatrace-version-1205--token-format
2022-07-28 12:09:57 INFO   --- GETTING CONFIGS for anomaly-detection-services
2022-07-28 12:09:57 DEBUG No previously downloaded configs found.
2022-07-28 12:09:57 ERROR error getting detail for API anomaly-detection-services for entity …
```
> fix(download): Downloading single config Apis now report encountered errors

- pkg/delete/delete.go
- pkg/delete/delete_test.go
With this change, slashes in names are allowed during deletion. The first slash is used to slit between API & name, and all following slashes are ignored.
Tested with the following delete.yaml:
```yaml
delete:
- conditional-naming-processgroup//a
- conditional-naming-processgroup/a/b/c/
- conditional-naming-processgroup/a/b
```
Fixes: #586
> fix(download): Deleting configs with slashes in the name does no longer error

- pkg/util/logging.go
- pkg/util/logging_test.go
Before this fix, all responses and requests containing a charset were ignored, and all content types starting with text/.
> fix: filter the mime types correctly for logging

- pkg/rest/config_upload.go
Similar to the previously known user error message, a general
'Metric selector is invalid' is usually returned while a calculated
metric is not yet available for use in an SLO.
This additional will trigger monaco's retry logic for this message as
well.
> feat: Retry SLO creation on additional know error

- cmd/monaco/test-resources/integration-all-configs/project/notification/notifications.yaml
- cmd/monaco/test-resources/special-character-in-config/project/alerting-profile/profile.yaml
- documentation/docs/configuration/yaml_config.md
- pkg/download/yamlcreator/yaml_creator.go
- pkg/util/template.go
- pkg/util/template_integration_test.go
- pkg/util/template_test.go
- pkg/util/test-resources/templating-integration-test-config.yaml
- pkg/util/test-resources/templating-integration-test-template.json
Reverts functionality of https://github.com/dynatrace-oss/dynatrace-monitoring-as-code/commit/f8d307ceb32100ce357706023aa5745b2cd438af
Handles the original issue resulting in that general fix with a simpler localized change escaping quotes when downloading
> Undo escape all

- pkg/rest/config_upload.go
- pkg/rest/config_upload_test.go
Instead of only logging actual errors from the rest call, now log http code and response in the same way non-retried errors are logged.
> fix(rest): Log http error and response in case of retry failures

- documentation/docs/commands/downloading-configuration.md
- pkg/download/download.go
- pkg/download/download_test.go
- pkg/download/jsoncreator/json_creator.go
Anomaly-detection-metrics that start with dynatrace.* or ruxit.* are metrics that plugins define - we need to skip those during download.
> fix(download): Skip plugin-definitions of ad-metrics

- documentation/docs/configuration/configuration_structure.md
- documentation/docs/configuration/yaml_config.md
- documentation/versioned_docs/version-1.8.x/configuration/configuration_structure.md
- documentation/versioned_docs/version-1.8.x/configuration/yaml_config.md
Name parameters where so far only mentioned in passing, but an integral part of how monaco works.
Add some more details about configuring them and detail common pitfals of wrongly using the name variable inside a JSON template.
> docs: Add additional information about name configuration

- RELEASE_NOTES.md
- pkg/rest/config_upload.go
- pkg/rest/config_upload_test.go
- pkg/version/version.go
When getting the list of SLOs the API only responds with "enabled" SLOs. To get all SLOs (including disabled) the query parameter `enabledSlos=all` needs to be set.
> fix: added "enabledSlos" query parameter

- pkg/rest/config_upload.go
- pkg/rest/config_upload_test.go
Testing the SLO APIs pagination it was found that it's possible to run into the same timing issues as Upsert when listing existing configs. To handle cases where one reply returns a nextPage key/number of configs that does not match the one of the next reply, GET is now retried.
> feat: Introduce retry mechanism for GET requests

- documentation/docs/configuration/environments_file.md
- documentation/versioned_docs/version-1.8.x/configuration/environments_file.md
based on #795 by @fwyattblake this adds some details about API tokens being defined as environment variables
> docs: Add details about environment variables for API tokens

- cmd/monaco/delete/delete.go
- cmd/monaco/delete/purge.go
- cmd/monaco/deploy/deploy.go
- cmd/monaco/deploy/deploy_test.go
- cmd/monaco/integrationtest/v2/cleanup_all_configs_test.go
- cmd/monaco/integrationtest/v2/integration_test_utils.go
- cmd/monaco/runner/runner.go
- pkg/manifest/manifest.go
- pkg/manifest/manifest_loader.go
- pkg/manifest/manifest_loader_test.go
- pkg/manifest/manifest_test.go
This change allows users to specify an environment group instead of only environments to deploy to.
For example, an environment 'staging' could contain hundreds of environments. To not need to specify each one, this change adds the possibility to specify the `--group` (`-g`) flag to deploy all environments within one group.
This flag is currently mutually exclusive with `--environment` (`-e`).
A new restriction introduced in the `manifest.yaml`: `environmentGroups[].name` must be unique.
> Feature: Allow deployment/deletion with environment-groups

- cmd/monaco/deploy/deploy.go
- cmd/monaco/download/download_command.go
- cmd/monaco/download/download_configs.go
- pkg/client/client.go
- pkg/client/client_test.go
- pkg/client/dummy_client.go
- pkg/client/settings_client_test.go
- pkg/client/version_check.go
- pkg/client/version_check_test.go
- pkg/util/version_utils.go
- pkg/util/version_utils_test.go
Added functionality to `DynatraceClient` to be aware of the dynatrace server version:
It is possible to add the following option when creating a `DynatraceClient`:
You can choose between determining the server version automatically during construction of the `DynatraceClient`:
`NewDynatraceClient("http://xxxxx.com/","xxxx",WithAutoServerVersion())` or
determine the version on your own and pass it using:
`NewDynatraceClient("http://xxxxx.com/","xxxx",WithServerVersion(specificVersion))` 
(useful for testing, or situations where it is not convinient to do network calls during construction of the object.
The `download` CLI command now includes determining the Dynatrace server version and a check whether it is bellow
_"1.262.0"_ in which case we print out a warning. Execution of the command …
> feat: Implement Version Check for Settings 2.0 Upload on older DT servers

- cmd/monaco/runner/runner.go
Added a dedicated `monaco version` command as it is common practice for CLI tools:
```
$ monaco versoin
monaco version 2.x
```
> feat: Added `monaco version` command

- cmd/monaco/integrationtest/v2/config_restore_e2e_test.go
- pkg/client/client.go
- pkg/client/client_test.go
- pkg/util/afero_test_utils.go
Instead of requiring an HTTPS url, we now print a warning if the scheme is not HTTPS, but allow all values.
> feat: Allow HTTP urls

- .github/workflows/end-to-end-test.yml
Previously the release binary build step was not limited by the same condiation as other steps, which means it would execute on any PR label, but subsequently fail as no code or Makefile was checked out.
> ci(e2e): Only run release binary build on main or e2e label

- .github/workflows/end-to-end-test.yml
Using the simple condition that is applied to e2e tests is not enough to ensure that binaries are only build if code was checked out/the build was on main, scheduled or labeled to run a PR e2e test.
To ensure this works, the release binary step is run conditionally when either the base repo checkout condition, or the PR checkout conditions are met and there is actually code to build.
> ci(e2e): Actually match checkout conditions to run e2e build step

- cmd/monaco/download/download_command.go
- cmd/monaco/integrationtest/v2/integration_test_utils.go
- cmd/monaco/integrationtest/v2/non_unique_names_e2e_test.go
- cmd/monaco/runner/runner.go
- internal/featureflags/check_env_flag.go
- internal/featureflags/check_env_flag_test.go
- internal/idutils/external_id.go
- internal/idutils/external_id_test.go
- internal/idutils/me_utils.go
- internal/idutils/me_utils_test.go
- internal/idutils/uuid_generator.go
- internal/idutils/uuid_generator_test.go
- pkg/client/client.go
- pkg/client/config_client_test.go
- pkg/client/settings_client_test.go
- pkg/delete/delete.go
- pkg/deploy/deploy.go
- pkg/download/entities/entities.go
- pkg/download/entities/entities_test.go
- pkg/download/settings/settings.go
- pkg/download/settings/settings_test.go
follow up of https://github.com/Dynatrace/dynatrace-configuration-as-code/pull/832
* group id related code into `internal/idutils`
* renamed `internal/environment` package to `internal/featureflags`
> chore: cleanup packages

- .dependencies/templates/dependencies.csv.tmpl
- .github/workflows/dependencies-and-licenses.yml
Extended template produces the following:  
[deps.txt](https://github.com/Dynatrace/dynatrace-configuration-as-code/files/10816260/deps.txt)
> Include license texts in generated SBOM

- cmd/monaco/integrationtest/v1/integration_test_utils.go
- cmd/monaco/integrationtest/v2/cleanup_all_configs_test.go
- cmd/monaco/integrationtest/v2/integration_test_utils.go
- cmd/monaco/integrationtest/v2/non_unique_names_e2e_test.go
- pkg/client/client.go
- pkg/client/client_test.go
- pkg/client/dummy_client.go
- pkg/client/limiting_client.go
- pkg/client/limiting_client_test.go
- pkg/client/settings_client.go
- pkg/client/settings_client_test.go
- pkg/delete/delete.go
- pkg/delete/delete_test.go
- pkg/deploy/deploy.go
- pkg/deploy/deploy_test.go
- pkg/download/classic/downloader.go
- pkg/download/classic/downloader_test.go
- pkg/download/settings/filter.go
- pkg/download/settings/filter_test.go
Changes in upsert logic:
* get settings2.0 object with matching origin Object ID instead of external ID, if a setting obj was found and tenant version is < 1.262 we print the warning
* Deleted PUT operation on settings endpoint as it is not needed. POST endpoint now handles both, creating and updating settings objects
Further:
* deleted settings download filters that are not needed anymore with recent changes in settings fw
* Adjusted methods names of ConfigClient interface to contain reflect the fact that it is manipulating Configs as these interfaces are embedded into a bigger one and its clearer what each method does
btw: I don't know why legacy integration tests fail on GH. I ran them from my local machine, and it was running fine.
> Fix: Enhance settings upsert logic to work with current enhancements of the settings API

- .github/dependabot.yml
Dependabot config was not yet updated to the new user group in the Dynatrace org.
> chore: Fix dependabot reviewer group

- cmd/monaco/integrationtest/v2/pagination_e2e_test.go
The nightly pagination test didn't work anymore since we changed the Settings upsert mechanism and can no longer discern between updates and creation and the test asserts were based on log output alone.
Instead the test now asserts the number of logged API calls for create/update as well as that all test objects are available on the environment.
> test(e2e): Assert created configs instead of logs in pagination test

- cmd/monaco/cmdutils/cmdutils.go
- cmd/monaco/convert/command.go
- cmd/monaco/convert/convert.go
- cmd/monaco/convert/convert_test.go
- cmd/monaco/delete/command.go
- cmd/monaco/delete/delete.go
- cmd/monaco/deploy/command.go
- cmd/monaco/purge/command.go
- cmd/monaco/purge/purge.go
- cmd/monaco/runner/runner.go
- cmd/monaco/version/command.go
Instead of defining nearly all commands in the runner.go file, move each command in its own cmd-package.
This makes the runner.go very slim as now only the command-usages are registered. 
With that, the unused err was also found.
> Restructure cmd package and split runner.go

- Makefile
- cmd/monaco/delete/delete.go
- cmd/monaco/deploy/deploy.go
- cmd/monaco/download/download.go
- cmd/monaco/download/download_command.go
- cmd/monaco/download/download_integration_test.go
- cmd/monaco/integrationtest/integration_test_utils.go
- cmd/monaco/integrationtest/v2/non_unique_names_e2e_test.go
- cmd/monaco/integrationtest/v2/settings_integration_test.go
- cmd/monaco/integrationtest/v2/test-resources/integration-settings/project/config.yaml
- cmd/monaco/purge/purge.go
- go.mod
- go.sum
- pkg/client/client.go
- pkg/client/client_test.go
- pkg/client/config_client.go
- pkg/client/config_client_test.go
- pkg/client/extension_upload.go
- pkg/client/extension_upload_test.go
- pkg/client/settings_client_test.go
- pkg/client/test_utils.go
- pkg/client/version_check.go
- pkg/client/version_check_test.go
- pkg/manifest/manifest_loader_test.go
- pkg/rest/request.go
- pkg/rest/request_test.go
- pkg/rest/retry.go
* PR contains changes that allow passing an `http.Client` that hides the authorization mechanism to the `DynatraceClient`.
Example Usage:
```golang
client.NewDynatraceClient(client.NewTokenAuthClient(environment.Token), envURL, client.WithAutoServerVersion())
``` 
or
```golang
client.NewDynatraceClient(client.NewOAuthClient(oauthCredentials), envURL, client.WithAutoServerVersion())
```
> Feat: Prepare `DynatraceClient` to support OAuth authorization

- pkg/converter/converter.go
- pkg/converter/converter_test.go
In Monaco, the name is required. In Monaco-v1, if skipDeployment was set to true, it was never required, but it is in Monaco v2. To minimize user confusion, we generate a name for them, even though the config does not have one in v1.
> fix: Conversion - Create config name where none exists

- cmd/monaco/delete/delete.go
- cmd/monaco/deploy/deploy.go
- cmd/monaco/deploy/deploy_test.go
- cmd/monaco/download/download.go
- cmd/monaco/integrationtest/integration_test_utils.go
- cmd/monaco/integrationtest/v2/cleanup_all_configs_test.go
- cmd/monaco/integrationtest/v2/non_unique_names_e2e_test.go
- cmd/monaco/purge/purge.go
- pkg/converter/converter.go
- pkg/converter/converter_test.go
- pkg/manifest/manifest.go
- pkg/manifest/manifest_loader.go
- pkg/manifest/manifest_loader_test.go
- pkg/manifest/manifest_persitence.go
- pkg/manifest/manifest_test.go
- pkg/manifest/manifest_writer.go
- pkg/manifest/manifest_writer_test.go
This PR simplifies the URL handling of the Manifest.
Instead of loading the URL when needed, we now resolve it when the manifest is loaded.
This allows us to simplify each call.
Additionally, this change 
* makes the UrlDefinition public instead of private, allowing even easier access and initialization of the Manifest
* splits up persistence and representation. Before it was mixed
* improves documentation
* moves v1 code where it belongs
> ♻️ Simplify Manifest URL handling

- cmd/monaco/delete/delete.go
- cmd/monaco/deploy/deploy.go
- cmd/monaco/download/download.go
- cmd/monaco/integrationtest/integration_test_utils.go
- cmd/monaco/purge/purge.go
- pkg/manifest/manifest.go
- pkg/manifest/manifest_loader.go
- pkg/manifest/manifest_loader_test.go
- pkg/manifest/manifest_writer.go
- pkg/manifest/manifest_writer_test.go
- pkg/project/v2/project_loader_test.go
To represent OAuth in the Environment, we move the Token from the Environment's root to the field 'Auth'. The new field OAuth in the Auth object contains all fields necessary for OAuth.
> feat: Define internal representation for OAuth

- cmd/monaco/download/download.go
- cmd/monaco/download/download_command.go
- cmd/monaco/download/download_configs.go
- cmd/monaco/download/download_entities.go
The function did the actual loading of the manifest plus very simple get operation on the loaded manifest, which can be done directly
> refactor: Removed getEnvFromManifest file

- cmd/monaco/delete/command.go
- cmd/monaco/delete/delete.go
- pkg/delete/delete_loader.go
- pkg/delete/delete_loader_test.go
The is no clear reason why 2.x should retain the restriction of delete yamls, being exactly named delete.yaml. Unlike 1.x the delete command accepts any file path and will load and parse delete entries from it, instead of looking for a defined 'delete.yaml' in the folder 'monaco deploy' is being executed in.
In addition:
- the filename restriction did not validate the file, but the full path, meaning delete had to be executed in the folder containing the delete.yaml for input validation not to fail
- the delete loaded needlessly split and recombined a given filepath into a directory and the filename. This is replaced by simply trying to get the absoulte path to the given delete yaml file.
> feat(delete): Remove restriction on delete yaml filename

- cmd/monaco/download/download.go
The previous default of 50 was found to be much to high for most Managed environments with internal firewalls/rate-limiting setups.
To be safe the default is reduced drastically to 5 and increasing it will be documented
> feat(download): Reduce default concurrent downloads to 5

- internal/environment/get_env_value.go
- pkg/client/errors.go
To bring the now documented environment variable in line with all other monaco configuration env vars, a MONACO_ prefix is added.
> feat(download): Rename concurrent request limit env var

- cmd/monaco/convert/convert_test.go
- cmd/monaco/integrationtest/v2/non_unique_names_e2e_test.go
- pkg/config/v2/config_loader_test.go
- pkg/converter/converter.go
- pkg/converter/converter_test.go
- pkg/download/download_writer.go
- pkg/manifest/manifest.go
- pkg/manifest/manifest_loader.go
- pkg/manifest/manifest_loader_test.go
- pkg/manifest/manifest_persitence.go
- pkg/manifest/manifest_writer.go
- pkg/manifest/manifest_writer_test.go
- pkg/project/v2/project_loader_test.go
Allow users to specify OAuth credentials
**User-visible changes**
* Introduces a new property [config].auth that should hold all authentication-related information from now on.
* Deprecates the property [config].token, as [config].auth.token should be used from now on.
* A warning is printed if [config].token is used.
**Library changes**
* Token, ClientId, ClientSecret use the same data structure and thus have the same behavior
* Unexperted some symbols
* Inlined 'NewEnvironmentDefinition' as it has no use anymore. The type does no longer use interfaces, and more properties have been added. Adding them to a method would not make sense.
**Example**
```yaml
manifestVersion: 1.0
projects: [{name: proj}]
environmentGroups: 
- name: environment-group
environments:
- name: my-oauth-environment …
```
> ✨ OAuth support

- cmd/monaco/deploy/deploy.go
some of the v1 (integration) tests verify error messages returned by the deploy command, which were failing because of the wrapped error at the end of deploy. I've reverted this change.
> fix: fix failing v1 test

- Makefile
The RELEASES variable needs to be defined before build-release so that it actually contains values when calling build-release without any defined RELEASES as argument. If defining it after build-release it is empty by default and results in the 'make build-release' doing nothing but delete the bin and build folders.
> build: Ensure build-release make target works without arguments

- .dependencies/templates/dependencies.csv.tmpl
- .github/workflows/dependencies-and-licenses.yml
The extended SBOM content was broken by not removing the CI action's content sorting (which made sense when the BOM contained just individual lines of dependencies instead of full licenses)
This is fixed by removing the sort and simplifying the action steps overall.
Additionally, the BOM template is modified to provide an overview list of depencies again.
A final commit changes the action to run when a release is created and uploads the BOM directly as an asset rather than storing it as a build artefact.
---
This workflow was tested locally (as it would need to be in main to trigger for a release event) using [act](https://github.com/nektos/act) and a re-created release event
Test release:
https://github.com/Dynatrace/dynatrace-configuration-as-code/releases/tag/untagged-9694d0928257df0855 …
> Fix SBOM content and change action to upload to release directly

- Dockerfile
Defining the entry point as a single string rather than an array in the latest version of the Docker file, results in the container behaving differently than before.
Arguments passed to a docker run which would previously directly be used as arguments to monaco are currently ignored and the container always prints the help text.
Chaning the entry-point back to a definition as array, changes docker's behaviour and passes any additional arguments/CMD set on run as arguments to the monaco binary defined as entry point.
For details on differences between defining ENTRYPOINT as single value string as as array see: https://stackoverflow.com/a/62206472
> fix(docker): Ensure additional arguments can actually be passed to Docker container

- pkg/config/v2/config.go
- pkg/config/v2/config_loader_test.go
- pkg/converter/converter.go
Properties of the toplevel Config object must not be re-defined as parameters, but 'name' was missing from the slice that is used to validate this.
As conversion also uses this slice in two places to ensure conversion does not produce invalid overlaps with v2 reserved parameter names, the exclusion for 'name' thas was already in place at one callsite is moved to the method called in both cases.
Additionally the method is documented and renamed to make it clear(er) what it is meant to do.
> fix(config): Add 'name' to list of reserved parameters

- cmd/monaco/cmdutils/cmdutils.go
- cmd/monaco/cmdutils/cmdutils_test.go
- cmd/monaco/deploy/deploy.go
- cmd/monaco/download/download_command.go
- cmd/monaco/download/download_configs.go
- pkg/client/client.go
- pkg/client/version_check.go
- pkg/client/version_check_test.go
WIth this PR we do a basic call to the version endpoint of the configured environment to verify that credentials (oauth or basic token) are correct. Based on the manifest environment type field it is distinguished whether to call the platform gen version endpoint or the classic gen version endpoint. If a call fails for a single environment the error is propagated back to main and the program stops.
> feat: check cluster generation download/deploy 

- pkg/manifest/manifest_loader.go
To make it clear to users what fields have to be changed, the warning messages needs to contain the correct field-names.
> fix: Field names are wrong in warning message

- .github/PULL_REQUEST_TEMPLATE.md
Adds a GitHub PR template so that we can have an overall suggestion on how to format PRs.
This is an alternative template to https://github.com/Dynatrace/dynatrace-configuration-as-code/pull/890 and proposes a quite minimal template. The team should discuss/decide which way to go.
> chore: Add GitHub PR-template

- cmd/monaco/cmdutils/cmdutils.go
- cmd/monaco/cmdutils/cmdutils_test.go
- cmd/monaco/download/download_command.go
- pkg/manifest/manifest.go
- pkg/manifest/manifest_loader.go
- pkg/manifest/manifest_loader_test.go
- pkg/manifest/manifest_persitence.go
- pkg/manifest/manifest_writer.go
- pkg/manifest/manifest_writer_test.go
- pkg/oauth2/endpoints/endpoints.go
Some customers have their own SSO OAuth systems connected with Dynatrace. Or like Dynatrace, have more than one OAuth authorization system. For that purpose, it must be possible to specify OAuth `tokenEndpoint` address. 
With this PR new section `tokenEndpoint` inside `oAuth` will be defined (see example). If `tokenEndpoint` is not provided, the default one `https://sso.dynatrace.com/sso/oauth2/token` will be used.
``` yaml
environmentGroups:
- environments:
- auth:
oAuth:
clientId:
name: ENV_CLIENT_ID
clientSecret:
name: ENV_CLIENT_SECRET
tokenEndpoint:
value: "https://sso.dynatrace.com:443/sso/oauth2/token"
```
> Feat: Enable explicit specification of SSO OAuth token_endpoint in manifest.yaml

- .ci/releasePipeline.groovy
Change the image name from 'monitoring' to 'configuration'.
Also, drop the extra 'monaco' that was added after the registry url
(previous image name was actually `monaco/dynatrace-monitoring-as-code`)
Additionally, the container image push function in the release pipeline is modified, to prepare it for being called for different registries than the current internal one.
> ci: Rename docker container image to dynatrace-configuration-as-code

- cmd/monaco/cmdutils/cmdutils.go
- cmd/monaco/cmdutils/cmdutils_test.go
- cmd/monaco/deploy/deploy.go
- cmd/monaco/download/download_command.go
- cmd/monaco/download/download_configs.go
- cmd/monaco/runner/runner.go
- pkg/client/client.go
- pkg/client/metadata.go
- pkg/client/metadata_test.go
- pkg/client/version_check.go
- pkg/client/version_check_test.go
The current solution implemented with https://github.com/Dynatrace/dynatrace-configuration-as-code/pull/883 has a very bad user experience. Especially the error logs are bad and confuse the user.
This PR tries to improve on that and introduces
* enhanced logging
* GetDynatraceClassicURL to determine the classic gen URL
* RespErr returned from GetVersion and GetDynatraceClassicURL
* explicit handling of 403 in cluster gen checks
* better log messages
* deduplication of error logs
Additionally, it turned out that the version endpoint of the platform will be removed. for the sake of still verifying platform tenants, we make a call to: `/platform/core/v1/environment-api-info`
:exclamation: this is only currently available and will need to be changed to …
> Fix: Enhance cluster generation checks

- cmd/monaco/cmdutils/cmdutils_test.go
As we differentiate between different types of tests via build tags, the missing tag is added to a unit test - so it won't run with e.g. e2e tests
> chore: Add 'unit' build tag to newly added test

- cmd/monaco/cmdutils/cmdutils.go
If the DT generation validation failed with an expected (non HTTP code) error, we previously swalled the actual error completely, making this case impossible to debug based on the logs alone. Thus the error is now included in the log.
> fix: Log underlying error when Dynatrace generation check fails

- cmd/monaco/cmdutils/cmdutils.go
The PR fixes a misleading error message in case the user provides a totally wrong (not just one with missing scopes) or empty auth token to monaco.
In that case, the API returns 401 which should also be checked for before giving the user the error message that
(s)he might consider checking the type of environment (classic/platform)
none
Error logs are corrected
> fix: Also check for status code 401 before printing error

- pkg/client/client.go
- pkg/download/entities/entities.go
- pkg/download/entities/entities_test.go
To simplify logging of an EntitiesType, a String method is added that omits its ToRelationsips and Properties maps and instead just returns the ID.
This however means that if these fields should ever be included in log output, they need to be printed explicitly.
This change will result in log output of: 
```sh
2023/03/21 09:36:21 ERROR Did not find all provided entities Types. 
- 2 Types provided: [SOMETHING SOMETHING_ELSE] 
- 1 Types found: [SOMETHING].
```
---
This is a suggested change to #903 which felt like it was best described directly in code rather than words
> refactor: Add String method to EntitiesType for simplify its use in logs

- cmd/monaco/download/download_command.go
- cmd/monaco/download/download_command_test.go
- cmd/monaco/download/download_configs.go
- cmd/monaco/download/download_entities.go
- cmd/monaco/download/download_integration_test.go
- pkg/client/client.go
- pkg/client/client_test.go
- pkg/download/entities/entities.go
- pkg/download/entities/entities_test.go
Make it possible to download only specific entity types, not all of the environment at once, when necessary
> feat: allow download of specific entity types

- .github/workflows/collect-test-results.yml
ci: Allow Unit Test workflow to write PR comments again
The workflow currently fails to write PR comments with a 403 error, but as it uses the issues/(id)/comment API, giving it permission to write issues should solve that problem
I'm not actually 100% sure that issues: write will work, we might need pull-requests: write instead, but testing this with an actual token will sadly only work once this is part of main
nope
> ci: Allow Unit Test workflow to write PR comments again

- pkg/client/metadata.go
- pkg/client/metadata_test.go
- pkg/client/version_check.go
- pkg/client/version_check_test.go
- pkg/manifest/manifest_loader.go
- pkg/manifest/manifest_loader_test.go
When you define the environment URL (and probably also token-sso URL) with a trailing slash, the version check will fail. The reason is, that we concatenate the two paths, and it results in a double-slash (//).
This is dealt with in two ways by this PR: 
1. The underlying version check and metadata client code are changed to actually be fine with trailing slashes
2. Manifest loading trims trailing slashes
As mentioned in the second commit, the trimming of trailing slashes in manifest loading is a band-aid so this won´t  happen that easily if someone next joins URL paths with string concatenation. 
Long term the client code should be moved to using url.URL objects, which have join methods resilient to this issue. 
As there's big changes to the client incoming to support oAuth/Platform, …
> fix: Ensure trailing slashes in manifest-url definition don't lead to errors in version-check 

- .github/workflows/collect-test-results.yml
The previously introduced issues: write permission does not actually cover writing PR comments.
The change to give this worklow 'pull-request: write' permissions, means that it could theoretically also open new PRs. As it only wrongs in the main repo context after a unit test workflow has finished, and does not actually have permission to write any code (contents), there's no risk in these unecessarily elevated permissions.
See also commit 93754ba
> ci: Actually allow Unit Test workflow to write PR comments again

- cmd/monaco/download/download.go
- cmd/monaco/download/download_configs.go
- cmd/monaco/download/download_configs_test.go
- cmd/monaco/download/download_entities.go
- cmd/monaco/download/download_integration_test.go
- pkg/download/download_writer.go
- pkg/download/download_writer_test.go
This PR contains changes to ensure that OAuth information inside a `manifest.yaml` file is not lost after
executing `monaco download manifest ...`
Fixes generated `manifest.yaml` file
> Fix: OAuth credentials lost after `monaco download manifest ...` 

- cmd/monaco/cmdutils/cmdutils.go
- cmd/monaco/cmdutils/cmdutils_test.go
- cmd/monaco/download/download_command.go
- pkg/client/client.go
- pkg/client/client_test.go
- pkg/manifest/manifest.go
- pkg/manifest/manifest_loader.go
- pkg/manifest/manifest_loader_test.go
- pkg/manifest/manifest_writer.go
- pkg/manifest/manifest_writer_test.go
We decided that the responsibility of loading the default Dynatrace SSO token URL should be encapsulated in the Dynatrace Client, rather than manifest loading.
This is achieved by having the manifest treat the token URL as a pointer, and loading the default URL when nothing was given to the client on instantiation.
> refactor: Move loading of default TokenURL to client

- pkg/deploy/deploy.go
- pkg/deploy/deploy_test.go
As Settings do not have a general 'name' field, the client currently just returns the objectID as both name and ID of created entities.
This causes problems if a user tries to reference the name of Settings configuration in another config.
As we still require every configuration to define a name, this change simply extracts the name from the configuration rather than using data returned from the API/client, and sets it when deploying.
To not break if we ever decide the make the name property optional for Settings, a fallback to using the ID - but doing so explicitly with a warning - is implemented.
> fix: Use config name for created Settings objects

- cmd/monaco/cmdutils/cmdutils.go
- cmd/monaco/integrationtest/integration_test_utils.go
This fixes an oversight/bug in current main, which causes a nil pointer dereference, if no tokenURL is set in manifest. 
Additionally it fixes how clients are instanted for E2E tests, enabling us to run these tests against platform envs
> fix: Correctly instantiate Dynatrace client if no tokenURL is set

- .github/workflows/end-to-end-test.yml
Add new Platform Environment secrets to E2E builds. 
Split from #923 to allow the E2E test for that branch to actually run correctly (if this is merged first)
> ci: Pass new Platform test configuration to E2E tests

- cmd/monaco/download/download_integration_test.go
- cmd/monaco/integrationtest/assert.go
- cmd/monaco/integrationtest/cleanup.go
- cmd/monaco/integrationtest/v1/integration_test_utils.go
- pkg/config/v2/config.go
- pkg/config/v2/config_loader.go
- pkg/config/v2/config_loader_test.go
- pkg/config/v2/config_writer.go
- pkg/config/v2/config_writer_test.go
- pkg/config/v2/type_definition.go
- pkg/config/v2/type_definition_test.go
- pkg/converter/converter.go
- pkg/deploy/deploy.go
- pkg/deploy/deploy_test.go
- pkg/download/classic/downloader.go
- pkg/download/dependency_resolution.go
- pkg/download/dependency_resolution_test.go
- pkg/download/download_writer_test.go
- pkg/download/entities/entities.go
- pkg/download/entities/entities_test.go
- pkg/download/settings/settings.go
- pkg/download/settings/settings_test.go
- pkg/project/v2/project_loader_test.go
Until now, config.Type has been a struct that contains all possible fields. To check what type it is, several isX methods were implemented. This is convenient for a few types, but with more and more unmaintainable.
This change makes config.Type an interface that all types can implement. This allows us to add more types and only change a few places where it is necessary to distinguish the types. One decision was to force the users of the method 'deploy' to cast and check the type on their own. One alternative would have been to add generics to the config object. To accomplish this, we would have to change all methods where the config.Config type is used, and even then we are not sure if this would really work. Another alternative would have been to add a method 'getData' to the Type …
> feat: Make config.Config.Type an interface

- cmd/monaco/purge/purge.go
- pkg/delete/delete.go
This change adds purging all settings objects from one or more environments.
If settings should not be deleted, an opt-out flag is introduced to skip them.
> feat: Allow purge of settings objects

- cmd/monaco/cmdutils/cmdutils.go
- cmd/monaco/cmdutils/cmdutils_test.go
- cmd/monaco/delete/delete.go
- cmd/monaco/deploy/deploy.go
- cmd/monaco/download/download.go
- cmd/monaco/download/download_command.go
- cmd/monaco/download/download_command_test.go
- cmd/monaco/download/download_configs.go
- cmd/monaco/download/download_configs_test.go
- cmd/monaco/download/download_entities.go
- cmd/monaco/download/download_integration_test.go
- cmd/monaco/integrationtest/integration_test_utils.go
- cmd/monaco/integrationtest/v2/config_restore_e2e_test.go
- cmd/monaco/integrationtest/v2/non_unique_names_e2e_test.go
- cmd/monaco/purge/purge.go
- pkg/config/v2/config_loader_test.go
- pkg/converter/converter_test.go
- pkg/download/download_writer.go
- pkg/manifest/manifest.go
- pkg/manifest/manifest_loader.go
- pkg/manifest/manifest_loader_test.go
- pkg/manifest/manifest_writer.go
- pkg/manifest/manifest_writer_test.go
New DT platform requires OAuth authentication. To be able to download configuration without manifest from platform, new flags (`--oauth-client-id` and `--oauth-client-secret`) are added.
With this changes, redesign of `download` command has been done. 
With this changes all arguments of  `download` command are removed. With that, previous `monaco download manifest environment ...`  can be achieved with next `monaco download --manifest --environment`, while `monaco download direct <url> ...` with `monaco download --url --token ...`.
> Add OAuth support for `download direct`

- cmd/monaco/download/download_configs.go
- cmd/monaco/download/download_entities.go
Like other commands download needs to pass the specific environment it is running against to the manifest loader, to ensure that unused environments don't get parsed and require environment variables to be set for their tokens (and possibly URLs) which won't be used.
It appears download was missed, when limited loading was introduced to cope with the fact that Environment variable resolution was moved from 'at use' to 'at load' time.
> fix(download): Limit manifest loading to specified environments

- pkg/client/client.go
Debug message in client did not print the correct default token URL
--
Debug logs corrected.
> fix: Wrong Debug message for default token URL

- pkg/download/dependency_resolution.go
- pkg/download/dependency_resolution_test.go
fix(download): Resolve Settings references based on objectID not confgID
When downloading settings a UUID is generated as config ID (and template filename) to not
use the lenghty encoded objectID.
Doing so breaks resolving references for Settings objects, as other configurations will
of course contain the Setting's objectID and not our generated UUID.
To work around this the map of IDs used to match JSON content to configurations is extended
with an entry for the objectID, if a downloaded config contained an originObjectID (which
all downloaded Settings do, and as they were just downloaded, this origin ID is also what
will be referenced by other configs).
Also: fix(download): Use Coordinate ID when resolving dependencies
The previously used Template ID just happened to be equal to the …
> fix(download): Correctly resolve Settings references on download

- README.md
Also update the introductory sentence to the nicer version now found in the documentation.
> docs: Remove pre-release note from README

- internal/featureflags/featureflags.go
- pkg/config/v2/config.go
- pkg/config/v2/config_loader.go
- pkg/config/v2/config_loader_test.go
- pkg/config/v2/config_writer.go
- pkg/config/v2/config_writer_test.go
- pkg/config/v2/type_definition.go
- pkg/config/v2/type_definition_test.go
Allows users to specify automation-resources (workflows/scheduling-rules/business-calendars)
This feature is hidden behind the FF `MONACO_FEAT_AUTOMATION_RESOURCES`. Loading/storing w/o enabling this flag will error.
Additionally, some minor refactorings. See commit-by-commit.
```yaml
configs:
- id: config-id
type:
automation:
resource: workflow # OR business-calendar OR scheduling-rule
config:
…
```
> Allow users to specify automation resources

- .ci/releasePipeline.groovy
Currently a file with sha sum generated during the build process doesn't comply to the standard. With this changes this is fix.
> fix: generate sha sum correctly on jenkins

- pkg/api/endpoints.go
While a Settings schema builtin:request-attributes does exist, this is not final yet, and not actually available on the Settings API.
Thus the deprecation is removed from the classic Config API type to ensure it is still downloaded and usable without warnings.
see title & desc / commit
-
Yes, 1 less warning using the config & downloads of the API type happening again
> fix(api): Remove deprecation from request-attributes Config type

- pkg/client/client_test.go
- pkg/client/metadata.go
- pkg/client/metadata_test.go
The response payload of `/metadata/v1/classic-environment-domain` changed to conatin the field "domain" instead of "endpoint" which causes the resolution of the classic environment URL to fail.
> Fix: Resolving classic environment URL does not work

- internal/idutils/numeric_id.go
- internal/idutils/numeric_id_test.go
- pkg/download/dependency_resolution.go
- pkg/download/dependency_resolution_test.go
fix(download): Resolve Managment Zone references by numeric ID
Management zones are always referenced in configurations via their numeric
ID instead of a Config UUID or Settings objectID for backwards compatibility
reasons.
To still allow download code to correctly build reference parameters to
management zone Settings configurations, which are only known by their objectID,
code is introduced that leverages knowledge about how the numeric ID is formed
internally and transforms a given object ID into a numeric ID.
The implementation matches the logic of the Dynatrace implementation for
this as closely as possible.
This version contains the base change matching Dynatrace numeric ID generation, and simplifies our code in the second commit.
References to ManagementZones will be correctly …
> fix : Correctly resolve dependencies when downloading Settings 2.0 Management Zones

- pkg/deploy/deploy.go
- pkg/deploy/deploy_test.go
Move parameter-resolving and Rendering of a config into the Deploy function
Both functions "deploySettings" and "deployConfig" currently do parameter resolving and rendering. Automation resources will need it as well.
The goal of this story is to move this functionality one level up into the "DeployConfigs" function. With that, all future configs will work in the future as well.
> Move parameter-resolving and Rendering of a config into the Deploy function

- pkg/client/automation/client.go
- pkg/client/automation/client_test.go
- pkg/client/automation/error.go
This PR provides a client implementation to handle Automation resources (Workflow, SchedulingRules, and BusinessCalendars). Currently, only the **upsert** operation is implemented. Operations for reading, listing, and deleting resources will be implemented in another story.
Usage is as follows:
```go
c := automation.NewClient("http://dt-url.com", client.NewAuthClient(context.TODO, oauthCredentials), automation.Workflows)
obj, err := c.Upsert("85b95caa-5469-484b-baeb-161104f7459f",data})
// handle err
``` 
Note that it is the responsibility of the caller to provide a generated ID or the Origin Object Id as `id` argument.
nah
> feat: Implemented automation client upsert operation

- pkg/deploy/deploy.go
- pkg/deploy/deploy_test.go
- pkg/deploy/entitymap.go
- pkg/deploy/entitymap_test.go
resolvedEntity already contains coordinate. Same coordinate can be used in put function
Simple refactoring to remove requests for an unnecessary and already redundant date for `entitymap.put function`
> refactor: Don't request coordinate to put  in entitymap

- .github/workflows/dependencies-and-licenses.yml
change the trigger action from release:created to release:published as the former does **not** trigger any workflows.  [1]
[1] https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#release
> fix: dependencies-and-licenses workflow not triggered on release

- Makefile
If the netgo build-tag is given, the pure Go resolver is forced to be used instead of the cgo provider. While this works fine most of the time, complex DNS configurations are not yet supported by the Go resolver. Since this issue only exists for windows, and the netgo tag is required for minimal docker-images (e.g. alpine), we now skip the tag for windows, but keep it for linux builds.
Make output: (if we would remove the @ of line 66)
```sh
> make build-release 
Removing monaco, bin/ and /build ...
Building binaries for monaco-windows-amd64.exe...
GOOS=windows GOARCH=amd64 CGO_ENABLED=0 go build -a  -ldflags '-X github.com/dynatrace/dynatrace-configuration-as-code/pkg/version.MonitoringAsCode=2.x -w -extldflags "-static"' -o ./build/monaco-windows-amd64.exe ./cmd/monaco
Building binaries …
```
> built: Do not include 'netgo' build tag in windows release-builds

- cmd/monaco/integrationtest/v2/test-resources/integration-all-configs/project/dashboard/config.yaml
- cmd/monaco/integrationtest/v2/test-resources/integration-all-configs/project/dashboard/overview-dashboard.json
- cmd/monaco/integrationtest/v2/test-resources/integration-all-configs/project/maintenance-window/config.yaml
- cmd/monaco/integrationtest/v2/test-resources/integration-all-configs/project/maintenance-window/maintenance-window.json
- cmd/monaco/integrationtest/v2/test-resources/integration-all-configs/project/maintenance-window/settings_config.yaml
- cmd/monaco/integrationtest/v2/test-resources/integration-all-configs/project/maintenance-window/settings_template.json
- cmd/monaco/integrationtest/v2/test-resources/integration-all-configs/project/management-zone/settings_config.yaml
- cmd/monaco/integrationtest/v2/test-resources/integration-all-configs/project/management-zone/settings_template.json
- internal/featureflags/featureflags.go
- pkg/client/dtclient/dummy_client.go
- pkg/deploy/deploy.go
- pkg/deploy/deploy_test.go
As Management Zones are still mostly referenced via their numeric ID in other Settings, their
ID needs to be resolved down to the numeric ID rather than Settings Object ID in all cases.
Without this change, their object ID would potentially be templated into other configurations that
reference a management zone's ID.
This feature is behind a new 'MONACO_FEAT_USE_MZ_NUMERIC_ID' flag, which is active by default.
Testing on latest version DT environments, it was found that non-deprecated APIs (like dashboards)
already support MZ references via Settings Object ID, but this may be different for older envs.
Thus the resolving to numeric ID when deploying happens by default but can be turned off if needed
/in the future.
-
Depending on DT environment version nothing might change, or currently …
> fix(deploy): Use numeric IDs for Management Zone Settings instead of ObjectID

- cmd/monaco/download/download.go
- pkg/download/download_writer.go
- pkg/download/download_writer_test.go
This PR adds code to randomize the project folder name _in case it already exists._ The project folder name is randomized using a **timestamp**, similar to what is done for the manifest file. (`project-name_TIMESTAMP`)
Tested with `--url` as well as `--manifest` option the output looks like:
* When downloading using `--url` or `--mananifest` using the same output folder (`-o`), the folder names are randomized if the folder already exists
> fix: Project folder is overwritten on monaco download

- Makefile
A previous fix removed the possibility to define the output filepath of a release build, which breaks the usage of this Make target in the release pipeline.
> build(make): Allow settings output filepath for release target again

- .github/workflows/dependencies-and-licenses.yml
Rather than the upload_url - which is a hypermedia resource template and thus not directly usable as our cUrl call assumed - use the plain assets URL also provided in the event.
This is less robust to changes of the API than actually parsing the resource template, but functional and less effort.
Note that while Github Actions exist to upload assets to releases, all of them are 3rd party actions - thus it was decided to keep this as a simple cUrl call rather than adding a new dependency to an action that's not directly supported/updated by GitHub either.
-
-
> ci(dep-and-licenses): Use plain assets URL from release event for asset upload

- cmd/monaco/download/download_configs.go
- cmd/monaco/download/download_configs_test.go
- cmd/monaco/download/download_integration_test.go
- cmd/monaco/download/downloaders.go
- cmd/monaco/download/downloaders_test.go
- pkg/download/classic/downloader.go
- pkg/download/classic/downloader_test.go
- pkg/download/downloader.go
- pkg/download/settings/settings.go
- pkg/download/settings/settings_test.go
Currently, we use `settings.Downloader` or `config.Downloader`, ... to handle downloading of the resp. configuration(s) from DT.
However, while they are very similar, they do not share a common interface. This means that adding yet another downloader (e.g. for automation resources) requires special logic as they cannot be treated uniformly.
This PR introduces a simple contract of how a downloader should be interfaced with: 
```
type Downloader[T v2.Type] interface {
Download(projectName string, specificConfigs ...T) (projectv2.ConfigsPerType, error)
}
``` 
It would be easily possible but I did **not** touch the code/interface for entity download. as this is handled completely on its own in a separate command.
Further, the interface is (imo) not perfect, e.g. the `projecName` is only …
> Refactor: Unify `Downloader`s interface

- .github/workflows/dependencies-and-licenses.yml
The previously used release.asset_url was also wrong for uploads, as it just contains the api.github URL at which assets can be downloaded.
Rather than parsing the Hypermedia URL that's contained in upload_url, this simply builds the URL directly using just the release ID from the event.
While this is not resilient to this URL changing, we do the same in our general release build - which has no access to github event data - so if this breaks, manual intervention to our release pipelines is needed anyway.
> ci: Build release asset upload URL directly for BOM upload action

- cmd/monaco/deploy/deploy.go
- internal/log/log.go
- internal/log/log_test.go
feat(deploy): Log number of projects, environments and (on debug) configs to deploy
It is sometimes helpful to get a quick overview of the number of projects and configurations
that are being deployed by just looking at the logs.
As collecting the number of configs requires counting them by running through all configs
per project, environment and type, this is limited to only happen when debug logging is
active.
- A simple way to check if debug is even currently active is added to our logger in it's own commit.
- Counting configs could be done elsewhere, e.g. while loading or sorting - this was just a quick addition on the side, if we think this is helpful but should be done more efficiently without extra iteration I'm happy to add counts to existing methods (which then get a bit more …
> feat(deploy): Log number of projects, environments and (on debug) configs to deploy

- go.mod
- go.sum
- pkg/download/dependency_resolution/dependency_resolution.go
- pkg/download/dependency_resolution/dependency_resolution_test.go
- pkg/download/dependency_resolution/resolver/ahocorasick_dep_resolver.go
Replace the cloudflare/ahocorasick library with anknown/ahocorasick, which was found to run at similar speed but with vastly reduced memory requirements - on a small environment needing just 27% of cloudflare's version, and on a huge (120k configs) test environment needing 57% of cloudflare.
Opened as draft to have a basis for discussion.
This pulls two dependencies from an individual developer with neither having tagged releases - while this Go implementation of Aho-Corasick is the second most starred one on GitHub, the dependence feels more brittle than the one to cloudflare's implementation. 
The memory reduction is significant though.
no
> refactor(download): Replace aho-corasick implemenation used in fast dependency resolver by a more memory efficient one

- pkg/client/dtclient/client.go
- pkg/client/dtclient/config_client.go
- pkg/rest/request.go
- pkg/rest/request_test.go
- pkg/rest/retry.go
#982
PR contains also a bit of cleanup/housekeeping.
Also, I've decided to get rid of "SendWithRetryWithInitialTry" and made it the default behavior.
Error logs/messages do not contain the term "upsert"
> chore: Don't use "upsert" term in error messages

- cmd/monaco/integrationtest/config_rewrite.go
- internal/throttle/throttle_requests.go
We use random number in tests and to add stutter to requests. Both cases are not cryptographically relevant. Semgrep still flags them as cryptographically insecure, so we mark them to be ignored
> chore: Add semgrep exclusion for random numbers

- internal/json/json.go
- internal/json/json_test.go
- pkg/download/automation/automation.go
- pkg/download/settings/settings.go
As the method already falls back to returning unchanged input if indenting it failed for any reason, and the error return was ignored in all production code usages, it is simply dropped.
Functionally monaco will still behave the same, printing a warning and writing unindented files in case a downloaded JSON could not be indented as expected.
> refactor(json): Remove unused error return from MarshalIndent utility

- .ci/releasePipeline.groovy
To ensure we log in to the registry correctly (login via sub-path, seems to cause issues for Docker Hub), the registry host and repo/project name are split into dedicated values, rather than having a single full path as input.
This should ensure that logins work, regardless of which regstriy we target, and that projects/repos can change independetly by modifying a single configuration.
I **believe** I was able to confirm the login being the issue for docker hub & have tested login to the internal registry as well. 
However, to really test this we'll have to push (and if it works manually delete) a test image to docker hub. 
For this a dedicated commit is added - if you think the PR is ok, I'll add test tag
> ci: Split Docker registry and repo path into separate inputs

- .github/workflows/dependencies-and-licenses.yml
In addition to the human readable long form dependencies-and-licenses.txt that is generate for each relase, add another SBOM in machine readable CycloneDB format.
This uses the official GitHub action by CycloneDX to generate the BOM.
See also https://cyclonedx.org/
An additional machine-readable SBOM can be downloaded for each release.
---
(txt ending because GH refuses XML files)
[sbom.xml.txt](https://github.com/Dynatrace/dynatrace-configuration-as-code/files/11422161/sbom.xml.txt)
> ci: Generate SBOM in machine readable CycloneDX format

- cmd/monaco/integrationtest/config_rewrite.go
- cmd/monaco/integrationtest/v1/integration_test_utils.go
- cmd/monaco/integrationtest/v2/delete_integration_test.go
- cmd/monaco/integrationtest/v2/integration_test_utils.go
- cmd/monaco/integrationtest/v2/non_unique_names_e2e_test.go
- internal/rand/rand.go
- internal/rand/rand_test.go
- internal/throttle/throttle_requests.go
Benchmark information:
```
goos: windows
goarch: amd64
pkg: github.com/dynatrace/dynatrace-configuration-as-code/internal/rand
cpu: 11th Gen Intel(R) Core(TM) i9-11950H @ 2.60GHz
BenchmarkInt
BenchmarkInt-16                  3422638               343.5 ns/op            82 B/op          4 allocs/op
BenchmarkIntLegacy
BenchmarkIntLegacy-16             120304              9712 ns/op            5376 B/op          1 allocs/op
PASS
Process finished with the exit code 0
```
Code for the given benchmark:
```
func BenchmarkInt(b *testing.B) {
b.ReportAllocs()
for n := 1; n < b.N+1; n++ {
Int(int64(n))
}
}
func BenchmarkIntLegacy(b *testing.B) {
b.ReportAllocs()
for n := 1; n < b.N+1; n++ {
newRand := rand.New(rand.NewSource(time.Now().UnixNano()))
newRand.Int63n(int64(n))
}
}
```
The reason for …
> feat: Create custom random function

- pkg/client/transport.go
- pkg/rest/request.go
With introducing oAuth support, we have lost the dedicated user-agent from the oAuth client (never added) as well as API token authenticated connects (not sent/ overwritten somewhere after the Transport struct it was added to).
To ensure we don't forget to send this with any future client implementations, setting the User-Agent header is moved to the lowest possible layer in our API call methods, the final rest/request method that actually calls the http/client.
> fix(rest): Re-introduce custom user-agent at the lowest REST lib layer

- cmd/monaco/deploy/command.go
- cmd/monaco/download/download_command.go
- cmd/monaco/download/download_command_test.go
- cmd/monaco/purge/command.go
- pkg/client/dtclient/client.go
- pkg/download/download_writer.go
- pkg/download/entities/entities.go
This change fixes numerous typos and fixes some sentence structures.
Additionally, this PR introduces a single quite (') within the commands as the quote to be used to reference flags. This should be used from now on everywhere consistently.
> fix: Typos and sentence structures.

- cmd/monaco/integrationtest/assert.go
- cmd/monaco/integrationtest/cleanup.go
- cmd/monaco/integrationtest/v2/diff_project_diff_ext_id_test.go
- cmd/monaco/integrationtest/v2/settings_integration_test.go
- cmd/monaco/integrationtest/v2/test-resources/integration-different-projects-different-extid/manifest.yaml
- cmd/monaco/integrationtest/v2/test-resources/integration-different-projects-different-extid/project1/builtinanomaly-detection.metric-events/a5c32c04-6d12-3c32-84aa-21a8113d36cd.json
- cmd/monaco/integrationtest/v2/test-resources/integration-different-projects-different-extid/project1/builtinanomaly-detection.metric-events/config.yaml
- cmd/monaco/integrationtest/v2/test-resources/integration-different-projects-different-extid/project2/builtinanomaly-detection.metric-events/a5c32c04-6d12-3c32-84aa-21a8113d36cd.json
- cmd/monaco/integrationtest/v2/test-resources/integration-different-projects-different-extid/project2/builtinanomaly-detection.metric-events/config.yaml
- cmd/monaco/integrationtest/v2/test-resources/integration-settings-old-new-external-id/manifest.yaml
- cmd/monaco/integrationtest/v2/test-resources/integration-settings-old-new-external-id/project/builtinanomaly-detection.metric-events/a5c32c04-6d12-3c32-84aa-21a8113d36cd.json
- cmd/monaco/integrationtest/v2/test-resources/integration-settings-old-new-external-id/project/builtinanomaly-detection.metric-events/config.yaml
- internal/idutils/external_id.go
- internal/idutils/external_id_test.go
- pkg/client/dtclient/client.go
- pkg/client/dtclient/client_test.go
- pkg/client/dtclient/dummy_client.go
- pkg/client/dtclient/settings_client.go
- pkg/client/dtclient/settings_client_test.go
- pkg/delete/delete.go
- pkg/deploy/settings.go
This PR changes the way we generate external IDs for settings 2.0 object to use the "full Coordinate" (projectname, schemaID, ID) in order to support using the same configuration in multiple projects by multiple "users".
To stay backwards compatible, we still calclulate the "old" external id (without project name included) and try to update already existing settings objects accordingly.
> feat: use full coordinate when generating external ids for settings 2.0 objects

- cmd/monaco/delete/delete.go
- cmd/monaco/integrationtest/v2/delete_integration_test.go
- cmd/monaco/integrationtest/v2/test-resources/delete-test-configs/project/auto-tag.json
- cmd/monaco/purge/purge.go
- pkg/delete/delete.go
- pkg/delete/delete_loader.go
- pkg/delete/delete_loader_test.go
- pkg/delete/delete_test.go
As the 'externalID' by which Settings are identified by monaco is extended to include the project (full coordinate - project,type,id) - the simple string format is no longer enough to define delete entry.
A new format is added that defines a structured project, type and name or ID delete entry.
Loading is extended to be able to load both the full and the old simple format.
This PR still includes several PRs as it depends on the extended external ID generation to be fully functional.
As that part is also in progress, this is left as draft for early review - other than these TODOs it should be ready for review
Delete YAML format changes to a structured format. 
Old format is still usable, but for Settings will produce a warning log.
```yaml
delete: 
- project: "project"
type: …
```
> feat(delete): Introduce structured delete definition

- pkg/config/v2/config_writer.go
- pkg/config/v2/config_writer_test.go
Monaco is often used to download configurations from the same environment at two different points in time. Until now, it was pretty hard to compare the configs as they were written in the order we downloaded them.
This change orders the configs before writing them to files, thus simplifying comparing incremental changes or the difference between two environments. We achieve the ordering by simply ordering by the config-id within a file, as the API already splits downloaded files, and thus, the ID is unique within a file.
The configs are ordered after a download 🔥 
I did the following to verify the changes:
1) Downloaded the same environment twice, one after another. 
2) Used a tool to compare the downloaded projects. 
3) The two projects matched 1:1, each config is sorted by id
> feat: Write downloaded configs in a stable order

- pkg/delete/delete_test.go
Reactivate a test that had been skipped due to the external ID calculation being changed
> test(delete): Reactivate Settings Delete test with extended externalID

- cmd/monaco/delete/delete.go
- cmd/monaco/integrationtest/assert.go
- cmd/monaco/integrationtest/integration_test_utils.go
- cmd/monaco/integrationtest/v2/delete_integration_test.go
- cmd/monaco/integrationtest/v2/test-resources/delete-test-configs/deploy-manifest.yaml
- cmd/monaco/integrationtest/v2/test-resources/delete-test-configs/project/workflow.json
- pkg/client/automation/client.go
- pkg/client/automation/client_test.go
- pkg/config/v2/type_definition.go
- pkg/config/v2/type_definition_test.go
- pkg/delete/delete.go
- pkg/delete/delete_loader.go
- pkg/delete/delete_test.go
- pkg/download/automation/automation.go
Allows deletion of automation resoruces.
This PR is done to "make it work"! There are a few small refactorings in dedicated commits, but there are rough edges in setup that I'd like to address in followup PRs and purposely ignored here.
Followup improvements are: 
- Refactor Automation Client setup! Unlike the "DynatraceClient" that's uniformly setup by a util shared between commands, each command currently sets up the AutomationClient in dedicated code. This should IMO move into the shared Client setup.
- Refactor UUID generation! Re-using the "FromName" with a coordinate string is strange, would introduce a from Coordinate
- Mapping from config.AutomationResource to the client's resource iota is clunky and done in several places. I'd like to introduce a single mapper that can be reused …
> feat: Allow Automations Deletion

- cmd/monaco/download/download_command.go
- cmd/monaco/download/download_configs.go
- cmd/monaco/integrationtest/v2/test-resources/integration-automation/project/workflow/c5a71c83-9dbd-458d-b42d-d48b098c60ed.json
- cmd/monaco/integrationtest/v2/test-resources/integration-download-configs/project/workflow/c5a71c83-9dbd-458d-b42d-d48b098c60ed.json
- cmd/monaco/integrationtest/v2/test-resources/integration-download-configs/project/workflow/config.yaml
- pkg/download/automation/automation.go
- pkg/download/automation/automation_test.go
- pkg/download/automation/internal/jinja.go
- pkg/download/automation/internal/jinja_test.go
- pkg/download/automation/testdata/listWorkflowsWithJinja.json
Workflow definition can also accept Jinja templates. To avoid mixing of resolutions, workflow templates need to be escaped. With these changes, all jinja templates downloaded from DT instance like ```{{ .var }} ```  will be escaped with ```{{`{{`}} .var {{`}}`}} ```
`--only-automation` flag behaves in a similar way as already existed `--only-apis` and `--only-setings`
This PR replaces https://github.com/Dynatrace/dynatrace-configuration-as-code/pull/996
> escape jinja templates

- cmd/monaco/integrationtest/assert.go
- cmd/monaco/integrationtest/v2/non_unique_names_e2e_test.go
- internal/idutils/uuid_generator.go
- internal/idutils/uuid_generator_test.go
- pkg/client/dtclient/config_client_test.go
- pkg/delete/delete.go
- pkg/deploy/automation.go
- pkg/deploy/classic.go
- pkg/download/entities/entities.go
- pkg/download/entities/entities_test.go
- pkg/download/settings/settings.go
- pkg/download/settings/settings_test.go
Replaces the usage of `FromName` UUID generation for Automations with a dedicated `FromCoordinate` method - making usage and reading clearer IMO.
- small followup refactor of #1004
NO
> Refactor UUID generation from Coordinate

- cmd/monaco/download/download_integration_test.go
- cmd/monaco/download/test-resources/integration-test-dashboard/dashboard/__LIST.json
- cmd/monaco/download/test-resources/integration-test-dashboard/dashboard/id-4.json
- cmd/monaco/download/test-resources/integration-test-dashboard/dashboard/id-5.json
- pkg/download/classic/filter.go
- pkg/download/classic/filter_test.go
Preset Dashboards that are "pre-installed" and owned by Dynatrace are ignored during a download using Monaco, as these Dashboards cannot be modified by the user at all and re-deploying them will result in an error. 
However, we should not ignore preset dashboards defined by the user.
This PR changes the filter for persisting dashboards to skip dashboards only if they are presets AND owned by "Dynatrace"
Users are able to download dashboards marked as "preset" if they were created ba themselves
> fix: User defined preset dashboards are ignored

- pkg/project/v1/project.go
- pkg/project/v1/project_test.go
fix(convert): Consider environment overrides when renaming duplicate config IDs
The previous conversion failed to consider v1 environment overrides, which are of the form [config ID].[environment].
This fix overwrites config IDs both for the base property and any that follow the format of a v1 override.
YES - conversion does not break environment overrides anymore if a config ID was renamed as duplicate.
Additionally, a warning is printed that possible references may need manual review. 
These references would already have been broken for v1 deployments - but if they were made correct via overrides/skipping they might now point to the wrong configuration.
> fix(convert): Consider environment overrides when renaming duplicate config IDs

- pkg/download/automation/internal/jinja_test.go
Shotgun testing, the approach to have many asserts sequentially, often lacks readability, granularity, and scalability. It results in complex and less readable tests, making debugging difficult. It can lead to redundant test cases and becomes cumbersome to manage as the number of tests increases. In contrast, table testing offers structured and readable tests, with individual test cases for specific scenarios, allowing for easier debugging and scalability.
---
This change also makes the errors readable. (introduced an error on purpose)
From 
```
Error:      	Not equal: 
expected: []byte{0x7b, 0x7b, 0x60, 0x64, 0x64, 0x60, 0x7d, 0x7d, 0x20, 0x7b, 0x7b, 0x60, 0x7d, 0x7d, 0x60, 0x7d, 0x7d}
actual  : []byte{0x7b, 0x7b, 0x60, 0x7b, 0x7b, 0x60, 0x7d, 0x7d, 0x20, 0x7b, 0x7b, 0x60, 0x7d, 0x7d, …
```
> Use table test instead of shotgun testing

- pkg/config/v2/config_loader.go
- pkg/config/v2/config_loader_test.go
The override logic was missing logic required to allow overriding the `OriginObjectId`. The missing logic has been provided.
Fixes the override logic to also take the `OriginObjectId` into consideration.
> fix(config): allow override of `OriginObjectId`

- cmd/monaco/integrationtest/assert.go
- cmd/monaco/integrationtest/cleanup.go
- cmd/monaco/integrationtest/integration_test_utils.go
Deletes automation resources as part of E2E test cleanup
The nightly cleanup "test" (`cleanup_all_configs_test.go`) can NOT be extended to remove left over automation as there is no way to generally identify them by having a suffix or externalID.
Draft and targeting another PR as the changes depend on those of #1010
nope
> feat(e2e): Include Automation resources in E2E test cleanup

- .editorconfig
- .github/workflows/build-test.yml
- .github/workflows/pr-static-code-analysis.yml
- Makefile
- cmd/monaco/integrationtest/rewrite_functions_test.go
- internal/featureflags/featureflags.go
- internal/idutils/uuid_generator.go
- internal/log/log.go
- internal/log/log_test.go
- internal/log/log_unix_test.go
- pkg/config/v2/config_writer.go
- pkg/config/v2/config_writer_test.go
- pkg/config/v2/template/loader.go
- pkg/config/v2/template/loader_test.go
- pkg/delete/delete_loader_test.go
- pkg/manifest/manifest_loader_test.go
- pkg/project/v1/project_loader_test.go
Changes in this PR:
* Split the 'build' pipeline into 'verify', which tests the code style, and 'test', which executes all unit tests.
* The 'test' pipeline runs on Windows and Ubuntu (Linux).
Due to this change, bugs have been discovered and also fixed with this PR. Most notably, that the UUID generation, which should be consistent over operating systems, was not.
This PR fixes that but also introduces the `MONACO_FEAT_CONSISTENT_UUID_GENERATION` to disable this feature in case Monaco is run on Windows systems.
Additionally, the actual feature that we're now writing slashes instead of backslashes in files is in the first commits.
**⚠️Possible breaking change:** It might be that some configs are duplicated now if Monaco is used on Windows. The `MONACO_FEAT_CONSISTENT_UUID_GENERATION` can …
> Add Windows test-pipeline

- cmd/monaco/integrationtest/v2/test-resources/integration-all-configs/project/credential-vault/config.yaml
- pkg/client/dtclient/config_client.go
As the API currently consistently reports server errors, the test config is set to skip to ensure we don't lose all tests due to a single config not working on our Dynatrace test envs.
> chore: Skip credential-vault test resources

- cmd/monaco/integrationtest/assert.go
- cmd/monaco/integrationtest/cleanup.go
- cmd/monaco/integrationtest/integration_test_utils.go
- internal/automationutils/resource_type.go
- pkg/delete/delete.go
- pkg/deploy/automation.go
We had several places that implement the same switch on config.AutomationResource string to map it to the client's iota ResourceType.
This is simplified to a single internal util that is reused where needed.
Draft based on #1014 as this introduced a shared switch for integration test utils. 
This moves this further and reuses the switch everywhere
no
> refactor: Introduce shared util for converting config.AutomationResource to client ResourceType iota

- .ci/releasePipeline.groovy
- Dockerfile
Previously we accidentally built another binary and container with version set to 'latest' instead of adding a tag to the image for the specific release version.
-
`latest` container image is a tag of the latest release version image, not it's own binary and image with the version set to `latest`
> ci: Fix tagging container releases as 'latest'

- cmd/monaco/deploy/logging.go
- internal/log/log.go
- internal/loggers/console/console.go
- internal/loggers/loggers.go
- internal/loggers/zap/zap.go
- internal/loggers/zap/zap_test.go
(Re)introduces the log level guard when printing out details about how many configs will be deployed.
This check was [removed](https://github.com/Dynatrace/dynatrace-configuration-as-code/pull/1025/files#r1206538911) with the PR introducing structured logging. After review we've decided to put that back in with a follow up PR (this one) that introduces the possibility to get the current log level configuration from the logger.
> feat: add possibility to get current log level from the logger

- cmd/monaco/integrationtest/v2/duplicate_coordinates_produce_user_errors_e2e_test.go
- cmd/monaco/integrationtest/v2/references_test.go
- cmd/monaco/integrationtest/v2/test-resources/references/classic-apis/config.yaml
- cmd/monaco/integrationtest/v2/test-resources/references/invalid-classic-with-settings/config.yaml
- cmd/monaco/integrationtest/v2/test-resources/references/invalid-classic-with-settings/profile.json
- cmd/monaco/integrationtest/v2/test-resources/references/invalid-classic-with-settings/slack.json
- cmd/monaco/integrationtest/v2/test-resources/references/invalid-classic-with-settings/zone.json
- cmd/monaco/integrationtest/v2/test-resources/references/invalid-configs-manifest.yaml
- cmd/monaco/integrationtest/v2/test-resources/references/settings-with-classic-mngt-zone/config.yaml
- pkg/config/v2/config_loader.go
- pkg/config/v2/config_loader_test.go
Config API type configurations generally have a UUID or Monitored Entity ID, while newer configuration types like
Settings use IDs that are not compatible with what the Config API expects.
As users are migrating existing configuration over to Settings it happens that an existing Config API configuration
references the ID of something now managed as a Setting.
Deploying such a configuration will fail withe API reporting that the Settings objectID is not a valid ID - Config APIs
are not able to resolve the new base64 encoded objectID, while the Settings API accepts any type of ID.
To warn users as early as possible, such invalid references result in an error as soon as the configuration is loaded.
To be lenient, two exceptions exist:
- validation only applies to referencing a config's ID, …
> feat(config): Fail early if a Classic Config API config references anything but another Config API type

- cmd/monaco/integrationtest/v2/references_test.go
- pkg/manifest/manifest_loader.go
- pkg/manifest/manifest_loader_test.go
[fix(manifest): Report an error if project name is missing](https://github.com/Dynatrace/dynatrace-configuration-as-code/commit/ac34e5c82d044256ea8e58464279ccf07a9122f8)
While a project path can be omitted for convenience, a name is always needed,
and empty project names don't make a lot of sense.
Thus we now validate that a name is defined for each project when loading the
manifest.
Error is reported if a project is missing a name. 
In general, a project with an empty string name does not make a lot of sense and it can happen that users accidentally configure empty projects like this:
```
- name: srg
- path: srg
```
-> 
```
- name: srg
(implicit path = name)
- (implicit/default val = name: "") 
path: srg
```
when they really wanted one
```
- name: srg
path: srg
```
> fix(manifest): Report an error if project name is missing

- cmd/monaco/integrationtest/v1/test-resources/integration-all-configs/project/credential-vault/credentials.yaml
I missed that there is a cred-vault in the v1 test configs as well, which occoaisonally fails with a 500 error in the same way the one in the v2 test config does.
> chore: Skip credential-vault test resources in legacy tests

- cmd/monaco/integrationtest/v2/test-resources/delete-test-configs/project/workflow.json
The `TestDelete` 2e2 test in `delete_integration_test.go` failed with the following error while deploying the sample workflow:
`{"actor":["Cannot set workflow actor to a non-service user."]}}}`
When I've deleted the actor field in the workflow payload it is working.
I did spend some time trying to figure out why that is not a problem in another integration test that uses nearly the same payload, but I wasn't able to find out what makes it different.
> test: fixed automation deletion e2e test failure

- Makefile
- internal/log/log.go
- internal/log/log_test.go
- internal/loggers/console/console.go
- internal/loggers/fields.go
- internal/loggers/loggers.go
- internal/loggers/zap/zap.go
- internal/loggers/zap/zap_test.go
This PR adds the possibility to add custom fields to our structured logging.
Usage:
```go
log.WithFields(loggers.F("name", "johnny")).Info("Hello :) ")
```
For convenience, there are two functions that provide fields for monaco coordinates and enviroments
```go
log.WithFields(loggers.CoordinateF(c), loggers.EnvironmentField("env1")).Info("hello  :)")
``` 
It is still possible to use formatted "printf" style logging using the Info/Debug/etc... methods. This is actually one of the main reason why I didn't choose to pass the fields as an additional argument as it conflicts with the already existing variadic args parameter, which we use a lot.
> feat: Add possibility to add custom fields when using structured logging

- cmd/monaco/purge/purge.go
- pkg/delete/delete.go
- pkg/delete/delete_test.go
* Also include automation resources when executing purge/"delete all" 
* Use Settings 'ModificationInfo' to skip deletion of objects early if they're marked non-deletable
- A Warning will be printed if a user defined a non-deletable Setting in their delete.yaml (unlikely)
> Include Automations in purge command

- .ci/releasePipeline.groovy
ci: Sign image tag rather than repo digest
Querying the repo digest(s) and using the first entry in the images list of repo digests, we accidentally always sign and deliver on the first registry/digest the release image was built for. For a full release that is the Docker Hub release, which will receive a signature twice, while the internally delivered image will not receive a signature.
As there is no recommendation to sign based on the full sha rather than a tag that could be found in cosign documentation, this issue is resolved by simply signing the image based on it's tag.
As we already use the tag to query for the full digest sha-sum, there is also no benefit to authenticity by using the checksum - it's already that of the tag (which we can strongly assume was just built and pushed …
> ci: Sign image tag rather than repo digest

- pkg/client/dtclient/client.go
- pkg/client/metadata/metadata.go
Give the user a hint when (s)he is trying to target a platform enabled environment but gave classic environment URL to monaco
> Fix: give user hint about correct platform URL

- cmd/monaco/download/downloaders_test.go
- cmd/monaco/dynatrace/dynatrace_test.go
- cmd/monaco/integrationtest/v2/pagination_e2e_test.go
- pkg/client/dtclient/client.go
- pkg/client/dtclient/config_client.go
- pkg/client/dtclient/config_client_test.go
- pkg/rest/list.go
- fix a small mistake in the pagination E2E test assertion (804aff68f991fc43f7492ec79128ee61c05ce74b)
- fix when a warning is logged about mismatch between received paginated entries and expected total count
Review per commit. The actual fix is in the second commit, the rest are small improvements found along the way,
YES - no incorrect warning is logged if Settings filtering results in less objects being returned from the client's List operation.
> Fix nightly E2E tests & several small improvements to pagination handling

- pkg/config/v2/config_writer.go
- pkg/config/v2/config_writer_test.go
- pkg/download/id_extraction/id_extraction.go
- pkg/download/id_extraction/id_extraction_test.go
As it is preferable for the main internal user of ID extraction on download to have extracted IDs grouped together, one complex value parameter is now created instead of individual parameters. 
Additionally, the resilience of the config writer is improved - as the value for the new parameter is a `map[string]string` rather than `map[string]interface{}` it was not correctly treated as a "full" map/slice Value parameter by the writer, but incorrectly produced as a shorthand.
The writer logic is now flipped, so writing the full parameter is the default.
See: what it does
> Feat: Create extracted IDs parameter as single complex Value

- cmd/monaco/integrationtest/v2/test-resources/integration-all-configs/project/request-attributes/config.yaml
- cmd/monaco/integrationtest/v2/test-resources/integration-all-configs/project/request-attributes/request-attributes.json
With this all supported config API types are covered, with the execption of synthetic locations, which would need a host to exist that's used as location.
NO
> test(e2e): Add request-attributes sample to all-configs test

- internal/log/field/field.go
- pkg/config/v2/config.go
- pkg/config/v2/config_loader.go
- pkg/config/v2/config_loader_test.go
- pkg/config/v2/config_writer.go
- pkg/config/v2/errors/errors.go
- pkg/config/v2/errors/loader_errors.go
- pkg/config/v2/errors/writer_errors.go
- pkg/config/v2/parameter/parameters.go
- pkg/manifest/manifest_loader.go
- pkg/manifest/manifest_writer.go
- pkg/rest/errors.go
- pkg/rest/retry.go
Introduce structured logging metadata to general load/write errors for configs and manifest
* This PR also removes the previously introduced explicit `Type` field from custom errors, and instead used Go formatting and a dedicated logging struct to log the actual type as well as error contents.  (8848ab673c35f8b27a24d713e130fadd1190e0c6)
* While this is pretty much independent from the other open PRs on structured logging, please still review them first
Additional structured logs.
> Introduce structured logging metadata to general load/write errors for configs and manifest

- cmd/monaco/delete/delete.go
- cmd/monaco/deploy/deploy.go
- cmd/monaco/download/download_configs.go
- cmd/monaco/download/download_configs_test.go
- cmd/monaco/download/download_entities.go
- cmd/monaco/download/downloaders.go
- cmd/monaco/dynatrace/dynatrace.go
- cmd/monaco/integrationtest/integration_test_utils.go
- cmd/monaco/integrationtest/v2/diff_project_diff_ext_id_test.go
- cmd/monaco/purge/purge.go
- pkg/client/clientset.go
Up to now no error message was given if a user wanted to download automation resources, but no credentials were configured.
Now we get logs like this: 
```
> MONACO_FEAT_AUTOMATION_RESOURCES=1 monaco download manifest.yaml -e XXX --only-automation -v
2023-06-21T14:51:58+02:00       debug   request log not activated
2023-06-21T14:51:58+02:00       debug   response log not activated
2023-06-21T14:51:58+02:00       debug   Loading manifest "manifest.yaml". Restrictions: groups=[], environments=["XXX "]
2023-06-21T14:51:58+02:00       debug   Concurrent Request Limit: 5, 'MONACO_CONCURRENT_REQUESTS' environment variable is NOT set, using default value
2023-06-21T14:51:58+02:00       info    Downloading from environment 'XXX ' into project 'project_XXX '
Error: can't download automation …
```
> Show an error if download of automation-resources is forced, but no OAuth credentials are configured

- cmd/monaco/integrationtest/cleanup.go
- cmd/monaco/integrationtest/v2/automation_integration_test.go
- pkg/client/automation/client.go
- pkg/client/automation/client_test.go
- pkg/client/automation/internal/pagination/url.go
- pkg/client/automation/internal/pagination/url_test.go
- pkg/client/dtclient/client.go
- pkg/delete/delete_test.go
- pkg/rest/request.go
- pkg/rest/request_test.go
Set `adminAccess` query parameter when accessing the "automation/workflows" API to ensure that all workflows can be fetched and modified by Monaco.
User is able to download **all** workflows, event from workflows created by other user if (s)he has the right permissions.
> feat: Workflows API access with admin mode

- internal/json/json.go
- internal/json/json_test.go
- internal/log/field/field.go
- internal/log/log_test.go
- internal/sort/topologysort.go
- pkg/config/config.go
- pkg/config/errors/errors.go
- pkg/config/errors/loader_errors.go
- pkg/config/errors/writer_errors.go
- pkg/config/parameter/parameters.go
- pkg/converter/converter.go
- pkg/delete/delete_loader.go
- pkg/deploy/deploy.go
- pkg/deploy/error.go
- pkg/manifest/manifest_loader.go
- pkg/manifest/manifest_loader_test.go
- pkg/manifest/manifest_writer.go
- pkg/project/v2/project_loader.go
- pkg/project/v2/topologysort/topologysort.go
- pkg/project/v2/topologysort/topologysort_test.go
- pkg/rest/errors.go
- pkg/rest/retry.go
refactor: Ensure custom errors use uniform names and have struct tags for JSON logging
To ensure that structured JSON logs are easy to parse, fields of custom errors that have the same meaning now have the same name.
For a nicer looking generated JSON all fields are extended with struct tags so they start lowercase, rather than than the upper-case of exported struct fields.
NO - but this should be included in the first release that contains structured logging fields, else there will be a change.
> refactor: Ensure custom errors use uniform names and have struct tags for JSON logging

- pkg/client/dtclient/client.go
- pkg/client/dtclient/config_client.go
- pkg/client/dtclient/config_client_test.go
- pkg/client/dtclient/extension_upload.go
- pkg/client/dtclient/extension_upload_test.go
- pkg/client/dtclient/test_utils.go
The code related to classic config handling is calling a lot of function passing internals of the struct.
Prominent example:
```go
upsertDynatraceEntityByNonUniqueNameAndId(ctx, d.clientClassic, d.environmentURLClassic, entityId, name, api, payload, d.retrySettings)
```
This PR just converts all these functions to methods, which reduces the number of arguments passed around.
Looking forward this enables also to introduce caching a bit easier.
Further, the split into a separate settings and config client will be easier.
--
> chore: reduce unnecessary argument passing

- .ci/nightly.groovy
- .ci/releasePipeline.groovy
- .github/workflows/end-to-end-test.yml
- Makefile
- cmd/monaco/integrationtest/v2/automation_integration_test.go
- cmd/monaco/integrationtest/v2/config_restore_e2e_test.go
- cmd/monaco/integrationtest/v2/integration_test_utils.go
- cmd/monaco/integrationtest/v2/non_unique_names_e2e_test.go
- cmd/monaco/integrationtest/v2/test-resources/delete-test-configs/deploy-manifest.yaml
- cmd/monaco/integrationtest/v2/test-resources/integration-all-configs/manifest.yaml
- cmd/monaco/integrationtest/v2/test-resources/integration-automation/manifest.yaml
- cmd/monaco/integrationtest/v2/test-resources/integration-automation/project/workflow/config.yaml
- cmd/monaco/integrationtest/v2/test-resources/integration-different-projects-different-extid/manifest.yaml
- cmd/monaco/integrationtest/v2/test-resources/integration-download-configs-with-automation/platform_manifest.yaml
- cmd/monaco/integrationtest/v2/test-resources/integration-download-configs-with-automation/project/workflow/config.yaml
- cmd/monaco/integrationtest/v2/test-resources/integration-download-configs/platform_manifest.yaml
- cmd/monaco/integrationtest/v2/test-resources/integration-multi-project/manifest.yaml
- cmd/monaco/integrationtest/v2/test-resources/integration-scope-parameters/manifest.yaml
- cmd/monaco/integrationtest/v2/test-resources/integration-settings-old-new-external-id/manifest.yaml
- cmd/monaco/integrationtest/v2/test-resources/integration-settings/manifest.yaml
- cmd/monaco/integrationtest/v2/test-resources/pagination-test-configs/manifest.yaml
- cmd/monaco/integrationtest/v2/test-resources/references/invalid-configs-manifest.yaml
- cmd/monaco/integrationtest/v2/test-resources/references/manifest.yaml
- cmd/monaco/integrationtest/v2/test-resources/special-character-in-config/manifest.yaml
This PR introduces automated, nightly E2E tests for Dynatrace hardening environments.
To do that, some changes have been made:
1. Added a pipeline that is executed every day
2. Adapted the configs and manifests
* Workflow-actor is differs for some tenants/accounts
* tokenEndpoint is differs per stage
3. Adapted the tests: Some tests can't be executed on non-prod environments. Those are skipped.
Additionally, this PR introduces a check for cosign to verify the container immediately after signing it, ensuring the container is signed correctly.
> ci: Add Staging E2E test

- pkg/client/dtclient/client.go
- pkg/manifest/manifest_loader.go
- pkg/project/v2/project_loader.go
When loading large projects without verbose logging, we log nothing until after the project was loaded, which can take minutes. Change some logs to INFO and extend them.
Differentiate between returning cached settings and querying them in debug logging
> chore: Improve log messages

- internal/memstatlog/memstatlog.go
As it is occasionally useful to collect information about memory usage at specific points in the code, by reading runtime.MemStats, a reusable method is added so that this doesn't have to be re-created every time.
This method is unused, but as it's the third time I've created a version of it, I figured I might as well check it in. 
NONE
> feat: Add reusable debugging code for logging memory usage

- cmd/monaco/integrationtest/integration_test_utils.go
- cmd/monaco/integrationtest/v2/special_character_in_config_integration_test.go
- internal/cache/cache.go
- internal/cache/cache_test.go
- pkg/client/clientset.go
- pkg/client/dtclient/client.go
- pkg/client/dtclient/client_settings_test.go
- pkg/client/dtclient/client_test.go
- pkg/client/dtclient/config_client.go
- pkg/client/dtclient/config_client_test.go
- pkg/client/dtclient/settings_client_test.go
At present, when Monaco deploys, it checks all configurations of a specific type to determine whether an object with a given name exists and needs updating. To enhance efficiency, a cache is introduced, similar to what has been done for settings objects and schema constraints. This cache helps optimize the process.
The code underwent slight modifications to enable the disabling of the caching mechanism. This adjustment is essential for stable end-to-end tests, as the cache might sometimes provide inaccurate results, especially when the API hasn't yet returned the most up-to-date values shortly after their creation.
Performance improvements when deploying classic api configs. :rocket:
> feat: cache classic configs

- cmd/monaco/dependencygraph/command.go
- cmd/monaco/dependencygraph/dependencygraph.go
- cmd/monaco/dependencygraph/dependencygraph_test.go
- cmd/monaco/dependencygraph/test-resources/manifest.yaml
- cmd/monaco/dependencygraph/test-resources/project/alerting-profile/config.yaml
- cmd/monaco/dependencygraph/test-resources/project/alerting-profile/profile.json
- cmd/monaco/dependencygraph/test-resources/project/dashboard/config.yaml
- cmd/monaco/dependencygraph/test-resources/project/dashboard/overview-dashboard.json
- cmd/monaco/dependencygraph/test-resources/project/maintenance-window/config.yaml
- cmd/monaco/dependencygraph/test-resources/project/maintenance-window/maintenance-window.json
- cmd/monaco/dependencygraph/test-resources/project/maintenance-window/settings_config.yaml
- cmd/monaco/dependencygraph/test-resources/project/maintenance-window/settings_template.json
- cmd/monaco/dependencygraph/test-resources/project/management-zone/config.yaml
- cmd/monaco/dependencygraph/test-resources/project/management-zone/settings_config.yaml
- cmd/monaco/dependencygraph/test-resources/project/management-zone/settings_template.json
- cmd/monaco/dependencygraph/test-resources/project/management-zone/zone.json
- cmd/monaco/dependencygraph/test-resources/project/notification/config.yaml
- cmd/monaco/dependencygraph/test-resources/project/notification/subfolder/email.json
- cmd/monaco/dependencygraph/test-resources/project/notification/subfolder/slack.json
- cmd/monaco/dependencygraph/test-resources/project/reports/config.yaml
- cmd/monaco/dependencygraph/test-resources/project/reports/report.json
- cmd/monaco/runner/runner.go
- internal/featureflags/featureflags.go
- internal/mutlierror/multierror.go
Fully finish the previously experimental command by:
- adding tests
- not overwriting files if they exist alrady
- removing the featureflag
Dependency graphs can be exported as DOT files with a new CLI command
> feat: Allow exporting dependency graph as DOT file

- .github/workflows/end-to-end-test.yml
- internal/featureflags/featureflags.go
- internal/log/log.go
- pkg/client/dtclient/config_client.go
- pkg/deploy/deploy.go
- pkg/rest/retry.go
Run deployments of independent subgraphs concurrently in separate go routines.
In general chance of much faster deployments for the user: :rocket:
Feature needs to be enabled via the the feature flag: `MONACO_FEAT_GRAPH_DEPLOY_PARALLEL`
> Feat: Deploy independent graph components in parallel

- internal/loggers/zap/zap.go
- pkg/client/dtclient/dummy_client.go
- pkg/deploy/deploy.go
Previously goroutines would write and read the same context, resulting in race conditions (and unwanted behaviour).
Additionally testing found additional data races in the dry-run's dummyclient & our logger setup
> fix(deploy): Ensure thread safety

- pkg/client/dtclient/dummy_client.go
- pkg/deploy/deploy_test/deploy_graph_test.go
refactor: Ensure dry-run dummy client is fully threadsafe
As we don't just modify a map, but slices of DataEntries within a map, the sync.Map used before does not actually safeguard all our read/write operations in the DummyClient.
Thus it's replaced with a read/write lock manually safeguarding operations on the DummyClient's entries.****
Note this race seems to be less likely than the ones fixed previously, so main is currently green and this was not noticed before
none
> refactor: Ensure dry-run dummy client is fully threadsafe

- internal/log/field/field.go
- internal/log/log.go
- internal/loggers/zap/console.go
- internal/loggers/zap/console_test.go
- internal/loggers/zap/objencode.go
- internal/loggers/zap/zap.go
- internal/loggers/zap/zap_test.go
- pkg/client/dtclient/config_client.go
- pkg/client/dtclient/settings_client.go
- pkg/deploy/deploy.go
To enhance the usefulness of the (human-readable) logs, this pull request introduces additional context to the log lines. Specifically, it enriches the logs with details about the coordinate and the graph ID (gid). The graph ID proves particularly valuable in linking logs that occur out of sequence when configurations are deployed concurrently. To conserve characters, the coordinate is logged using a shorthand syntax.
Zap allows implementing the `Encoder` interface which makes it possible to choose the exact format of each log line on your own. This was done to change the order of when context fields are printed. Per default, they are just appended as JSON to each log line. However, this made the logs look very clumsy and unclear and confusing to look at.
> feat: log coordinate and gid in human readable logs

- pkg/deploy/deploy.go
Since, all of the go-routines are already started, and cannot be canceled caching the errors and return early does not make much sense.
> fix: remove early return when errors occur during parallel deploy

- cmd/monaco/integrationtest/v2/test-resources/integration-all-configs/project/slo/as_settings_config.yaml
All configs test resources are a useful sample to check things against a test environment as they define all types we support and use most monaco features.
To be able to deploy them without the name-rewriting that happens on E2E tests, a 'UNIQUE_TEST_SUFFIX' env var needs to be set to empty string (used in some references so setting an actual value fails if no re-write happened).
Setting this to an empty string would produce invalid SLO configurations at they end in an underscore, which the API does not allow.
As it does not matter for the test itself, the underscore separator is simply removed, ensuring the local usage of the project works.
NONE
> chore: Ensure all-configs SLOs are still valid if test-suffix is empty

- cmd/monaco/integrationtest/assert.go
- cmd/monaco/integrationtest/v2/test-resources/integration-all-configs/project/management-zone/settings_config.yaml
- cmd/monaco/integrationtest/v2/test-resources/integration-all-configs/project/management-zone/settings_template.json
- cmd/monaco/integrationtest/v2/test-resources/integration-settings/project/config.yaml
- pkg/config/config_loader.go
- pkg/config/config_loader_test.go
- pkg/config/config_writer.go
- pkg/download/automation/automation.go
- pkg/download/automation/automation_test.go
- pkg/download/settings/settings.go
- pkg/download/settings/settings_test.go
Remove the required name from non-classic-config-API types.
Only config APIs will fail to load if they have no name defined.
Additionally downloaded configs are cleaned up to only include a name if it actually exists (e.g. an extracted Worklfow title), but no longer set 'dummy names' that just contain a configID and are not used.
This means users do not have to set a name that might not be used anywhere.
Existing configs are not impacted. 
Downloaded configs will no longer contain unused 'name' parameters added just to fulfill the loaded constraints.
> Feat: Don't enforce name parameter for anything but classic APIs

- cmd/monaco/deploy/logging.go
- pkg/graph/graph.go
When building a graph, we already log dependencies in the same format we did before. Additionally logging that we add a graph edge is not helpful to anyone and just pollutes the logs.
less logging
> fix: Remove unecessary/duplicate log of dependencies

- cmd/monaco/integrationtest/assert.go
- cmd/monaco/integrationtest/v2/skip_e2e_test.go
- cmd/monaco/integrationtest/v2/test-resources/skip-test/manifest.yaml
- cmd/monaco/integrationtest/v2/test-resources/skip-test/project/auto-tag/auto-tag-setting.json
- cmd/monaco/integrationtest/v2/test-resources/skip-test/project/auto-tag/config.yaml
[test(e2e): Add test for different cases of skipping configurations](https://github.com/Dynatrace/dynatrace-configuration-as-code/commit/b0604a46a5601c74a7bca2a262590abd1534bb2d)
This also makes the individual e2e assert methods for individual configs accessible to E2E tests, as asserting the whole project did not fit the need to assert to assert specific things are created/skipped.
none
> Add E2E tests for skip parameter

- pkg/rest/client.go
Previously we failed to log actual http client errors, and only logged HTTP response codes - which are missing/zero-initialized if a http client error occurred.
> fix(rest): Correctly log GET request retry reason

- cmd/monaco/deploy/deploy.go
- cmd/monaco/integrationtest/assert.go
- cmd/monaco/integrationtest/v2/bucket_integration_test.go
- cmd/monaco/integrationtest/v2/test-resources/integration-bucket/manifest.yaml
- cmd/monaco/integrationtest/v2/test-resources/integration-bucket/project/bucket.json
- cmd/monaco/integrationtest/v2/test-resources/integration-bucket/project/config.yaml
- pkg/client/bucket/bucket.go
- pkg/client/bucket/bucket_test.go
- pkg/client/bucket/dummy_bucket.go
- pkg/client/clientset.go
- pkg/deploy/bucket.go
- pkg/deploy/deploy.go
- feat: new client for bucket
- feat: create new bucket (without update)
- feat: upsert command for bucket (with update and create, without retry)
- feat: add concurrency to bucket upsert
- feat: extend platform exclusive configuration check with BucketType
- feat: add dummy client for Bucket
- test: add test cases for bucket.upsert
- doc: add documentation
Add cover for Grail Bucket. For now, only `deploy` is covered.
> `deploy` functionality for Grail Bucket 

- cmd/monaco/integrationtest/v2/bucket_integration_test.go
- cmd/monaco/integrationtest/v2/test-resources/integration-bucket/complex-bucket/bucket.json
- cmd/monaco/integrationtest/v2/test-resources/integration-bucket/complex-bucket/config.yaml
- cmd/monaco/integrationtest/v2/test-resources/integration-bucket/complex-bucket/log-bucket-rule.json
- cmd/monaco/integrationtest/v2/test-resources/integration-bucket/manifest.yaml
- cmd/monaco/integrationtest/v2/test-resources/integration-bucket/project/bucket.json
Adds another bucket integration test where 
1) name is configured
2) parameter is configured
3) bucket is used as a reference
4) settings object points to a created bucket
> test: Add additional bucket integration test

- pkg/deploy/automation.go
- pkg/deploy/automation_test.go
- pkg/deploy/bucket.go
- pkg/deploy/classic.go
- pkg/deploy/deploy.go
- pkg/deploy/deploy_test.go
- pkg/deploy/settings.go
This PR removes the unnecessary pointers of the `ResolvedEntity` return value
> refactor: Remove unnecessary pointer

- pkg/rest/client.go
- pkg/rest/client_test.go
For some reason the stdlib http client reports an unexpected closed connection as an io.EOF with no further information.
This resulted in connection problems (like an internal firewall/proxy/connection config blocking connections to a Dynatrace SaaS URL) to just be reported as EOF to users.
This fix makes some assumptions about the internals of the http client and may break in the future, but if the client is changed to no longer return io.EOF errors it will hopefully return a more helpful error instead.
see also: https://github.com/golang/go/issues/53472
I'll open an analogous PR for the -core rest client once this is reviewed.
Connection reset errors are presented in a more helpful way than just printing "EOF"
> fix(rest): Wrap net/url connection reset EOF errors in user-readable error

- pkg/client/auth/http.go
The previous log about using an old token format was misleading, as we don't actually check for an old format, but just if the new format is matched.
As the new format exists since October 2020, it is much more likely that a random string was provided as a token, than an actual old API token.
To reflect this, the log warning is changed to point the user towards checking their configuration first, but still mention to possibly update their tokens.
Old warning: 
```
2023-08-18T12:21:39+02:00 warn You used an old token format. Please consider switching to the new 1.205+ token format.
More information: https://www.dynatrace.com/support/help/dynatrace-api/basics/dynatrace-api-authentication
```
New warning: 
```
2023-08-25T10:37:33+02:00       warn    The supplied token does not match the …
```
> chore(http): Improve API token format warning

- cmd/monaco/integrationtest/assert.go
- pkg/config/parameter/parameters.go
- pkg/config/parameter/reference/reference.go
- pkg/config/parameter/reference/reference_test.go
- pkg/deploy/automation.go
- pkg/deploy/automation_test.go
- pkg/deploy/bucket.go
- pkg/deploy/classic.go
- pkg/deploy/classic_test.go
- pkg/deploy/deploy.go
- pkg/deploy/deploy_test.go
- pkg/deploy/entitymap.go
- pkg/deploy/entitymap_test.go
- pkg/deploy/resolve.go
- pkg/deploy/resolve_test.go
- pkg/deploy/settings.go
This PR moves the ResolvedEntity to the deploy package, where it belongs. An interface to lookup properties is created instead.
Additionally, fields are unexported.
Furthermore, since the name lookup does not work as it used to do, it's also removed from the entityMap
> refactoring: Move 'ResolvedEntity' from parameter package to deploy package

- cmd/monaco/integrationtest/v2/supportarchive_e2e_test.go
- cmd/monaco/integrationtest/v2/test-resources/support-archive/invalid-manifest.yaml
- cmd/monaco/integrationtest/v2/test-resources/support-archive/manifest.yaml
- cmd/monaco/integrationtest/v2/test-resources/support-archive/project/alerting-profile/config.yaml
- cmd/monaco/integrationtest/v2/test-resources/support-archive/project/alerting-profile/profile.json
- internal/trafficlogs/logger.go
- internal/zip/zip_test.go
Assert that support-archives are actually being created as we expect by adding a small E2E test.
none
> test: Assert that support-archives are created as expected

- cmd/monaco/integrationtest/assert.go
- pkg/deploy/internal/bucket/bucket.go
- pkg/deploy/internal/bucket/bucket_test.go
To ensure uniqueness and not overlapping with other configs, monaco created buckets get a generated identifier based on their coordinate, similar to other types like settings or automations.
Other than those types theses IDs are human readable, used in other configs or manually and they only ever exist on the bucket API for bucket types.
As such every single bucket config will contain the unecessary string _bucket_ in it's 'bucketName'. As the type is not needed to ensure uniqueness and looks weird to users, it is simply omited.
As this feature is not publicly released yet, not backwards compatibility to the previous 'full coordinate' version is required.
> refactor(bucket): Omit type from generated bucket names

- internal/memstatlog/memstatlog.go
When collecting more memory statistics it can be helpful to use structured logging to automatically parse the outcomes with tools like jq.
> chore: Enable structured logging for internal memstat util

- pkg/deploy/deploy.go
- pkg/deploy/deploy_test.go
- pkg/deploy/errors/error.go
Unlike the old per-config validation for config API type's name uniqueness, the new pre-flight validation always returned it's errors directly, even for a dry-run (in which we want to collect all errors we can find) or when the continue-on-error flag was set.
Now the options are honored and the validation errors are collected into the full EnvironmentDeploymentErrors.
To enable this useage EnvioronmentDeploymentErrors.Append now accepts a variadic error slice, so it can be used with single errors as well as the slice of errors from deployment.
Only if they where using the feature flagged graph based deployment. 
This should be merged before 2.8.0 is released with that feature on by default.
> fix(deploy): Honor continue-on-error and dry-run in new name validation

- cmd/monaco/generate/deletefile/deletefile.go
- cmd/monaco/generate/deletefile/deletefile_test.go
- cmd/monaco/generate/deletefile/test-resources/invalid-project/dashboard/config.yaml
- cmd/monaco/generate/deletefile/test-resources/invalid-project/dashboard/overview-dashboard.json
- cmd/monaco/generate/deletefile/test-resources/manifest_invalid_project.yaml
- pkg/config/parameter/reference/reference.go
Previously it was possible to generate invalid delete files if config had an empty string set as name but was a Config API type. As persisting delete entries uses the same object for all types it will omit empty names and IDs, and thus produce an invalid entry consisting only of the 'type' if a config had an empty 'name' defined.
> fix(generate): Omit configs with empty names when generating deletefiles

- cmd/monaco/integrationtest/assert.go
The previous implementation didn't actually do what we want, it didn't retry on 404 statuscodes, but only on unlikely network errors, and it would have retrid immediately instead of after a delay.
As such our E2E tests were flaky as it might still happen occaisonally that an active bucket is not immediately returned.
> test(e2e): Fix bucket assert retry logic

- cmd/monaco/delete/command.go
- cmd/monaco/delete/delete.go
- cmd/monaco/generate/deletefile/deletefile_test.go
- cmd/monaco/purge/purge.go
- pkg/delete/delete.go
- pkg/delete/delete_loader.go
- pkg/delete/delete_loader_test.go
- pkg/delete/delete_test.go
Enable `monaco delete ...` to also recognize and delete bucket API type of configurations.
PR also contains a bit of code refactoring most notably cleaning up the delete function from
```go
func Delete(afero.Fs, string, string, []string, []string) error
``` 
to just
```go
func Delete(manifest.Environments, delete.DeleteEntries) error 
```
Loading the manifest and delete files happens outside of this function.
Obviously
> feat: delete buckets

- cmd/monaco/integrationtest/assert.go
- cmd/monaco/integrationtest/cleanup.go
- internal/idutils/bucketname.go
- pkg/delete/delete.go
- pkg/deploy/internal/bucket/bucket.go
Remove Grail Bucket configs after E2E tests.
No
> test: Include Grail Buckets in E2E test cleanup

- cmd/monaco/integrationtest/v2/settings_integration_test.go
- cmd/monaco/integrationtest/v2/test-resources/settings-unique-properties/manifest.yaml
- cmd/monaco/integrationtest/v2/test-resources/settings-unique-properties/project3/builtinhost.process-groups.monitoring.state/config.yaml
- cmd/monaco/integrationtest/v2/test-resources/settings-unique-properties/project3/builtinhost.process-groups.monitoring.state/template.json
- cmd/monaco/integrationtest/v2/test-resources/settings-unique-properties/project4/builtinhost.process-groups.monitoring.state/config.yaml
- cmd/monaco/integrationtest/v2/test-resources/settings-unique-properties/project4/builtinhost.process-groups.monitoring.state/template.json
- internal/memory/limit.go
- pkg/client/dtclient/settings_client.go
- pkg/client/dtclient/settings_client_test.go
This addressed two issues in the settings_client's code finding existing objects to update based on unique properties.
The issues where both found when investigating memory consumption, which discovered that for some schemas we currently find hundreds of matches in a large test configurations. 
In this perfectly valid test project, many Settings define the same unique properties but apply to different scopes - a fact that the code didn't consider so far.
1. A refactoring aims to reduce heap memory consumption by removing the use of pointers and not including matching object IDs in error text if there are more than 5 matches. This ensures that matches don't escape to the heap, and that the currently stored errors don't get too big.
2. The logic is modified to only consider Settings that …
> fix: Settings matching based on unique properties

- cmd/monaco/integrationtest/v2/bucket_integration_test.go
- cmd/monaco/integrationtest/v2/test-resources/integration-bucket/broken-bucket/bucket.json
- cmd/monaco/integrationtest/v2/test-resources/integration-bucket/broken-bucket/invalid-config.yaml
- cmd/monaco/integrationtest/v2/test-resources/integration-bucket/invalid-manifest.yaml
- pkg/deploy/internal/bucket/bucket.go
Validation of bucket configs previously failed, because the DummyClient implemented for validation didn't set a status code.
Thus it's zero-initialized status code repsonse has treated as an error/non-success, and incorrectly flagged valid bucket configurations as invalid.
> fix(buckets): Ensure validating buckets works

- internal/memory/memstatlog.go
- tools/parse-memstats-from-json-log.sh
Extend the on-demand utility function to write memory statistics.
This version writes extended information (like human readable, MiB and Byte values) and creates a CSV file for easier processing.
Additionally a utility script is committed to the tools/ folder, which allows post-processing logs written into a structured JSON log.
LogMemStats still needs to be placed in desired lines of code manually, this just commits the latest version used to investigate high memory consumption/development of heap memory during sample deployments.
nope
> feat: extended memstat log util

- cmd/monaco/deploy/deploy.go
- cmd/monaco/deploy/internal/clientset/clientset.go
- cmd/monaco/deploy/internal/logging/logging.go
- cmd/monaco/deploy/sequential/deploy.go
- cmd/monaco/deploy/sequential/reporterror.go
- cmd/monaco/integrationtest/v2/duplicate_coordinates_produce_user_errors_e2e_test.go
- cmd/monaco/integrationtest/v2/invalid_manifests_produce_user_errors_e2e_test.go
- cmd/monaco/integrationtest/v2/invalid_payloads_produce_user_errors_e2e_test.go
- cmd/monaco/integrationtest/v2/test-resources/configs-with-invalid-payload/manifest.yaml
- cmd/monaco/integrationtest/v2/test-resources/configs-with-invalid-payload/project/auto-tag/auto-tag-config-api.json
- cmd/monaco/integrationtest/v2/test-resources/configs-with-invalid-payload/project/auto-tag/auto-tag-setting.json
- cmd/monaco/integrationtest/v2/test-resources/configs-with-invalid-payload/project/auto-tag/config.yaml
- pkg/deploy/deploy.go
- pkg/deploy/deploy_test.go
- pkg/deploy/errors/error.go
- pkg/deploy/sequential/deploy_sequential.go
Currently when using --continue-with-error, or by default for parallel deployment errors, monaco will collect all errors that occurred and will log them in a sorted report at the end of deployment.
In cases where many errors fail, that means we carry a memory overhead for presenting errors that have already been logged just to present the user with a sorted representation of issues.
These errors may carry additional information like full JSON templates that failed to render or HTTP request and response bodies.
This PR removes the collection of errors and ensures that no information is lost, by adding a few explicit logs.
It also attempts to present the information that is logged in a slightly clearer way.
- review per commit is recommended
- relates to …
> feat/(fix): Do not collect large amounts of errors for final error report

- cmd/monaco/integrationtest/v2/errors_written_to_file_e2e_test.go
Correct an e2e test asserting that errors are written as expected to actually match modified wording in our errors
nope
> fix(e2e): Correct test assertions after error messages changed

- pkg/deploy/deploy.go
When printing the logs what configs are skipped, the child is not printed using structured logging. This is now fixed.
> fix: Add child-config as structured logging field

- pkg/config/parameter/reference/reference.go
Previously the error wrongly mentioned that 'project' is missing, which is especially confusing as 'project' is expressly optional.
Additionally the error message is extended a bit to clarify why 'property' is needed, rather than just state that it's missing.
> fix(reference): Correctly report if 'property' is missing

- cmd/monaco/integrationtest/v2/settings_integration_test.go
- pkg/client/dtclient/client.go
- pkg/client/dtclient/dummy_client.go
- pkg/client/dtclient/settings_client.go
- pkg/client/dtclient/settings_client_test.go
- pkg/deploy/deploy_test.go
- pkg/deploy/internal/setting/setting.go
- pkg/deploy/sequential/deploy_sequential_test.go
- pkg/rest/retry.go
We observed, that even if we wait for a new bucket definition to be in  "active" state, it turns out that settings objects referencing that bucket could still fail to be uploaded because the bucket could not be found.
In this PR a special handling for settings objects referencing buckets is added. If it is triggered, the retry settings for that upsert operation ar drastically increased.
> fix: override retry settings in case a bucket is referenced in a settings obj to be deployed

- internal/log/field/field.go
- pkg/client/dtclient/settings_client.go
- pkg/deploy/deploy.go
- pkg/deploy/sequential/deploy_sequential.go
This PR adds a field `deploymentStatus` to structured log lines related to configuration deployment, so it is e.g. easily possible to collect log lines that indicate that the deployment of certain configurations failed or were skipped etc.
It introduces the field `deploymentStatus` which is set whenever a log line related to a configuration coordinate is written during the execution of a deployment. It's set to one of the following values:
* deploying - to indicate that the log message was produced to tell that a deployment of a config is happening 
* deployed - to indicate that the log message was produced to tell that a deployment of a config was successful
* failed - to indicate that the log message was produced to tell that the deployment of a config failed
* skipped - to indicate …
> feat: status log field

- .ci/nightly.groovy
- .ci/releasePipeline.groovy
The beta.* labels are not allowed on jenkins anymore resulting in a failing build.
https://kubernetes.io/docs/reference/labels-annotations-taints/#beta-kubernetes-io-arch-deprecated
> fix: replace deprecated node selector labels

- pkg/deploy/internal/automation/automation.go
In order to decode a proper automation resource, at least the id field needs to be set, otherwise, an error occurs.
The dummy client failed to return a response with an id, thus a monaco `--dry-run` was failing.
> fix: dummy client not returning id in response

- cmd/monaco/download/download_configs.go
- cmd/monaco/integrationtest/v2/all_configs_integration_test.go
- cmd/monaco/integrationtest/v2/bucket_integration_test.go
- cmd/monaco/integrationtest/v2/config_restore_e2e_test.go
- cmd/monaco/integrationtest/v2/delete_integration_test.go
- internal/featureflags/temporary.go
- pkg/persistence/config/internal/persistence/type_definition.go
- pkg/persistence/config/internal/persistence/type_definition_test.go
- pkg/persistence/config/loader/config_loader_test.go
Removes FF for bucket definitions, thus enabling support for buckets per default.
User is able to use monaco to configure grail buckets per default without setting using a feature flag
> feat: enable managing bucket definitions

- pkg/client/dtclient/config_client.go
Sometimes, the API returns 500 Internal Server Error e.g. when an application referenced by an application detection rule is not fully "ready" yet.
This PR adds another special treatment to handle that specific case.
> fix: unable to deploy app-detection-rules

- cmd/monaco/delete/delete.go
We're leaking the API-Token and OAUTH credentials if the deletion of resources fail during the execution of `monaco delete`. 
This change fixes this by only logging the Name of the environment, not all information.
> fix: Fix log message that leaks the secrets

- internal/featureflags/temporary.go
Sets the enablement of the Bucket feature flag to true per default.
User is able to use buckets as configurations type
> feat: enable bucket management feature flag

- cmd/monaco/generate/deletefile/command.go
- cmd/monaco/generate/deletefile/deletefile.go
- cmd/monaco/generate/deletefile/deletefile_test.go
- cmd/monaco/generate/deletefile/test-resources/project/notification/config.yaml
- cmd/monaco/integrationtest/cleanup.go
- cmd/monaco/integrationtest/v1/integration_test_utils.go
- cmd/monaco/integrationtest/v2/config_restore_e2e_test.go
- cmd/monaco/integrationtest/v2/integration_test_utils.go
- cmd/monaco/integrationtest/v2/non_unique_names_e2e_test.go
- cmd/monaco/integrationtest/v2/settings_integration_test.go
- pkg/delete/delete_test.go
- pkg/delete/internal/classic/delete.go
This replaces the dedicated logic to cleanup after an E2E test run, with reusing the `generate deletefile` and `delete` commands to clean up. 
Additionally this PR fixes an oversight in deletefile generation, that so far excluded Classic Config API configs with a name overwritten per environment, and improves a delete log message.
review per commit suggested
Yes, first commit in PR ensures that all configs are actually included in delete files, and `generate deletefile` gains a new --environment flag
> Improve Deletefile generation and use it and the delete command for E2E test cleanup

- cmd/monaco/generate/deletefile/deletefile.go
- cmd/monaco/generate/deletefile/deletefile_test.go
As the delete command validates if it was passed a yaml file, by checking the file ending, the current handling of avoiding overwriting existing files by appending a filestamp, means that such generated deletefiles can't be used directly. To address this, the timestamp is simply pre-pended, which also makes sorting by filename easier.
> fix(generate): Prepend timestamp if generated delete.yaml already exists

- cmd/monaco/integrationtest/v2/non_unique_names_e2e_test.go
- internal/featureflags/temporary.go
- pkg/client/dtclient/config_client.go
Updating single non-unique name configs can cause issues if a project defines more than one config with the same name - they will overwrite each other, and keep a single on the environment.
As there currently does not seem to be fix without detrimental side-effects, the feature flag is introduced to turn it off until a generally better solution is available.
Yes, they get a new feature flag to deactivate the update feature until we have a general purpose fix to this handling
> chore(client): Allow deactivating update of single non-unique name configs

- .github/workflows/build-test.yml
- .github/workflows/conventional_commit.yml
- .github/workflows/pr-static-code-analysis.yml
- .github/workflows/semgrep.yml
To allow us to use GitHub merge-queues [0] our actions are adapted to also trigger if they are part of a merge_group (sub-set of a merge-queue).
See also: [1], [2]
[0]https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/incorporating-changes-from-a-pull-request/merging-a-pull-request-with-a-merge-queue 
[1]https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/configuring-pull-request-merges/managing-a-merge-queue 
[2]https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#merge_group
> ci: Trigger checks that run on PR on merge-group events as well

- pkg/download/bucket/bucket.go
- pkg/download/bucket/bucket_test.go
- pkg/download/bucket/testdata/buckets.json
Up to now, if a bucket is in the "deleting" state, it is still downloaded. IMO this is wrong, thus this PR.
Log output looks like this after the change:
```
2023-10-09T15:58:36+02:00       debug   Skipping bucket: bucket "dt_query_executions" is immutable
2023-10-09T15:58:36+02:00       debug   Skipping bucket: bucket "default_logs" is immutable
2023-10-09T15:58:36+02:00       debug   Skipping bucket: bucket "default_bizevents" is immutable
2023-10-09T15:58:36+02:00       debug   Skipping bucket: bucket "default_events" is immutable
2023-10-09T15:58:36+02:00       debug   Skipping bucket: bucket "default_metrics" is immutable
2023-10-09T15:58:36+02:00       debug   Skipping bucket: bucket "default_spans" is immutable
2023-10-09T15:58:36+02:00       debug   Skipping bucket: bucket …
```
> feat: Skip "deleting" buckets

- Dockerfile
To prevent security issues as much as possible the docker image shall be shipped with as few dependencies as possible. This also means that tools like curl or jq should not be installed as they are not needed.
`curl` and `jq`are no longer available inside the docker container
> chore: remove curl and jq from docker image

- cmd/monaco/deploy/acc/deploy.go
- internal/files/files.go
- pkg/persistence/account/errors.go
- pkg/persistence/account/load.go
- pkg/persistence/account/load_test.go
- pkg/persistence/account/test-resources/duplicate-group.yaml
- pkg/persistence/account/test-resources/duplicate-policy.yaml
- pkg/persistence/account/test-resources/duplicate-user.yaml
- pkg/persistence/account/test-resources/multi/a/a.yaml
- pkg/persistence/account/test-resources/multi/a/b/b.yaml
- pkg/persistence/account/test-resources/multi/a/b/c/c.yaml
- pkg/persistence/account/test-resources/no-id-field-group-ref.yaml
- pkg/persistence/account/test-resources/no-ref-group.yaml
- pkg/persistence/account/test-resources/no-ref-policy-account.yaml
- pkg/persistence/account/test-resources/no-ref-policy-env.yaml
- pkg/persistence/account/test-resources/valid.yaml
- pkg/persistence/account/types.go
- pkg/persistence/account/validate.go
- pkg/persistence/account/validate_test.go
- pkg/project/v2/project_loader.go
This PR introduces the capability to read account management resources from files living inside of monaco project folders. The PR contains a function responsible for loading raw resources into a first in-memory representation as well as a function validating the references between users groups and policies.
> feat: load and parse account management resources

- cmd/monaco/convert/convert_test.go
- internal/featureflags/temporary.go
- pkg/manifest/account.go
- pkg/manifest/account_test.go
- pkg/manifest/manifest.go
- pkg/manifest/manifest_loader.go
- pkg/manifest/manifest_loader_test.go
- pkg/manifest/manifest_persitence.go
- pkg/manifest/manifest_test.go
- pkg/manifest/manifest_writer.go
- pkg/manifest/testdata/manifest_full.yaml
- pkg/version/version.go
This PR allows defining accounts in the `manifest.yaml`.
To do that, a user must increase the manifest-version to `1.1`.
Example manifest:
```yaml
manifestVersion: 1.1                                # manifestVersion needs to be set to at least 1.1
accounts:                                           # New top level property
- name: other-account                               # name
accountUUID: c3f50f90-a1e2-4e7b-aadb-f3dea28e2294 # account uuid
apiUrl:                                           # allow overriding endpoint (optional)
type: environment
value: ENV_API_URL
oAuth:                                            # credentials (only oAuth)
clientId:
name: ENV_CLIENT_ID
clientSecret:
name: ENV_CLIENT_SECRET
tokenEndpoint:                                  # (optional)
type: environment …
```
> feat(manifest): Allow defining accounts

- cmd/monaco/main.go
- internal/featureflags/permanent.go
- internal/version/releases.go
- internal/version/releases_test.go
This PR enables the monaco CLI to perform a version check at the end of each run before exiting the CLI to notify the user about newer versions of monaco being available.
This behavior is turned ON by default and can be disabled by setting `MONACO_SKIP_VERSION_CHECK` if needed.
User is notified when a new version of monaco is available each time the CLI executes.
> Feat: notify users about new Monaco version

- Makefile
Currently, when executing any makefile task, we usually install all tools that we do use somewhere in the makefile. This is most inconvenient and slow. 
This change does split up the setup step and moves the install calls to the targets where they're actually used.
No
> chore: Split up 'setup' task of Makefile

- .github/workflows/build-test.yml
- .github/workflows/end-to-end-test.yml
The actions/setup-go action reports an error for each step: 
`Restore cache failed: Dependencies file is not found in /home/runner/work/dynatrace-configuration-as-code/dynatrace-configuration-as-code. Supported file pattern: go.sum` 
This is due to the fact that we checkout the code after setting up go. Switching the order fixes this warning.
> chore: Setup go after checkout so `go.sum` is present.

- cmd/monaco/download/download_integration_test.go
- cmd/monaco/integrationtest/v2/non_unique_names_e2e_test.go
- pkg/client/dtclient/client.go
- pkg/client/dtclient/config_client.go
- pkg/client/dtclient/config_client_test.go
- pkg/client/dtclient/dummy_client.go
- pkg/config/config.go
- pkg/deploy/deploy_test.go
- pkg/deploy/internal/classic/classic.go
- pkg/deploy/internal/classic/validation.go
- pkg/project/v2/project_loader.go
This PR fixes the monaco failing to deploy multiple non-unique name configs having the same name.
It involves checking if there are multiple non-unique name api configs having the same name. If yes, we "mark" them using an artificial parameter in order to identify them later on when we need to handle them specially during deploy.
> fix: failed to deploy non-unique name configs with same name

- cmd/monaco/account/account.go
- cmd/monaco/account/deploy.go
- cmd/monaco/integrationtest/account/runner.go
- cmd/monaco/integrationtest/account/testdata/all-resources/manifest.yaml
- cmd/monaco/integrationtest/account/testdata/all-resources/single-file/resources.yaml
- cmd/monaco/integrationtest/account/testdata/all-resources/split-files/groups.yaml
- cmd/monaco/integrationtest/account/testdata/all-resources/split-files/policies.yaml
- cmd/monaco/integrationtest/account/testdata/all-resources/split-files/users.yaml
- cmd/monaco/integrationtest/account/users_test.go
- cmd/monaco/runner/runner.go
- pkg/account/deployer/deployer.go
- pkg/manifest/manifest.go
- pkg/persistence/account/types.go
This PR adds the command
```
monaco account deploy [--project <project>] [--account <account>]
```
This command will allow users to deploy account management resources.
Other commands allow the chaining of projects (`-p a,b`) and environments. In this PR, this is skipped for the simpler single-argument.
Additionally, this PR introduces a simple scaffolding for e2e tests and executes in a first version the command that loads the resources but is a NO-OP operation in the end.
This scaffolding can be extended further in the future.
> feat: Allow `monaco account deploy` command

- pkg/manifest/writer/manifest_writer.go
- pkg/manifest/writer/manifest_writer_test.go
Extend the manifestwriter to also write accounts if the FF is active.
If the FF is inactive a 1.0 manifest without any accounts is created.
If the FF is active a 1.1 manifest is created - if accounts where defined in the in-memory Manifest they are persisted, if none exist, the manifest will look like a 1.0 manifest but have version 1.1.
Small refactor to reuse existing code for creating the persistence URL type as initial commit.
Currently not, regardless of FF value.
Only once account downloads are implemented manifests will ever be written with Accounts. Currently no in-memory manifest will ever contain account data when persisted.
> feat(manifest): Extend manifest writer to persist Account definition

- pkg/account/resources.go
- pkg/persistence/account/errors.go
- pkg/persistence/account/load.go
- pkg/persistence/account/load_test.go
- pkg/persistence/account/test-resources/valid-with-refs.yaml
- pkg/persistence/account/types.go
- pkg/persistence/account/validate.go
Added data model to be used by deploy and download AM resources functions.
Additionally, the load am resources function is now considering references, and storing values of type `Reference` when necessary.
> chore: add basic data model for am resources in pkg/account package

- pkg/client/clientset.go
At least in E2E testing we somewhat frequently see the default 2min timout of the core- client being too low for a created bucket to become active, or a deleted bucket to be fully removed.
> fix(client): Increase timeout for Grail bucket operations to 5min

- cmd/monaco/account/account.go
- cmd/monaco/account/delete.go
- cmd/monaco/completion/completion.go
- go.mod
- go.sum
- pkg/account/delete/client.go
- pkg/account/delete/client_test.go
- pkg/account/delete/delete.go
- pkg/account/delete/delete_test.go
- pkg/account/delete/loader.go
- pkg/account/delete/loader_test.go
- pkg/account/delete/persistence.go
- pkg/delete/delete_test.go
Introduces account delete logic and command.
- delete persistence and loading is fully separate from config deletes. This by default covers our requirement to not mix types in one delete file, the respective loaders only understand their own formats. 
- this is lacking an E2E test as well as including the deletion after other account E2E tests. This will be a followup after deployments of accounts are merged - IMO there's no sense testing delete if we can't automatically deploy something to delete again. 
- the last commit refactors usage of the delete.Client and adds documentation comments to exported methods. **I've left this as it's own commit, so it can be discussed and potentially remove/changed again**. It's my latest take on how I found the interface easier to use after adding the …
> feat: Delete Account Resources

- Makefile
The cleanup-step was never properly executed but failed with `make: Nothing to be done for 'clean-environments'.`. This was due to spaces instead of a tab before the command. This PR changes this and enables the cleanup step again in the environment
> chore: Fix Makefile cleanup-test

- cmd/monaco/account/account.go
- cmd/monaco/account/download.go
This PR just adds the `account download ...` command to the CLI.
Currently, the command does nothing, as the functionality is not yet implemented in monaco.
> feat: added `account download` CLI command

- pkg/download/classic/downloader.go
- pkg/download/settings/settings.go
- pkg/download/settings/settings_test.go
When we query all settings, we're skipping settings that are marked as 'unmodifiable'. However, some of them have the property 'modifiablePaths' set, an exception to this rule.
This PR adds the check for the exception, and if any path is set, we're still downloading the setting.
Users will get an error message from the API if they try to update a property that is not modifiable; we're not doing any extra checks.
Additionally, this PR improves the log messages on how many settings/configs have been downloaded, skipped, and persisted.
Examples:
```
[…] info    Finished downloading 1 settings for schema "builtin:synthetic.browser.kpms".
[…] info    Finished downloading 3 settings for schema "builtin:synthetic.browser.name".
[…] info    Finished downloading 0 settings for schema …
```
> Fix: Download unmodifiable modifiable settings

- cmd/monaco/integrationtest/v2/test-resources/integration-all-configs/project/slo/as_settings_config.yaml
- pkg/config/parameter/compound/compound.go
When we introduced the duplicate-name check, we overlooked testing the compound as a name as well. This is now fixed by adding the Equal method to the Compound Parameter. This method is added to not publish all fields in the Compound Parameter. This is done, due to a template being in there, which is skipped in the comparison. Also, to initialize the parameter correctly, the New method is required, which is another reason not to open the fields.
> fix: Correctly parse compounds during the duplicate-name check

- cmd/monaco/account/delete.go
- cmd/monaco/account/deploy.go
- cmd/monaco/delete/command.go
- cmd/monaco/deploy/deploy.go
- cmd/monaco/download/download_configs.go
- cmd/monaco/download/download_integration_test.go
- cmd/monaco/generate/deletefile/deletefile.go
- cmd/monaco/generate/dependencygraph/dependencygraph.go
- cmd/monaco/integrationtest/account/runner.go
- cmd/monaco/integrationtest/integration_test_utils.go
- cmd/monaco/integrationtest/v2/delete_integration_test.go
- cmd/monaco/integrationtest/v2/invalid_manifests_produce_user_errors_e2e_test.go
- cmd/monaco/integrationtest/v2/references_test.go
- cmd/monaco/purge/purge.go
- pkg/manifest/loader/manifest_loader.go
- pkg/manifest/loader/manifest_loader_test.go
- pkg/manifest/manifest_test.go
Instead of always requting environmentGroups and viewing accounts as optional when loading a manifest, they are now both optional. This means manifests that are only used for deploying account resources, no longer need to define envirnment groups.
For convenience validation of manifests is still done in the loader, allowing callers to optionally define whether they require envs or accounts to be defined. With those options set, they do not be extended with dedicated validations, but just react to errors of the loader function as before.
Main change is in pkg/manifest/loader/manifest_loader.go
No
> feat(manifest): Make envGroups and accounts optional

- cmd/monaco/convert/convert_test.go
- cmd/monaco/integrationtest/assert.go
- internal/featureflags/permanent.go
- pkg/config/config.go
- pkg/config/config_test.go
- pkg/config/entities/entitymap.go
- pkg/config/entities/entitymap_test.go
- pkg/config/entities/resolvedentity.go
- pkg/config/entities/resolvedentity_test.go
- pkg/config/parameter/reference/reference.go
- pkg/config/parameter/reference/reference_test.go
- pkg/config/sort.go
- pkg/config/sort_test.go
- pkg/deploy/deploy.go
- pkg/deploy/deploy_test.go
- pkg/deploy/internal/automation/automation.go
- pkg/deploy/internal/bucket/bucket.go
- pkg/deploy/internal/bucket/bucket_test.go
- pkg/deploy/internal/classic/classic.go
- pkg/deploy/internal/classic/classic_test.go
- pkg/deploy/internal/setting/setting.go
- pkg/download/id_extraction/id_extraction.go
- pkg/download/id_extraction/id_extraction_test.go
This PR introduces a feature flag `FEAT_MONACO_EXTRACT_SCOPE_AS_PARAMETER`.
If it is set, monaco will inspect the `scope` parameter and treat it as an explicit parameter of inside the `config.yaml`
Example:
**Download of a settings 2.0 object with FF disabled:**
**Download of a settings 2.0 object with FF enabled:**
> feat: Extract Scope value as parameter

- pkg/download/dependency_resolution/dependency_resolution_test.go
- pkg/download/dependency_resolution/resolver/ahocorasick_dep_resolver.go
- pkg/download/dependency_resolution/resolver/basic_dep_resolver.go
- pkg/download/dependency_resolution/resolver/shared.go
- pkg/download/dependency_resolution/resolver/shared_test.go
- pkg/download/id_extraction/id_extraction.go
- pkg/download/id_extraction/id_extraction_test.go
This PR fixes the first parts of the id extraction during download. There needs to be more improvements in the id_extraction, but to keep things simple, this PR introduces the first set of changes.
This is fixing the first set of issues. The id_extraction has similar issues, but another solution on how this can be done needs to be found.
The change has one minor caveat: It requires a character before and after the search string. An ID that is only the content can't be found. However, since we are always handling JSON contents which are  never (in our case) a plain number, we can dismiss this. We always have at least quotes around the object.
Yes: For large environments, different ids might be extracted due to being more correct;
* Some random strings like …
> fix: More correctly extract ids from configs

- cmd/monaco/download/download_configs.go
- cmd/monaco/download/download_configs_test.go
- cmd/monaco/integrationtest/v2/all_configs_integration_test.go
- cmd/monaco/integrationtest/v2/bucket_integration_test.go
- cmd/monaco/integrationtest/v2/config_restore_e2e_test.go
- cmd/monaco/integrationtest/v2/delete_integration_test.go
- internal/featureflags/temporary.go
- pkg/persistence/config/internal/persistence/type_definition.go
- pkg/persistence/config/internal/persistence/type_definition_test.go
- pkg/persistence/config/loader/config_loader_test.go
1. drops the buckets feature flag, the feature is out without complaints for 2 months
2. fixes classic configs and buckets always being downloaded.
We should possibly discuss if always downloading classic config API types was desired.
YES
1. bucket feature can no longer be deactivated
2. config APIs and buckets are no longer always downloaded
> fix: Dont always download buckets and config API types

- internal/log/field/field.go
- pkg/download/automation/automation.go
- pkg/download/bucket/bucket.go
- pkg/download/classic/downloader.go
- pkg/download/settings/settings.go
For configs and settings we're no longer logging when there has been nothing downloaded. For buckets and automation resources, it's still logged to make it very prominent.
Additionally, this PR standardizes the logging a bit more.
Log examples:
<details><summary>Some logs with debug enabled:</summary>
```
2023-12-14T14:02:48+01:00       debug   Downloading all settings for schema builtin:problem.notifications
2023-12-14T14:02:48+01:00       debug   Did not find any settings to download for schema "builtin:process.built-in-process-monitoring-rule"
2023-12-14T14:02:48+01:00       debug   Downloading all settings for schema builtin:dashboards.presets
2023-12-14T14:02:48+01:00       debug   Did not find any settings to download for schema "builtin:rum.web.custom-errors" …
```
> feat(download): 🔊 Improve and standardize logging for downloaded configs.

- .github/workflows/build-test.yml
- .github/workflows/end-to-end-test.yml
With the v4 release of the publish artifacts GH action, it is no longer possible to upload additional files to the same artifact.
To rememdy this, each build step now uploads an artifact with it's own unique name.
The result collection workflows should not impacted by this, as they simply download all artifacts of the triggering job and unpack them.
> ci: Use unique artifact names for test results

- pkg/account/downloader/internal/http/groups.go
If the API returns inconsistent data, we should not fail.
For a user, this check is meaningless as they can do nothing if it fails and not being able to use monaco in that case until it is fixed does not make sense.
> feat(account): Don't fail on inconsistent API

- cmd/monaco/account/download.go
- pkg/account/downloader/downloader.go
If no data has been downloaded, we'd still create the download folder with only a manifest but nothing else. This is now no longer the case.
> feat(account): Don't create folder if no account data has been downloaded

- cmd/monaco/account/deploy.go
- cmd/monaco/integrationtest/account/all_resources_integration_test.go
Accept manifest as optional flag instead of positional arg for all commands.
This brings it in line with other commands and also reflects the usage change we want to introduce for config deploy in the near future. 
NO - not released yet
> feat(account): Accept manifest as optional flag instead of positional arg for all commands

- internal/featureflags/export_test.go
- internal/featureflags/featureflag.go
Since all FeatureFlags are listed inside `featureflags` package, and on-fly creation is not allowed New() function is useless except for testing. With this change, the `New()` function is moved to export_test.go file and is available only during the testing phase.
> Enable featureflags.New only for testing

- pkg/account/deployer/deployer.go
- pkg/account/deployer/deployer_test.go
- pkg/account/deployer/dispatcher.go
- pkg/account/deployer/dispatcher_test.go
- pkg/account/deployer/ids.go
- pkg/account/deployer/ids_test.go
This PR aims for improving the execution time of a deployment of account management resources by triggering API operations in parallel.  
As a first improvement the following operations 
1) fetching existing policies, management zones and groups
2) upserting policies, groups and users (each concurrently)
3) upserting bindings (each concurrently)
note, that 1,2 and 3 still (must) happen sequentially.
The last commit, itroduces another component called "Dispatcher" that acts as a "thread/go-rouine" pool to limit the amount of go-routines. I am not completely sure if it is really necessary, as the amount of requests made to the APIs are in general already limited by the underlying rest client. However, it makes the code a bit cleaner (imo) and removes the behavior of spawning a gouroutine …
> chore: increase performance of deployment of account management resources

- internal/featureflags/temporary.go
As the command is generally seperated from other features and no negative impact is expected, it is activated by default, but the the feature flag is retained for now, just in case.
> feat: Activate YAML schema generation command by default

- pkg/config/template/renderer.go
- pkg/config/template/renderer_test.go
Some configurations, e.g. synthetic monitors, support some special syntax to subistitute values, for example setting a header using the value like `"Bearer:  {SOME_ENTITY_ID | token}"` and things like that.
For quite some time, monaco inspects each payloads and searches for entity ids and replaces them with monaco references.
This process breaks go templating once we come across such values like above (e.g., In the example above something like {{{ externalIDs.SOME_ENTITY_ID }}} is created) 
Possible solution: as soon as we download configuration, parse the json tree and replace each opening curly brace ("{") with `{{'{'}}`. This would work, however this means that we would obfuscate a lot of configurations that naturally contain curly braces, e.g. workflow scripts. Also it is hard to …
> fix: handling of parameterized values that contain dt entity ids

- pkg/account/downloader/groups.go
- pkg/persistence/account/writer/writer.go
Similar to config downloads this PR just adds a missing log for accout resource download that tells the user where the downloaded resources can be found.
> chore: added missing log for am download location

- cmd/monaco/account/deploy.go
- cmd/monaco/dynatrace/dynatrace.go
- go.mod
- go.sum
- pkg/account/deployer/deployer.go
- pkg/account/deployer/dispatcher.go
- pkg/account/deployer/dispatcher_test.go
This PR enables the dispatcher to dynamically create workers on the fly instead of having a fixed-sized pool.
This way the dispatcher behaves like creating a worker (aka go routing) for each resource.
In the end i am still not totally sure whether spawning a go routine for each and every resource is so nice.
So for now i've set max workers to be equal to `MONACO_CONCURRENT_REQUESTS`
It has the nice effect that there are not potentially `n - defaultLimit`  started go routines waiting to passing the gate :P
> chore: limit requests for deploying account management resources

- cmd/monaco/integrationtest/v2/test-resources/integration-all-configs/project/network-zone/config.yaml
- cmd/monaco/integrationtest/v2/test-resources/integration-all-configs/project/network-zone/test-zone-2.json
- cmd/monaco/integrationtest/v2/test-resources/integration-all-configs/project/network-zone/test-zone.json
- pkg/api/api.go
- pkg/api/endpoints.go
- pkg/client/dtclient/config_client.go
- pkg/deploy/deploy.go
- pkg/download/classic/downloader.go
- pkg/download/classic/filter.go
- pkg/download/classic/filter_test.go
This PR adds network zone configuration, to known classic api's so that they are downloaded with monaco.
Default network zone (e.g. network zone with id == "default") will be excluded from download as modifications to this network zone is anyway rejected by the API.
During deployment, we need to make sure that always the PUT method is used for update as well as creation.
Adds support for network-zones to monaco.
> feat: Manage network zones configuration with monaco

- internal/idutils/numeric_id.go
- internal/idutils/numeric_id_test.go
This PR fixes an error in id extraction which is happening if the regular implementation for var integer reading would cause an overflow, resulting in Monaco not calculating a numeric ID.
> fix: reimplement numeric id extraction to handle overflows

- cmd/monaco/generate/deletefile/command.go
- cmd/monaco/generate/deletefile/deletefile.go
- cmd/monaco/generate/deletefile/deletefile_test.go
- cmd/monaco/integrationtest/cleanup.go
- pkg/client/dtclient/config_client.go
- pkg/client/dtclient/config_client_test.go
This, PR adds a special handling for network zone deployment errors that can occur when the feature for network zone is not (yet) enabled. 
In integration tests we need to make sure that we do not cleanup the specific setting responsible for enabling the network zone feature. Hence it needs to be ignored during cleanup/deletion
To do this, I've sneaked in an (already requested) feature to exclude or exclusively include specific configuration types when generating the delete file for configurations.
It fixes the bug. Additionally the user can add filters via flags to the delete file generation:
```
monaco generate deletefile ... --types builtin:alerting.profile  # generates delete file entries only for the given type(s)
monaco generate deletefile ... --exclude-types  # skips generating …
```
> fix: handle network zone deployment error

- cmd/monaco/convert/convert_test.go
- cmd/monaco/integrationtest/rewrite_functions.go
- cmd/monaco/integrationtest/v2/test-resources/integration-all-configs/project/alerting-profile/config.yaml
- pkg/persistence/config/internal/persistence/type_definition.go
- pkg/persistence/config/internal/persistence/type_definition_test.go
- pkg/persistence/config/loader/config_entry_loader.go
- pkg/persistence/config/loader/config_loader.go
- pkg/persistence/config/loader/config_loader_test.go
- pkg/persistence/config/loader/parameter_integration_test.go
- pkg/persistence/config/loader/template_integration_test.go
- pkg/project/v2/project_loader.go
This PR adds the first version of parsing complex API definitions so that we can later extend it to reference existing objects.
Currently, the following would be possible:
```yaml
configs:
- id: my-profile
type:
api:
name: profile
scope: […] 
config:
…
```
Note that the scope is currently still unused and needs to be used in the future when implementing the APIs.
This PR is the first version to build the other stuff upon. There is still some stuff to be done.
The type loading is a mess of yaml unmarshalling, mapstructure, multiple decoding steps, and code that is distributed throughout the config loading. 
The Unmarshalling step needs to be executed 5! times alone to make it work easily, which is obviously not what we want to do.
This should be refactored to load the type at the start and …
> feat: Extend API definitions that allow for complex API definitions

- pkg/api/api.go
- pkg/api/endpoints.go
- pkg/client/dtclient/config_client.go
- pkg/deploy/internal/classic/classic.go
The SubPath method broke the deployment as the former method checked whether the URL contained the {SCOPE} subpath. This led to a problem when we depended in a later step on the subpath check, and at that time, the proper URL without the {SCOPE} was already used instead.
> fix: Replace SubPath method by SubPath Property as it broke deployment

- Makefile
* go.uber.org/mock/mockgen@v0.2.0 -> 0.4
* github.com/sigstore/cosign/v2/cmd/cosign@v2.1.1 -> 2.2
Update version of go libraries used by make.
> chore: bump version of go libraries used in Makefile

- cmd/monaco/deploy/deploy.go
- cmd/monaco/download/downloadopts.go
- cmd/monaco/download/downloadopts_test.go
- cmd/monaco/generate/deletefile/command.go
- cmd/monaco/integrationtest/v2/all_configs_integration_test.go
- cmd/monaco/integrationtest/v2/integration_test_utils.go
- internal/featureflags/permanent.go
- pkg/api/api.go
- pkg/api/apis.go
- pkg/api/endpoints.go
There is a need to hide specific classic endpoints under development. For that reason api.API structure is expanded with a new field, and new filtering is added to prepareAPIs function
> Enable to define the required feature flag for an API

- internal/featureflags/permanent.go
- pkg/client/metadata/metadata.go
For most URLs simply replacing the .apps. part of the URL is enough to find the classic URL, which means we don't always need an authenticated API call to find the classic URL.
If a GET to the created URL does not reply with a 200 status code, the metadata endpoint will be called.
As there may be networking/DNS edge-cases where the replaced URL is valid (GET returns 200) but is not actually a Classic environment, a feature flag allows deactivation of the feature.
-
No noticeable change for users.
> feat: Build simple classic environment URL without API call

- cmd/monaco/download/downloadopts.go
- cmd/monaco/integrationtest/v2/test-resources/integration-all-configs/project/key-user-actions-web/config.yaml
- cmd/monaco/integrationtest/v2/test-resources/integration-all-configs/project/key-user-actions-web/key-user-action-web.json
- pkg/api/api.go
- pkg/api/endpoints.go
- pkg/api/endpointsV1.go
- pkg/client/dtclient/config_client.go
- pkg/client/dtclient/entities.go
- pkg/download/classic/download_test.go
Add support for the classic API `key-mobile-actions-web` (delete is not supported)
> Add support for `key-user-actions-web`

- cmd/monaco/integrationtest/v2/invalid_manifests_produce_user_errors_e2e_test.go
- pkg/manifest/internal/persistence/manifest_persitence.go
- pkg/manifest/loader/manifest_loader.go
- pkg/manifest/loader/manifest_loader_test.go
- pkg/persistence/config/internal/persistence/config_persistence.go
- pkg/project/v2/project_loader.go
- pkg/project/v2/project_loader_test.go
This PR makes projects optional in manifests:
- Manifests can be loaded which don't contain projects: a check is removed from `manifest_loader`
- Manifests must contain projects if projects are loaded: a check is added to `project_loader.go` 
- Manifest JSON spec is updated to reflect this change
- Some copy-paste errors in the manifest JSON spec are corrected
- Changed from `minLength` to `minItems` for restrictions on arrays
Yes, similar to `monaco download --url...` working without a project specified, it is now possible to download using a manifest that does not contain projects
> feat: Make projects optional in manifest

- cmd/monaco/integrationtest/account/resources/all-resources/manifest-account.yaml
- cmd/monaco/integrationtest/account/resources/deploy-download/manifest.yaml
- cmd/monaco/integrationtest/account/resources/mzones/manifest.yaml
- pkg/manifest/loader/manifest_loader.go
- pkg/manifest/manifest_test.go
- pkg/manifest/testdata/manifest_full.yaml
- pkg/manifest/writer/manifest_writer.go
- pkg/manifest/writer/manifest_writer_test.go
- pkg/version/version.go
refactor: Drop manifest version back to 1.0
When account resources where originally introduced, we expected
the manifest extension to support them to be a breaking change.
In their current version the addition of accounts to the manifest
is not a breaking change, but they are just an optional field in
the manifest. Older versions targeting config deployments will already
produce an error we consider clear enough, mentioning that the accounts
field can not be unmarshalled, and do not offer an account deployment
command, so it is should be clear enough to users that they need a
newer version to work with account resources.
Older versions produce the following error message when faced with an accounts field:
```sh
loading of manifest failed: …
```
> refactor: Drop manifest version back to 1.0

- internal/template/template_utils.go
- internal/template/template_utils_test.go
When loading parameter types like the value-parameter, characters like <, >, and & were escaped to their unicode-representation, due to the json unmarshaler escaping those by default. This commit changes this behavior, and those characters are no longer escaped.
This fixes a 🐛 where duplicated configurations were created, as the local (escaped) name did not match the remote (unescaped) name. Now, the correct object is updated instead.
---
A real-world example is the string that is now also a test case:
`[8/5] Disk space available < 15% (/media/datastore)` is escaped to `[8/5] Disk space available \\u003c 15% (/media/datastore)` in the parameter. However, the remote object is still called `[8/5] Disk space available < 15% (/media/datastore)`.
Since the strings don't match, and thus, the …
> fix: Parameter resolving must not escape HTML character

- pkg/download/classic/download.go
This PR contains two important small changes:
1.) when downloading user session properties, instead of using the "name" property as "name" and the "key" property as "originObjectID", i changed to code use the "key" as name directly, because it seems that the "workaround" with misusing  originObjectID is not needed.
2.) I've noticed that when monaco configs have the same name, (which can happen for scoped configurations) we use that as a name for the json files as well, which results in overwrites. So I am also adding the "parentConfigId" as suffix the the name if there is any.
> fix: use key property as configuration name for session properties api

- cmd/monaco/generate/deletefile/deletefile.go
- cmd/monaco/generate/deletefile/deletefile_test.go
- cmd/monaco/generate/deletefile/test-resources/project/application-mobile/app1.json
- cmd/monaco/generate/deletefile/test-resources/project/application-mobile/config.yaml
- cmd/monaco/generate/deletefile/test-resources/project/user-action-and-session-properties-mobile/config.yaml
- cmd/monaco/generate/deletefile/test-resources/project/user-action-and-session-properties-mobile/property1.json
- pkg/project/v2/project.go
- pkg/project/v2/project_test.go
This PR adds the feature to support scoped configurations when generating the deletefile using `monaco generate deletefile...`. The "scope" property of each delete entry will be the "name" property of the referenced config.
There is potential for code reuse to follow references and get their properties, but i didn't extracted that functionality yet.
> feat: consider scope when generating delete file

- cmd/monaco/account/load.go
- cmd/monaco/integrationtest/account/deploy-download_test.go
- internal/secret/email.go
- internal/secret/email_test.go
- pkg/account/delete/delete.go
- pkg/account/delete/loader.go
- pkg/account/deployer/deployer.go
- pkg/account/downloader/users.go
- pkg/account/resources.go
- pkg/persistence/account/internal/types/types.go
- pkg/persistence/account/loader/load.go
- pkg/persistence/account/writer/writer.go
This PR introduces the type `MaskedMail` in order to mask/hide sensitive/personal information like email addresses in logs.
The last [commit](https://github.com/Dynatrace/dynatrace-configuration-as-code/pull/1379/commits/4422948fb60c5339053cc0f79f5d8e61fbebadb7) uses the type `MaskedMail` directly inside the model (instead of string) wheras the [commit](https://github.com/Dynatrace/dynatrace-configuration-as-code/pull/1379/commits/ef483d75fa47402ec24c5540eb622b2ab1438d52) before casts the string type into `MaskedMail` on demand. 
You can decide which version you like more.
I'd use it as a field, because it's safer and you cannot forget it. Also it covers hidden leaks e.g. test assertions etc...
Email addresses in logs of account management are masked
> feat: Mask Emails in Account management logs

- pkg/project/v2/project_loader.go
- pkg/project/v2/project_loader_test.go
The duplicate name check marks all configs that are non-unique configs and where the name is declared as duplicate. This has the intention, that we don't update the same object multiple times in the same source config set.
However, a bug was present that if the same config was defined for multiple environments, that the duplicate name flag was set, since the config existed multiple times with the same name, **but for different environments**. This resulted in configs marked as duplicates, and thus not updating the remote object and creating a new one
This is now fixed by taking the target env into account during the check
> fix: Duplicate name check must take environment into account

- internal/concurrency/limiter_test.go
- internal/regex/regex_patterns_test.go
- internal/template/parse_test.go
- internal/template/template_test.go
- internal/template/template_utils_test.go
- internal/throttle/throttle_requests_test.go
- internal/timeutils/time_test.go
- pkg/client/dtclient/extension_upload_test.go
- pkg/client/useragent/transport_test.go
- pkg/config/coordinate/coordinate_test.go
- pkg/config/parameter/compound/compound_test.go
- pkg/config/parameter/environment/environment_test.go
- pkg/config/parameter/list/list_test.go
- pkg/config/parameter/reference/reference_test.go
- pkg/config/template/filebased_test.go
- pkg/converter/v1environment/environment_test.go
- pkg/deploy/internal/extract/configname_test.go
- pkg/download/classic/download_sanitize_test.go
- pkg/download/classic/test_utils.go
- pkg/download/dependency_resolution/dependency_resolution_test.go
- pkg/download/download_writer_test.go
- pkg/persistence/config/loader/parameter_integration_test.go
- pkg/persistence/config/loader/template_integration_test.go
- pkg/project/v1/config_test.go
- pkg/project/v1/project_loader_test.go
- pkg/project/v1/topologysort_test.go
- pkg/rest/request_test.go
Replace gotest/assert with testify in remaining unit tests
I did not cover integration/e2e tests yet.
It could be that i forgot some.
I've tried to use `require` and `assert` more  purposely, i.e.
```
result, err := doSomething()
require.NoError(t,err)
assert.Equal(t,expected,result)
```
> chore: Unify testing code (ctd. II)

- .github/workflows/build-test.yml
- .github/workflows/dependencies-and-licenses.yml
- .github/workflows/end-to-end-test.yml
- .github/workflows/pr-static-code-analysis.yml
- .github/workflows/semgrep.yml
- go.mod
- pkg/download/classic/download.go
- pkg/download/dependency_resolution/dependency_resolution.go
Updates `go.mod` and Workflows to go `1.22`
Also removes a couple of redundant assignments within loops
> chore: Update go version to 1.22.0

- pkg/api/endpoints.go
- pkg/client/dtclient/config_client.go
- pkg/deploy/internal/classic/classic.go
- pkg/download/classic/download.go
This PR just extracts the values for classic config names into their own constants to reduce the risk of having typos and searching unnecessarily for errors for quite some time
> refactor: constants for api names/types

- cmd/monaco/generate/deletefile/command.go
- pkg/api/endpoints.go
- pkg/delete/delete.go
A dashboard share setting cannot be deleted.
Hence they need to be ignored during the generation of the delete file as well as during deletion in case users manually put them inside the delete file.
> feat: Ignore dashboard-share-settings in context of deletion

- internal/featureflags/temporary.go
- pkg/api/api.go
- pkg/api/endpoints.go
- pkg/api/endpoints_test.go
- pkg/download/classic/download.go
- pkg/download/classic/download_test.go
Adds support for downloading dashboard sharing settings
- As the feature is still in development, it must be enabled using the `MONACO_FEAT_DASHBOARD_SHARE_SETTINGS` feature flag.
- One and only one dashboard sharing configuration is available per dashboard.
- For security reasons `URLs` are removed from `publicAccess`
Yes, dashboard sharing settings configurations and templates will now be downloaded into `dashboard-share-settings`
> feat: Download dashboard sharing settings

- .github/workflows/dependencies-and-licenses.yml
To align with other SBOM initiatives, this PR changes the SBOM output format from XML to JSON and the used `args` to assert licenses, so that they are stored in the `licenses` section of the BOM. Since node.js 16 actions are [deprecated](https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/), the integration is replaced by the go package that it wraps (also avoiding rate limit issues as occurred during the 2.11.0 release).
I've manually generated and validated the expected JSON output.
The SBOM is now published as a JSON document.
> chore: Generate SBOM in JSON format

- cmd/monaco/delete/command.go
- cmd/monaco/integrationtest/v2/test-resources/integration-all-configs/project/key-user-actions-mobile/config.yaml
- cmd/monaco/integrationtest/v2/test-resources/integration-all-configs/project/key-user-actions-web/key-user-action-web.json
- pkg/delete/delete.go
- pkg/delete/delete_loader_test.go
- pkg/delete/delete_test.go
- pkg/delete/internal/classic/client.go
- pkg/delete/internal/classic/delete.go
Add `delete` functionality for next endpoints:
* `userActionAndSessionProperties`
* `key-user-actions-web`
* `key-user-actions-mobile`
> `delete` feature for `key-user-actions-*` and `userActionAndSessionProperties`

- cmd/monaco/download/downloadopts_test.go
- cmd/monaco/generate/deletefile/deletefile_test.go
- cmd/monaco/integrationtest/v2/all_configs_integration_test.go
- cmd/monaco/integrationtest/v2/delete_integration_test.go
- cmd/monaco/integrationtest/v2/scoped_configs_test.go
- internal/featureflags/permanent.go
- internal/featureflags/temporary.go
- pkg/api/endpoints.go
- pkg/delete/delete_loader_test.go
This PR replaces the general "MONACO_EXPERIMENTAL" feature flag for activating APIs with specific ones.
> chore: use specific FF for MRUM properties

- .ci/releasePipeline.groovy
Simlar to the binary name and paths, there's now just a method to get the name of the sha file for a binary, removing the need to hardcode the filename in several places and introducing errors like accidentally using different file-endings in different places.
Refactors the release pipeline a bit to make it less error prone in the future.
Simlar to the binary name and paths, there's now just a method to get the name of the sha file for a binary, removing the need to hardcode the filename in several places and introducing errors like accidentally using different file-endings in different places.
> ci: Introduce reusable method for sha file name instead of hardcoding

- pkg/api/api.go
- pkg/api/endpoints.go
- pkg/client/dtclient/client.go
- pkg/client/dtclient/config_client.go
- pkg/client/dtclient/config_client_test.go
- pkg/client/dtclient/entities.go
KUAs are identifies by name+domain+action type, and not by name only.
Since this information is present in the payload we need a way to compare their values to existing dynatrace objects.
I've introduced a custom function that can be registered on the API level to do this job.
This function can/should be re-used e.g. when dealing with deletion use case.
> Fix: Correctly identify Key-User-Actions for web applciations

- pkg/config/config.go
- pkg/deploy/internal/classic/validation.go
- pkg/deploy/internal/classic/validation_test.go
This PR adds stricter validation for sub-path APIs, only allowing the same name if the scope is different.
`key-user-action-web` configs are explicitly excluded as the uniqueness of these is determined by three fields in the payload
Yes, improved validation for classic configs for sub-path APIs: increases the chance of the user being presented with an error if the configs are not unique.
> Fix: Improve uniqueness checks for subpath APIs by taking scope into account

- cmd/monaco/integrationtest/assert.go
- cmd/monaco/integrationtest/integration_test_utils.go
- cmd/monaco/integrationtest/rewrite_functions.go
- cmd/monaco/integrationtest/v1/integration_test_utils.go
- cmd/monaco/integrationtest/v2/integration_test_utils.go
- cmd/monaco/integrationtest/v2/scoped_configs_test.go
- cmd/monaco/integrationtest/v2/test-resources/scoped-configs/project/dashboard-share-settings/config.yaml
- cmd/monaco/integrationtest/v2/test-resources/scoped-configs/project/dashboard-share-settings/dashboard1.json
- cmd/monaco/integrationtest/v2/test-resources/scoped-configs/project/dashboard/config.yaml
- cmd/monaco/integrationtest/v2/test-resources/scoped-configs/project/dashboard/dashboard1.json
- pkg/client/dtclient/client.go
Extends `cmd/monaco/integrationtest/v2/scoped_configs_test.go` to deploy dashboard-share-settings with sharing disabled, checks the change, re-deploys with sharing enabled, and checks the change.
> Test: Extend test deploy scoped configurations

- pkg/client/dtclient/settings_client.go
This PR ensures `externalId`s are correctly applied to `builtin:oneagent.features` settings objects by removing code in ` upsertSettings(...)` that was preventing this.
This allows `builtin:oneagent.features` settings objects with scopes of monitored entities to be deleted as required.
To prevent `builtin:oneagent.features` settings objects with for example environment scope from being deleted, existing checks for `ModificationInfo.Deletable` are used.
> fix: Apply externalId to settings objects with `builtin:oneagent.features` schema

- cmd/monaco/integrationtest/v2/scoped_configs_test.go
This PR fixes the fact that `v2.TestDeployScopedConfigurations` was using `monaco.Runf(...)` instead of `monaco.RunWithFsf(...)` when deploying, resulting configs without test suffixes being applied.
> test: Use `monaco.RunWithFsf(...)` when deploying in `TestDeployScopedConfigurations`

- cmd/monaco/download/downloadopts_test.go
- cmd/monaco/generate/deletefile/deletefile_test.go
- cmd/monaco/integrationtest/v2/all_configs_integration_test.go
- cmd/monaco/integrationtest/v2/delete_integration_test.go
- cmd/monaco/integrationtest/v2/scoped_configs_test.go
- internal/featureflags/temporary.go
- pkg/api/endpoints.go
Added FF for each new API/endpoint and removed the "grouper" FF.
Also I've already activated kua-mobile, user-actions-session-props, and dashboard-share-settings per default.
> Feature flags for new apis/endpoints

- internal/featureflags/temporary.go
- pkg/account/deployer/client.go
- pkg/account/deployer/client_test.go
This PR introduces a feature flag `MONACO_SKIP_READ_ONLY_ACCOUNT_GROUP_UPDATES` which, when enabled, causes groups owned by SCIM and ALL_USERS not be updated during deployment.
> Feat: Skip updates to SCIM and ALL_USERS account groups

- internal/environment/get_env_value.go
- pkg/api/api.go
- pkg/api/endpoints.go
- pkg/deploy/deploy.go
- pkg/project/v2/project_loader.go
- pkg/project/v2/project_loader_test.go
This makes sure that web key user actions can reliably deployed.
Since this API seems to work unreliably whenever we try to create multiple key user actions **in parallel**
this PR forces configs of this type to be deployed sequentially with a 2 second delay between each.
Note that we can only rely on configs to be in the same independent graph component when there are dependencies between them. Hence this approach does not work when hard coding the scope of a web key user actions to a specific web application. For this reason specifying a hard coded scope for web key user actions is not allowed and will result in an error printed to the user.
> fix: deploy web key user actions sequentially

- cmd/monaco/integrationtest/account/all_resources_integration_test.go
- cmd/monaco/integrationtest/account/resources/all-resources/accounts/groups.yaml
- pkg/account/deployer/deployer.go
- pkg/account/downloader/downloader_test.go
- pkg/account/downloader/groups.go
- pkg/account/resources.go
- pkg/persistence/account/internal/types/types.go
- pkg/persistence/account/loader/load.go
- pkg/persistence/account/writer/writer.go
This PR adds support for `federatedAttributeValues` to account groups. This allows Monaco to deploy groups with owner `SAML`.
> Feat: Add support for federated attribute values in account groups

- .github/workflows/end-to-end-test.yml
- Makefile
As the account management API currently frequently causes issues with our E2E tests, they are now run explicitly and no longer included in the main E2E tests.
This allows us to easily discern test failures we currently do not care about (API fixes incoming).
The change to the make targets could be continued in follow up refactorings, removing the 'v1' and 'download-restore' build tags and simply running tests based on the folders they're mostly already in. 
To keep this PR focused it just makes the change of splitting out account management.
E2E tests workflow will have to be merged to actually run with this code state, so not even triggering E2E tests for this branch.
no
> ci: Split Account Management E2E tests into their own test stage

- cmd/monaco/integrationtest/v2/version_logged_e2e_test.go
- cmd/monaco/runner/runner.go
- pkg/version/version.go
To make it easier to support Monaco, this PR adds an info log of the version at the start of every command. Furthermore, to ensure that it is persisted, it is logged after the log file has been initialized.
> feat: Log Monaco version at the beginning of every command

- pkg/config/config.go
- pkg/persistence/config/internal/persistence/type_definition.go
- pkg/persistence/config/loader/config_loader_test.go
- pkg/persistence/config/writer/config_writer_test.go
This PR extends configurations with support for dashboard and notebooks. This permits syntax like:
```
- id: MyDashboard
config:
name: My dashboard
originObjectId: ext-ID-123 
template: my-dashboard.json
skip: false
type:
document:
type: dashboard
```
To use this feature, enable the feature flag by setting `MONACO_FEAT_DOCUMENTS` to `true`
> chore: Extend config to support dashboard and notebook documents

- .github/workflows/end-to-end-test.yml
As there is a known issue in the IAM API, these tests are not currently useful to us.
To still be able to run them selectively, they are limited to unly run for PRs if labeled with a specific new label.
This is to be removed when the API issues are resolved and we actually get value from these tests again
> ci: Only run IAM E2E tests if specifically triggered via label

- cmd/monaco/download/download_configs.go
- cmd/monaco/download/download_configs_test.go
- cmd/monaco/integrationtest/assert.go
- cmd/monaco/integrationtest/v2/delete_integration_test.go
- pkg/client/clientset.go
- pkg/delete/delete.go
- pkg/delete/internal/automation/delete.go
- pkg/download/automation/download.go
- pkg/download/bucket/download.go
This PR adapts the Delete logic so that deletion of automation resources is happening in correct order, Workflows --> Scheduling Rules --> BusinessCalendars.
> fix: Delete automation resources in correct order

- cmd/monaco/download/download_configs.go
- cmd/monaco/download/download_configs_test.go
- cmd/monaco/integrationtest/assert.go
- cmd/monaco/integrationtest/v1/integration_test_utils.go
- cmd/monaco/integrationtest/v2/non_unique_names_e2e_test.go
- cmd/monaco/integrationtest/v2/settings_integration_test.go
- cmd/monaco/integrationtest/v2/skip_e2e_test.go
- pkg/client/clientset.go
- pkg/client/dtclient/client.go
- pkg/client/dtclient/dummy_client.go
- pkg/delete/delete.go
- pkg/delete/delete_test.go
- pkg/delete/internal/classic/delete.go
- pkg/delete/internal/setting/delete.go
- pkg/deploy/deploy.go
- pkg/deploy/deploy_test.go
- pkg/deploy/internal/classic/classic.go
- pkg/deploy/internal/setting/setting.go
- pkg/deploy/internal/setting/setting_test.go
- pkg/download/classic/download.go
- pkg/download/classic/download_test.go
- pkg/download/settings/download.go
- pkg/download/settings/download_test.go
With https://github.com/Dynatrace/dynatrace-configuration-as-code/pull/1455/files#diff-fa7dc8186897d976c2c1839920a9cd0e41eb14a46cac7e2fa48426ce52f65173 we've introduced client facing interfaces for automation as well as bucket client. For config and settings client we already used a client interface. This is just a follow up PR to [move](https://github.com/Dynatrace/dynatrace-configuration-as-code/pull/1458/files#diff-fa7dc8186897d976c2c1839920a9cd0e41eb14a46cac7e2fa48426ce52f65173R50) the existing interface for settings and classic configs to the same package/place as the other interfaces.
> chore: moved settings and config client interfaces to client package

- go.mod
- go.sum
- pkg/delete/internal/bucket/delete.go
- pkg/deploy/internal/bucket/bucket.go
- pkg/deploy/internal/bucket/bucket_test.go
- pkg/download/bucket/download.go
This PR adapts to changes in the error handling in the buckets client, specifically https://github.com/Dynatrace/dynatrace-configuration-as-code-core/pull/93
Currently, it points to a commit in the `github.com/dynatrace/dynatrace-configuration-as-code-core` library; once the adaption PRs are merged there this PR will need to be updated to use the new release.
> chore: Adapt to changes in error handling in the buckets client

- .gitignore
- cmd/monaco/download/download_command.go
- cmd/monaco/download/download_configs.go
- cmd/monaco/download/download_configs_test.go
- cmd/monaco/download/downloadopts.go
- cmd/monaco/integrationtest/v2/references_test.go
- go.mod
- go.sum
- pkg/client/clientset.go
- pkg/download/document/download.go
- pkg/download/document/download_test.go
- pkg/download/document/testdata/getDashboardDocument.json
- pkg/download/document/testdata/getNotebookDocument.json
- pkg/download/document/testdata/listDashboardDocuments.json
- pkg/download/document/testdata/listNoNotebookDocuments.json
- pkg/download/document/testdata/listNotebookDocuments.json
This PR adds support for downloading documents of type `dashboard` and `notebook`, placing these within in the project in folders of the same name.
To use this feature, enable the feature flag by setting `MONACO_FEAT_DOCUMENTS` to `true`
> feat: Download dashboard and notebook documents

- cmd/monaco/main.go
- cmd/monaco/runner/runner.go
- internal/featureflags/permanent.go
- internal/log/log.go
`MONACO_LOG_FILE` is treated to be set per default, hence Monaco will continue writing to the .logs directory. If it is set to false, it will not write log files. This is overruled as soon as the `--support-archive` flag is used. Then we obviously need/want to write logs to files and collect them.
> feat: introduce `FEAT_LOG_FILE` environment variable to deactivate log files

- cmd/monaco/integrationtest/v2/bucket_integration_test.go
- cmd/monaco/integrationtest/v2/delete_integration_test.go
- pkg/delete/delete_test.go
- pkg/delete/internal/automation/delete.go
- pkg/delete/internal/bucket/delete.go
- pkg/delete/internal/classic/delete.go
- pkg/delete/internal/setting/delete.go
- pkg/delete/loader.go
- pkg/delete/loader_test.go
- pkg/delete/persistence/delete_persistence.go
- pkg/delete/pointer/delete_pointer.go
Currently, delete file entries for automation resources and buckets contain `project`, `type` and `configId`, which are used to regenerate the ID of the object to delete during deletion. However, this doesn't work for objects not created by Monaco, as these have IDs that do not correspond.
Instead, to enable the deletion of pre-existing objects, delete file entries should support object ID (explicit field objectId ) as an alternative that, when available, is used instead of a generated ID.
When implementing the fix for automation and bucket resources we’ve agreed that we generally change the format of the delete file entries to be more expressive: Proposal for changes of the `delete.yaml` file:
```
delete:
- type: <ANY>
objectId: 123453
- type: <SETTINGS>/<AUTOMATION>/bucket
id: XYZ …
```
> delete by objectId

- cmd/monaco/download/download_configs.go
- cmd/monaco/download/download_configs_test.go
With this PR, `download.copyConfigs(...)` merges the provided configs with those of the same type in the destination, rather than simply overwriting them.
> fix: Merge rather than overwrite downloaded configs of same type

- pkg/config/config.go
- pkg/download/document/download_test.go
- pkg/persistence/config/internal/persistence/type_definition.go
- pkg/persistence/config/loader/config_loader_test.go
- pkg/persistence/config/writer/config_writer_test.go
Currently the type `dashboard` is used for both platform and classic dashboard configs. This has two implications:
- It is not possible to have a platform dashboard and classic dashboard configuration with the same config ID
- A different value `type` must be chosen for platform dashboards  in delete files to ensure the entry is not ambiguous.
This PR removes the ambiguity by changing to `dashboard-document` for platform dashboards and `notebook-document` for notebooks.
Yes, with this PR, platform dashboard configs are specified as follows:
```
configs:
- id: my-dashboard
config:
name: My platform dashboard
template: platform-dashboard.json
skip: false
type:
document:
type: dashboard-document
```
while for notebooks:
```
configs:
- id: my-notebook
config:
name: My demo notebook
template: …
```
> chore: Use `dashboard-document` and `notebook-document` for document types

- internal/featureflags/temporary.go
- pkg/persistence/config/internal/persistence/type_definition.go
This PR places the persistence of settings object order behind the `MONACO_FEAT_PERSIST_SETTINGS_ORDER` feature flag.
It is a follow up to #1465 to allow users to opt-in to this feature, as it appears some ordered settings have additional constraints which prevent Monaco updating objects even if the order is unchanged.
When `MONACO_FEAT_PERSIST_SETTINGS_ORDER` is set to `true` or `1`, the config parameter `insertAfter` will be persisted in the associated config file when downloading configs; if left unset or disabled,  it will simply be omitted.
Regardless of the state of the feature flag, users can specify `insertAfter` in configs to deploy, subject to the constraints of the underlying settings schema.
> chore: Require feature flag `MONACO_FEAT_PERSIST_SETTINGS_ORDER` for persisting order of settings objects

- cmd/monaco/delete/delete.go
- pkg/delete/delete.go
- pkg/delete/delete_test.go
- pkg/delete/internal/automation/delete.go
- pkg/delete/internal/bucket/delete.go
- pkg/delete/internal/classic/delete.go
- pkg/delete/internal/document/delete.go
- pkg/delete/loader_test.go
With this PR `delete` functionality for documents id supported.
Same as for another type, there are two types of definitions:
1.  via coordinate:
```
- type: document
project: <name_of_project>
id: <monaco_config_id>
```
2. directly:
```
- type: document
objectId: <DT_id_of_the_entity>
```
> delete functionality for documents

- go.mod
- go.sum
This PR updates the `dynatrace-configuration-as-code-core` library to the most recent version.
> chore: Update `dynatrace-configuration-as-code-core` library

- cmd/monaco/purge/purge.go
- internal/featureflags/temporary.go
- pkg/delete/delete.go
- pkg/delete/delete_test.go
- pkg/delete/internal/classic/delete.go
- pkg/delete/internal/document/delete.go
- pkg/delete/loader_test.go
This PR adds `purge` functionality for documents.
DT still doesn't support complete document deletion functionality. To be able to use the `delete` or `purge` command, the MONACO_FEAT_DELETE_DOCUMENTS flag needs to be set to true.
> Purge functionality for documents

- internal/log/field/field.go
This PR ensures that the string representation of an error is always logged in the structured logging `error` field instead of the underlying fields of the exported error.
As an example:
- Without the change:
```
{"level":"debug","ts":"2024-06-11T15:48:00+02:00","msg":"Can't parse current monaco version: failed to parse version: minor x is not a number","error":{"type":"*errors.errorString","details":{}}}
```
- With the change
```
{"level":"debug","ts":"2024-06-11T15:45:19+02:00","msg":"Can't parse current monaco version: failed to parse version: minor x is not a number","error":{"type":"*errors.errorString","details":"failed to parse version: minor x is not a number"}}
```
It is worth noting that fields themselves are only logged when JSON logging is enabled (through …
> fix: Ensure error message appears in error log field

- cmd/monaco/deploy/deploy.go
- cmd/monaco/deploy/deploy_test.go
- internal/featureflags/temporary.go
- pkg/config/config.go
- pkg/persistence/config/internal/persistence/type_definition.go
- pkg/persistence/config/loader/config_loader_test.go
- pkg/persistence/config/writer/config_writer_test.go
- pkg/project/v2/project.go
This PR adds support for the persistence of OpenPipeline configs:
```
- id: 16f77aad-e590-4652-9e8d-0af860f68362
config:
template: 16f77aad-e590-4652-9e8d-0af860f68362.json
skip: false
type:
openpipeline:
kind: bizevents
```
Notes:
- The feature is behind the `MONACO_FEAT_OPENPIPELINE` feature flag.
- Only a single config of each kind is permitted within each environment - the PR enhances the validation of load projects before deployment.
- Kind is a free-text field validated by the OpenPipeline API.
> feat: Persist OpenPipeline configs

- cmd/monaco/generate/deletefile/deletefile.go
This PR logs as INFO the skipped creation of delete file entries for OpenPipeline configs
> chore: Log skipped creation of OpenPipeline delete entries

- pkg/project/v2/project_loader.go
- pkg/project/v2/project_loader_test.go
When both, `builtin:networkzones` and `network-zone` apis are deployed, we need to make sure the settings 2.0 object is deployed first. Hence we introduce a fixed parameter as soon as we see both config appearing in a config set.
First commit fixes the problem, second commit reduces cognitive complexity of that code area in general.
fixes #1356
> feat: Add Fixed parameter for `network-zones`

- cmd/monaco/convert/convert.go
- cmd/monaco/convert/convert_test.go
- cmd/monaco/download/downloadopts_test.go
- cmd/monaco/generate/command.go
- cmd/monaco/generate/deletefile/deletefile_test.go
- cmd/monaco/integrationtest/account/all_resources_integration_test.go
- cmd/monaco/integrationtest/account/deploy-download_test.go
- cmd/monaco/integrationtest/v2/all_configs_integration_test.go
- cmd/monaco/integrationtest/v2/delete_integration_test.go
- cmd/monaco/integrationtest/v2/scoped_configs_test.go
- cmd/monaco/runner/runner.go
- internal/featureflags/permanent.go
- internal/featureflags/temporary.go
- internal/idutils/uuid_generator.go
- pkg/api/endpoints.go
- pkg/converter/converter.go
- pkg/converter/converter_test.go
- pkg/manifest/writer/manifest_writer.go
- pkg/manifest/writer/manifest_writer_test.go
We have a large amount of FFs allowing to deactivate features we felt uncertain about, as well as development flags for features already released.
It also moves some flags I didn't feel safe removing to the 'permantent.go' file.
This was done to make reworking FFs so we can log them simpler by having fewer flags.
Yes and No - some features can no longer be turned off, via FFs that are not documented.
> Remove old temporary feature flags

- cmd/monaco/integrationtest/v2/documents_integration_test.go
- cmd/monaco/integrationtest/v2/test-resources/integration-documents/project/document-notebook/config.yaml
based on https://github.com/Dynatrace/dynatrace-configuration-as-code/pull/1529 and https://github.com/Dynatrace/dynatrace-configuration-as-code-core/pull/118 this PR makes minor adjustments to the documents related e2e tests in order to test creating documents that are "initially public"
> test: create initially public documents in e2e tests

- pkg/config/parameter/compound/compound.go
- pkg/config/parameter/compound/compound_test.go
- pkg/config/parameter/reference/reference.go
- pkg/config/resolve.go
- pkg/deploy/internal/classic/validation.go
- pkg/deploy/internal/classic/validation_test.go
This, PR contains a quick fix for validating name parameters of classic configs.
First, we try to resolve the name parameters and compare their values.
If resolving the paramters didn't work (because of missing resolved entities) we check if both parameters are reference parameters and assume that they will resolve to the same name if they look exactly the same. The same check is also done if both paramters are of type "compoundParameter". 
Note that this check misses the situation where compound parameters point to local reference parameters that resolves to different values tho. There is a test case which should cover this case. Currently it is skipped. https://github.com/Dynatrace/dynatrace-configuration-as-code/pull/1530/files#diff-12f7b59badc043a408921cbc6e7416edc7623283f022bb7971b7f9 …
> Fix: Better name parameter validation

- pkg/api/endpoints.go
- pkg/download/classic/download.go
- pkg/persistence/config/writer/config_writer.go
- pkg/persistence/config/writer/config_writer_test.go
This PR contains couple of refactorings to cleanup logic for downloading configs.
The last two commits fixes downloading of scoped configuration like "key user actions" which were duplicated before which resulted in duplicate config writese to disk. Also possible template file clashes are fixed by the last commit.
> fix: Avoid duplicate config downloads and template file overwrites

- cmd/monaco/download/download_configs_test.go
- cmd/monaco/download/download_integration_test.go
- pkg/client/dtclient/settings_client.go
- pkg/download/settings/download.go
- pkg/download/settings/download_test.go
Previously we needed to perform n API calls to detect whether any of the n schemas is "ordered".
With this PR this is reduced to a single API call to fetch all schemas at once and and evaluating their "ordered" field.
> refactor: make schema download performant again

- pkg/download/classic/download.go
- pkg/download/classic/download_test.go
Dashboards and Dashboard-share-settings have the same ids which causes clashes in code that collects configs by IDs, i.e. keys are overwritten, e.g. keys for dashboard-share-settings override keys for dashboards. 
Depending on the order of configs, this ultimately caused the code for excluding references between dashboards to be skipped.
I couldn't find out a strong requirement for using same IDs for this kind of parent-child configs.
So I've deleted the test for it. It would be great if somebody could verify that this is actually not a hard requirement.
> fix: dependency circle between dashboards and dashboard-share-settings

- pkg/download/id_extraction/id_extraction.go
- pkg/download/id_extraction/id_extraction_test.go
during download, we extract and convert IDs into parameters, we also do this for the "scope" parameter. Depending on the settings object the scope could contain dots (".") which are then used as a key of the reference parameters However, monaco fails to resolve these parameters as monaco assumes dots to be nested structures. Example:
```yaml
- id: 1
config:
parameters:
extractedIDs:
type: value
value:
id_metric_postgres.session_time.count: metric-postgres.session_time.count
template: 1.json
skip: false
type:
settings:
schema: builtin:metric.metadata
schemaVersion: "4.28"
scope:
property: extractedIDs.id_metric_postgres.session_time.count
type: reference
```
monaco fails to resolve the parameter "extractedIDs.id_metric_postgres.session_time.count" as it assumes the following parameter …
> fix: avoid dots in extracted parameters

- pkg/download/id_extraction/id_extraction.go
- pkg/download/id_extraction/id_extraction_test.go
Cherry-pick of #1562 into the existing branch for 2.15.x (or the 2.15.1 CI fix), as main is currently not in a state that would allow releasing the small bugfix.
(Done via PR for transparency & running E2E tests)
> Fix extracted ID parameters with dots for 2.15.x

- pkg/deploy/preload.go
- pkg/deploy/preload_test.go
The Cache cannot deal with scoped configs and will return "unresolved" config URLs, i.e. the parent id will stay unresolved.
This PR adds a check for scoped configs (configs that have a parent) and skips doing any caching.
> fix: skip caching scoped configs

- cmd/monaco/download/download_command.go
- cmd/monaco/dynatrace/dynatrace.go
- cmd/monaco/integrationtest/v2/non_unique_names_e2e_test.go
- go.mod
- go.sum
- pkg/client/classicheartbeat/client.go
- pkg/client/clientset.go
- pkg/client/dtclient/client.go
- pkg/client/dtclient/config_client.go
- pkg/client/dtclient/extension_upload.go
- pkg/client/dtclient/list.go
- pkg/client/dtclient/settings_client.go
- pkg/client/metadata/metadata.go
- pkg/client/version/version_check.go
This PR updates the core library and only uses the core rest request retrier for 429s (TooManyRequests)
This allows us to:
- maintain custom retry logic in the classic clients for the moment
- use the rate limiting logic in the core REST client
> fix: Use core rest request retrier only for 429s

- go.mod
Our currently used go directive omitting the patch version, will result in .0 'or higher' being used at the discrection of the build tool-chain. In some tools this open defintion leads to 1.22.0 being used (happens in ko container image build), which is 6 patches behind and has vulnerabitlies. We also can't be sure in the regular builds that the latest patch is being used or not.
Thus an explicit fixed version is set, to the currently latest 1.22.6 patch (1.23.x should be introduced seperately). Our setup of dependabot should cover these version updates as well and update with future patches automatically.
none
> build: Use explicit latest Go version

- pkg/api/endpoints.go
- pkg/api/endpointsV1.go
This API seems to be not available anymore and is replaced by a settings 2.0 config.
Hence this API is marked as deprecated.
> chore: removed v1 calculated metrics log api

- pkg/delete/internal/setting/delete.go
This PR [enhances the debug messages ](https://github.com/Dynatrace/dynatrace-configuration-as-code/pull/1573/commits/527921f3c692bc518121cf29f009e66cdc8e76ff) spit out by monaco in case no settings 2.0 object was found for deletion.
I hate `else` branches :D , so I've refactored and cleaned up the code a bit to have it more readable.
> chore: enhance debug message of config deletion

- pkg/download/settings/download.go
- pkg/download/settings/download_test.go
When the `MONACO_FEAT_PERSIST_SETTINGS_ORDER` feature flag is turned on, Monaco is trying to inject `insertAfter` parameters in order to preserve the actual ordering of downloaded settings. However, it turned out that some of the settings objects are marked as not movable which ends up in an API error if `insertAfter`is used for these objects (even if the ordering does not change). This PR makes sure that `insertAfter`parameters are only created when the settings object is movable.
This makes turning on the feature flag safe(r) as Monaco will produce configuration sets that are deployable again.
> fix: only consider movable objects when injecting `insertAfter` parameters

- go.mod
This PR updates the toolchain to go 1.22.7
> chore: Update toolchain to go 1.22.7

- .ci/releasePipeline.groovy
This PR requires release candidates be tagged with the form `x.x.x-rc.x`.
> fix: Release candidate tags should have suffix of form `-rc.x`

- cmd/monaco/dynatrace/dynatrace.go
- cmd/monaco/integrationtest/v2/supportarchive_e2e_test.go
- cmd/monaco/runner/runner.go
- internal/trafficlogs/logger.go
- internal/trafficlogs/logger_test.go
- pkg/client/clientset.go
This PR resolves some issues with logging HTTP traffic in Monaco:
* Avoid calling `file::sync`unnecessarily after writing each entry into the files
* Avoid using multiple instances of traffic logger
* Use Buffered Writer to write content into files
* Flush / Sync content once before adding files to the zip archive
> Enhance HTTP traffic logging

- pkg/download/settings/download_test.go
- pkg/download/settings/filter.go
- pkg/download/settings/filter_test.go
`builtin:host.monitoring.mode` objects are handled in a bit special way, and it's not reliable to download them. Thus, we decided to skip them during download by default. If a customer still wants to download them, they can do so by providing the `MONACO_FEAT_DOWNLOAD_FILTER=false` environment variable.
None
`builtin:host.monitoring.mode` are no longer downloaded by default.
> fix: Don't persist `builtin:host.monitoring.mode` settings by default

- internal/version/version_utils.go
- internal/version/version_utils_test.go
- pkg/client/dtclient/extension_upload.go
- pkg/client/dtclient/extension_upload_test.go
- pkg/manifest/loader/manifest_loader_test.go
This PR fixes an issue where `1.9` was considered greater than `1.10` when comparing extension versions.
Rather than using a string compare, the existing `Version` struct from the `version` package  is used.
This was, however, generalized to accept `1`, i.e. just a major version, as a valid version, due to existing test cases.
> fix: Correctly compare extension versions

- internal/featureflags/temporary.go
Yes, configurations downloaded with the `download` command contain `insertAfter` parameters on ordered Settings 2.0 configurations.
> set default value for MONACO_FEAT_PERSIST_SETTINGS_ORDER to true

- cmd/monaco/deploy/deploy.go
- cmd/monaco/integrationtest/v2/all_configs_integration_test.go
- cmd/monaco/integrationtest/v2/supportarchive_report_test.go
- internal/environment/get_env_value.go
- internal/testutils/afero_test_utils.go
- pkg/deploy/deploy.go
- pkg/deploy/deploy_test.go
- pkg/deploy/preload.go
- pkg/deploy/preload_test.go
- pkg/report/detailer.go
- pkg/report/detailer_test.go
- pkg/report/exports_test.go
- pkg/report/record.go
- pkg/report/reporter.go
- pkg/report/reporter_test.go
This PR adds optional basic deployment reports.
To enable the feature set the environment variable `MONACO_DEPLOYMENT_REPORT_FILENAME` with the report filename Monaco should create. Leaving the environment variable empty or unset disables the feature.
When enabled, Monaco writes a report record for each regular config it attempts to deploy. Each record is written as a JSON object on its own line, collectively [in the JSON Lines format](https://jsonlines.org/). An example line is:
```json
{"type":"DEPLOY","time":"2024-10-23T12:40:22Z","config":{"project":"test","type":"dashboard","configId":"my-dashboard3"},"state":"SKIPPED","details":[{"type":"INFO","msg":"skipped"}]}
```
which when pretty formatted looks like this:
```json
{
"type": "DEPLOY",
"time": "2024-10-23T12:40:22Z",
"config": { …
```
> feat: Deployment report

- CONTRIBUTING.md
- cmd/monaco/delete/delete.go
- cmd/monaco/deploy/deploy.go
- cmd/monaco/deploy/deploy_test.go
- cmd/monaco/download/download_configs.go
- cmd/monaco/download/download_configs_test.go
- cmd/monaco/download/download_integration_test.go
- cmd/monaco/download/downloadopts.go
- cmd/monaco/dynatrace/dynatrace.go
- cmd/monaco/dynatrace/dynatrace_test.go
- cmd/monaco/integrationtest/integration_test_utils.go
- cmd/monaco/integrationtest/v2/diff_project_diff_ext_id_test.go
- cmd/monaco/purge/purge.go
- pkg/client/clientset.go
- pkg/client/clientset_test.go
- pkg/client/dtclient/config_client.go
- pkg/converter/converter.go
- pkg/converter/converter_test.go
- pkg/delete/delete.go
- pkg/download/download_writer_test.go
- pkg/manifest/internal/persistence/manifest_persitence.go
- pkg/manifest/loader/account.go
- pkg/manifest/loader/manifest_loader.go
- pkg/manifest/loader/manifest_loader_test.go
- pkg/manifest/manifest.go
- pkg/manifest/manifest_test.go
- pkg/manifest/writer/manifest_writer.go
- pkg/manifest/writer/manifest_writer_test.go
- pkg/persistence/config/loader/config_loader_test.go
- pkg/project/v2/project_loader_test.go
Enable the possibility to only define oAuth credentials and be able to work with oAuth API's. Only validate the token if it's needed for an API.
Valid manifest:
```
manifestVersion: 1.0
projects:
- name: only_3rdgen_project
environmentGroups:
- name: default
environments:
- name: platform_env
url:
type: environment
value: URL
auth:
oAuth:
clientId:
name: OAUTH_CLIENT_ID
clientSecret:
name: OAUTH_CLIENT_SECRET
```
Some refactoring around the clientset creation has been done.
A user can now define a manifest with only oAuth credentials for APIs that use oAuth for authentication. As a follow-up, the Settings API will be updated to allow its usage with oAuth-only credentials.
> feat: Allow empty token for only oauth client apis

- cmd/monaco/account/deploy.go
When `monaco account deploy -a <account> -p <project>` is executed and the `<project>` is not existing the error message prints:
`required project "<account>" was not found in manifest "manifest.yaml"`
Instead of:
`required project "<project>" was not found in manifest "manifest.yaml"`
> fix: fix error message on account deploy

- pkg/download/dependency_resolution/dependency_resolution.go
- pkg/download/dependency_resolution/dependency_resolution_test.go
- pkg/download/dependency_resolution/resolver/ahocorasick_dep_resolver.go
- pkg/download/dependency_resolution/resolver/basic_dep_resolver.go
- pkg/download/dependency_resolution/resolver/shared.go
Dashboard share settings are a bit special. One dashboard always has exactly 1 dashboard-share config connected to it. This share setting has the same ID as the dashboard itself. This is where the issues arise.
Dashboards can't depend on other dashboards, as we ignore those references. The references are usually only included in the markdown of the tiles, not the dashboards themselves. Since the dashboard share settings have the same ID as the dashboards, what means that instead of ignoring `dashboard->dashboard` references, we get unwanted `dashboard->dashboard-share-setting` references. What is more, the references are not within the same config, but some random dashboards can suddenly depend on the dashboard-share-settings.
Since dashboard-share settings do depend on their parent …
> fix(dependency_resolution): Dashboard-Share-Settings can no longer be referenced from dashboards.

- cmd/monaco/integrationtest/v2/test-resources/delete-test-configs/project/workflow.json
This PR fixes E2E tests by removing an `actor` field that is assigned an empty string from a workflow definition that is used in our delete E2E tests. Most likely this is important because of a change in the underlying Automation API.
> fix: Remove `actor` field in delete E2E test workflow

- pkg/deploy/preload.go
- pkg/deploy/preload_test.go
Skip caching for configs of type classic and setting that have the skip parameter set to true. As the configs won't be deployed there is no need to chache them. With this being skipped, we also prevent performance degradation compared to the previous version.
> Consider Skip parameter during preload caching

- cmd/monaco/delete/delete.go
- cmd/monaco/deploy/deploy.go
- cmd/monaco/download/download_configs.go
- cmd/monaco/download/download_configs_test.go
- cmd/monaco/download/download_integration_test.go
- cmd/monaco/dynatrace/dynatrace.go
- cmd/monaco/integrationtest/integration_test_utils.go
- cmd/monaco/integrationtest/v2/diff_project_diff_ext_id_test.go
- cmd/monaco/integrationtest/v2/dry-run_test.go
- cmd/monaco/purge/purge.go
- pkg/client/clientset.go
- pkg/client/clientset_test.go
- pkg/client/dummy_clientset.go
- pkg/delete/delete.go
- pkg/delete/delete_test.go
- pkg/deploy/deploy.go
- pkg/deploy/deploy_test.go
- pkg/deploy/internal/automation/automation.go
- pkg/deploy/internal/automation/automation_test.go
- pkg/deploy/internal/bucket/bucket.go
- pkg/deploy/internal/document/document.go
- pkg/deploy/internal/document/document_test.go
- pkg/deploy/internal/openpipeline/openpipeline.go
- pkg/deploy/internal/setting/setting_test.go
- pkg/deploy/preload.go
- pkg/deploy/preload_test.go
- pkg/download/classic/download_test.go
- pkg/download/settings/download_test.go
This PR ensures that no requests are sent to a Dynatrace environment during a dry run by switching to a no-op client early during deployment.
Furthermore, this PR tries to move towards the goal of only having one sort of "clientset" in Monaco, by removing those in from the delete and deploy packages. It also finishes splitting the old DTClient into a classic client and a settings client.
> fix: Ensure environment is not accessed during a dry run

- .github/workflows/end-to-end-test.yml
Add a first version of Dynatrace notification for nightly E2E test failure via a curl at the end of the workflow
> chore: Add Dynatrace notification for nightly E2E test failure

- cmd/monaco/deploy/deploy.go
- cmd/monaco/deploy/deploy_test.go
This PR adopts the authentication check for every configuration entry in a file, not just the first one.
> fix: check every config entry in a file

- cmd/monaco/deploy/deploy.go
- cmd/monaco/deploy/deploy_test.go
- cmd/monaco/download/download_configs.go
- cmd/monaco/download/download_configs_test.go
This PR removes the validation check for Settings API in download and deploy to fail if Token is not set. This allows to use OAuth credentials with Settings API.
> Allow Settings API with OAuth credentials

- internal/environment/get_env_value.go
- pkg/deploy/deploy.go
This PR adds a opt-in limit on concurrent deployments: To enable it, set `MONACO_CONCURRENT_DEPLOYMENTS` to a non-zero value.
The limiter can help prevent excessive resource usage in scenarios where Monaco would otherwise start many deployments.
> feat: Limit max concurrent deployments

- go.mod
- go.sum
The core library has recently been updated to automatically retry OpenPipeline configuration updates when a version conflict occurs. Let's use this in Monaco.
> chore: Update core library

- pkg/client/dtclient/settings_client.go
- pkg/client/dtclient/settings_client_test.go
With the current matching algorithm, we can only support non-nested constraints. With this PR, recursive matching is introduced, and so we can apply even nested constraints.
> fix: Support deeper unique settings properties

- pkg/client/clientset.go
As suggested in [PR review](https://github.com/Dynatrace/dynatrace-configuration-as-code/pull/1647#discussion_r1877947881), let's remove comments that don't bring any useful value.
> refactor: delete comments from ClientSet

- cmd/monaco/generate/deletefile/deletefile.go
- pkg/deploy/deploy.go
- pkg/deploy/deploy_test.go
- pkg/deploy/internal/classic/validation.go
- pkg/deploy/internal/classic/validation_test.go
- pkg/deploy/internal/setting/validation.go
- pkg/deploy/internal/setting/validation_test.go
- pkg/deploy/internal/validate/validate.go
- pkg/deploy/internal/validate/validate_test.go
- pkg/project/v2/project.go
- pkg/project/v2/project_test.go
This PR introduces a new pre-deploy validator, that verifies that `insertAfter` references reference the correct kind of setting. Referenced settings now have to  have the same 1) schema, 2) scope, and 3) environment.
These checks can only be performed when this information is static (ValueParameters), so this limit exists. We could also introduce it during deployment when the values are resolved, but at that time, the API already returns an error, so I skipped it (IMO it would only introduce more issues).
This PR requires some minor refactorings to work (split into their own commits):
* Validator requires access to project, so the interface is extended
* `GetConfigFor` -> Added the environment where the Config should be looked for. This seems to have been a bug, as the returned config …
> fix: `insertAfter` references must have the same scope and type as the source

- go.mod
- go.sum
- internal/featureflags/temporary.go
- pkg/config/types.go
- pkg/persistence/config/internal/persistence/type_definition.go
- pkg/persistence/config/loader/config_loader_test.go
- pkg/persistence/config/writer/config_writer_test.go
The name of the feature is `segment`. With this PR, it is aligned with it.
> refactor: Rename `filersegments` -> `segments`

- pkg/deploy/deploy.go
The validation if the configs are valid happened after the deployment-graph was build and the caches were preloaded. This does not make sense, so this change moves the validation up.
> feat: Validation should happen before first steps in deploy

- cmd/monaco/integrationtest/v2/settings_integration_test.go
- cmd/monaco/integrationtest/v2/test-resources/settings-ordered/cross-project-reference/manifest.yaml
- cmd/monaco/integrationtest/v2/test-resources/settings-ordered/cross-project-reference/source/builtincontainer.monitoring-rule/config.yaml
- cmd/monaco/integrationtest/v2/test-resources/settings-ordered/cross-project-reference/source/builtincontainer.monitoring-rule/template.json
- cmd/monaco/integrationtest/v2/test-resources/settings-ordered/cross-project-reference/target/builtincontainer.monitoring-rule/config.yaml
- cmd/monaco/integrationtest/v2/test-resources/settings-ordered/cross-project-reference/target/builtincontainer.monitoring-rule/template.json
- pkg/deploy/internal/classic/validation.go
- pkg/deploy/internal/classic/validation_test.go
- pkg/deploy/internal/setting/validation.go
- pkg/deploy/internal/setting/validation_test.go
- pkg/deploy/internal/validate/validate.go
We did not take other projects into account when resolving the reference.
To ensure this is not an issue in the future, an e2e test is also added.
> fix: `insertAfter` can reference other Monaco projects

- pkg/client/clientset.go
- pkg/delete/delete.go
- pkg/delete/delete_test.go
- pkg/delete/internal/segment/delete.go
- pkg/delete/internal/segment/delete_test.go
- pkg/persistence/config/writer/config_writer_test.go
With these changes, delete functionality for segments is supported. To declare `segment` config for delete, in `delete.yaml` file add an entry like this for indirect reference:
```
- type: segment
project: my-project
id: monaco-config-id
```
or for direct reference like next:
```
- type: segment
objectId: origin-object-ID
```
> feat(segments): delete functionality for `segments`

- cmd/monaco/generate/deletefile/deletefile_test.go
- cmd/monaco/generate/deletefile/test-resources/project/segment/config.yaml
- cmd/monaco/generate/deletefile/test-resources/project/segment/segment.json
The generate command works as it should for the new endpoint `segment`. With this PR new tests are added to ensure functionality
> test(segment): add tests for generate command for segments

- cmd/monaco/download/download_command.go
- cmd/monaco/download/download_configs.go
- cmd/monaco/generate/deletefile/deletefile_test.go
- cmd/monaco/integrationtest/v2/all_configs_integration_test.go
- cmd/monaco/integrationtest/v2/documents_integration_test.go
- cmd/monaco/integrationtest/v2/dry-run_test.go
- internal/featureflags/temporary.go
- internal/log/log.go
- pkg/client/classicheartbeat/client.go
- pkg/client/metadata/metadata.go
- pkg/client/version/version_check.go
- pkg/delete/delete.go
- pkg/delete/delete_test.go
- pkg/deploy/deploy.go
- pkg/persistence/config/internal/persistence/type_definition.go
- pkg/persistence/config/loader/config_loader_test.go
- pkg/persistence/config/writer/config_writer_test.go
This PR removes `MONACO_FEAT_DOCUMENTS` and `MONACO_FEAT_DELETE_DOCUMENTS` feature flags as the features are now stable.
> refactor: Remove documents feature flags

- pkg/download/dependency_resolution/dependency_resolution_test.go
- pkg/download/dependency_resolution/resolver/ahocorasick_dep_resolver.go
- pkg/download/dependency_resolution/resolver/basic_dep_resolver.go
This PR ensures that no reference parameter is added to a config if the parameter is unused in the template.
Due to the way the code currently works, the fix is made in both dependency resolvers. This could maybe be improved in a follow up PR, however changes to this code have performance implications and thus should be measured.
A test is also added demonstrating the correct behavior.
In practice the simplest way to demonstrate it is to create a classic config with a name that occurs often in configs out of context. A good example is a network zone with the name `_`. 
This string occurs often in templates however as a false positive, which is detected via a regex:
https://github.com/Dynatrace/dynatrace-configuration-as-code/blob/329021241d62ed9f90bf6421982611aeca7c51da/pkg/download/depend …
> fix: Skip reference parameter creation if parameter is unused in template

- pkg/persistence/account/loader/load.go
- pkg/persistence/account/loader/transform.go
- pkg/persistence/account/loader/validate.go
Found while investigating #1666, this PR:
- reduces the complexity of `load(...)`
- ensures file name is included in errors while loading account resources
- corrects two typos in error messages
- improves error messages
- refactors code for increased readability
> feat: Improve account loading errors

- internal/featureflags/temporary.go
- pkg/account/resources.go
- pkg/persistence/account/internal/types/types.go
- pkg/persistence/account/loader/load.go
- pkg/persistence/account/loader/load_test.go
- pkg/persistence/account/loader/testdata/configs-accounts-mixed.yaml
- pkg/persistence/account/loader/testdata/duplicate-group.yaml
- pkg/persistence/account/loader/testdata/duplicate-service-user.yaml
- pkg/persistence/account/loader/testdata/multi-with-configs/a/b/c/d/d.yaml
- pkg/persistence/account/loader/testdata/multi-with-delete-file/a/b/c/d/d.yaml
- pkg/persistence/account/loader/testdata/multi/a/b/c/d/d.yaml
- pkg/persistence/account/loader/testdata/partial-service-user.yaml
- pkg/persistence/account/loader/testdata/valid-origin-object-id.yaml
- pkg/persistence/account/loader/testdata/valid.yaml
- pkg/persistence/account/loader/transform.go
- pkg/persistence/account/loader/validate.go
- pkg/persistence/account/writer/writer.go
- pkg/persistence/account/writer/writer_test.go
This PR adds persistence for account service users.
While the service users feature is in development, enable `MONACO_FEAT_SERVICE_USERS` feature flag.
> feat: Service user persistence

- cmd/monaco/deploy/deploy.go
- cmd/monaco/download/download_configs.go
- cmd/monaco/download/download_integration_test.go
- cmd/monaco/download/test-resources/integration-test-go-templating-expressions-are-escaped/settings/__SCHEMAS.json
- cmd/monaco/download/test-resources/integration-test-go-templating-expressions-are-escaped/settings/objects.json
- internal/template/escape.go
- internal/template/escape_test.go
- pkg/download/automation/download.go
- pkg/project/v2/project.go
- pkg/project/v2/project_test.go
There are still occurances in some configs that contain `{{` and `}}` that clash with the Go templating expressions.
This PR escapes all those occurances except for classic APIs and Automation resources.
> fix(download): Escape Go Templating

- cmd/monaco/download/download_configs.go
- go.mod
- go.sum
- pkg/client/clientset.go
- pkg/client/dummy_clientset.go
- pkg/client/test_clientset.go
- pkg/delete/delete_test.go
- pkg/deploy/deploy.go
- pkg/deploy/deploy_test.go
- pkg/deploy/internal/segment/segment.go
- pkg/deploy/internal/segment/segment_test.go
This PR adds support for the `segments` API in monaco.
Follow-up is planned to move the logic of adding `uid` and `owner` to the lib.
> feat(segments): deploy support for `segments` API

- cmd/monaco/integrationtest/v2/integration_test_utils.go
- cmd/monaco/integrationtest/v2/references_test.go
- cmd/monaco/integrationtest/v2/test-resources/string-references/manifest.yaml
- cmd/monaco/integrationtest/v2/test-resources/string-references/string-references/builtinnetworkzones/config.yaml
- cmd/monaco/integrationtest/v2/test-resources/string-references/string-references/builtinnetworkzones/network-zones-enabled.json
- cmd/monaco/integrationtest/v2/test-resources/string-references/string-references/dashboards/config.yaml
- cmd/monaco/integrationtest/v2/test-resources/string-references/string-references/dashboards/dashboard.json
- cmd/monaco/integrationtest/v2/test-resources/string-references/string-references/network-zones/config.yaml
- cmd/monaco/integrationtest/v2/test-resources/string-references/string-references/network-zones/zone.json
- internal/featureflags/temporary.go
- internal/json/apply.go
- internal/json/apply_test.go
- pkg/download/dependency_resolution/resolver/shared.go
This PR adds a feature that, when enabled via the `MONACO_FEAT_ONLY_CREATE_REFERENCES_IN_STRINGS` feature flag, only creates references in string values within the JSON templates.
> feat: Create references only in string values in JSON templates

- pkg/download/classic/download.go
- pkg/download/classic/download_test.go
In some scenarios, we have observed an environment may list multiple configurations for download with the same ID. As Monaco cannot distinguish between these, this PR adds a warning and removes the duplicate.
> fix: Skip duplicate downloaded values

- cmd/monaco/account/download.go
- cmd/monaco/account/download_command.go
- cmd/monaco/delete/command.go
- cmd/monaco/delete/delete.go
- cmd/monaco/deploy/command.go
- cmd/monaco/deploy/deploy.go
- cmd/monaco/deploy/deploy_test.go
- cmd/monaco/download/download.go
- cmd/monaco/download/download_command.go
- cmd/monaco/download/download_command_test.go
- cmd/monaco/download/download_configs.go
- cmd/monaco/dynatrace/dynatrace.go
- cmd/monaco/dynatrace/dynatrace_test.go
- cmd/monaco/integrationtest/utils/monaco/cmd.go
- cmd/monaco/main.go
- cmd/monaco/purge/command.go
- cmd/monaco/purge/purge.go
- cmd/monaco/runner/runner.go
This PR fixes the context flow in `cmd` package
> refactor(cmd): ensure to use top-level context in production code

- cmd/monaco/account/deploy.go
- cmd/monaco/account/download.go
- cmd/monaco/delete/delete.go
- cmd/monaco/download/download_configs.go
- cmd/monaco/dynatrace/dynatrace.go
- cmd/monaco/integrationtest/account/runner.go
- cmd/monaco/integrationtest/integration_test_utils.go
- cmd/monaco/integrationtest/utils/monaco/cmd.go
- cmd/monaco/integrationtest/v2/diff_project_diff_ext_id_test.go
- cmd/monaco/main.go
- cmd/monaco/purge/purge.go
- cmd/monaco/runner/runner.go
- cmd/monaco/support/archive.go
- cmd/monaco/supportarchive/supportarchive.go
- cmd/monaco/supportarchive/supportarchive_test.go
- pkg/client/clientset.go
- pkg/client/clientset_test.go
Since recently, `context.Context` has not been introduced into Monaco CLI. For keeping information that support-archive is needed, the global variable `SupportArchive` has been used.
This PR makes information available via the `context.Context`.
Instead of the solution where printing log files is done via the defer function, `cobra.OnFinalize` option is used.
> refactor: eliminate support archive global variable `SupportArchive`

- .ci/jenkins/tools/ko.groovy
- Makefile
This change allows us to use a different proxy instead of querying docker directly, potentially breaking the pipeline because of "You have reached your pull rate limit".
By default, it still pulls from the docker-hub
Documentation about ko: https://ko.build/configuration/
no
> ci: Allow to overwrite the ko base image path

- cmd/monaco/download/download_command.go
- cmd/monaco/download/download_configs.go
- cmd/monaco/download/download_configs_test.go
- cmd/monaco/download/downloadopts.go
- pkg/download/slo/download.go
- pkg/download/slo/download_test.go
Introduces the download command for SLOs
> feat(SLO): download support for SLO API

- go.mod
- go.sum
- pkg/account/downloader/downloader.go
- pkg/account/downloader/downloader_test.go
- pkg/account/downloader/http_client.go
- pkg/account/downloader/internal/http/client.go
- pkg/account/downloader/service_users.go
This PR adds functionality to download service-users.
> feat: Download service users

- cmd/monaco/integrationtest/v2/supportarchive_report_test.go
- cmd/monaco/supportarchive/supportarchive.go
It adds the generated deployment report if enabled to the archive
> feat(support-archive): add deployment report to archive

- pkg/client/clientset.go
- pkg/client/dummy_clientset.go
This PR removes unnecessary aliases for import in `pkg/client`. In case where named imports are necessary, it rename it in wah they are always same.
> refactor: remove and rename custom package name for import

- cmd/monaco/deploy/deploy_test.go
- pkg/deploy/deploy_test.go
- pkg/deploy/internal/automation/automation_test.go
- pkg/deploy/internal/bucket/bucket_test.go
- pkg/deploy/internal/classic/classic_test.go
- pkg/deploy/internal/document/document_test.go
- pkg/deploy/internal/openpipeline/openpipeline_test.go
- pkg/deploy/internal/segment/segment_test.go
- pkg/deploy/internal/setting/setting_test.go
- pkg/deploy/internal/slo/slo_test.go
- pkg/deploy/preload_test.go
Passes the correct context to deploy related functions
> chore(deploy): pass right context

- pkg/client/clientset.go
- pkg/client/clientset_test.go
- pkg/client/dtclient/config_client_test.go
- pkg/client/dtclient/extension_upload_test.go
- pkg/client/dtclient/retry_test.go
- pkg/client/dtclient/settings_client.go
- pkg/client/dtclient/settings_client_test.go
- pkg/client/metadata/metadata_test.go
- pkg/client/version/version_check_test.go
Passes the correct context to client (not core) related functions
> chore(client): pass right context

- cmd/monaco/integrationtest/assert.go
- cmd/monaco/integrationtest/integration_test_utils.go
- cmd/monaco/integrationtest/v2/delete_integration_test.go
- cmd/monaco/integrationtest/v2/diff_project_diff_ext_id_test.go
- cmd/monaco/integrationtest/v2/documents_integration_test.go
- cmd/monaco/integrationtest/v2/non_unique_names_e2e_test.go
- cmd/monaco/integrationtest/v2/references_test.go
- cmd/monaco/integrationtest/v2/scoped_configs_test.go
- cmd/monaco/integrationtest/v2/segments_integration_test.go
- cmd/monaco/integrationtest/v2/settings_integration_test.go
- cmd/monaco/integrationtest/v2/skip_e2e_test.go
Passes the correct context in integration test related functions
> chore(integration): pass right context

- pkg/client/clientset.go
- pkg/deploy/deploy.go
- pkg/deploy/internal/setting/setting.go
- pkg/deploy/internal/setting/setting_test.go
- pkg/persistence/config/loader/config_entry_loader.go
- pkg/persistence/config/loader/config_loader_test.go
Allows defining value, environment, and other values.\
Additionally moves the `insertAfter` fetching into Deploy.\
Adds minor change to add parameters to a interface method, as they were not clear.
This is the first PR of two. 
1) This one allows users to define more than just references while 
2) the next one will allow users to define magic values to insert at the begin and end of a list.
Yes, users will be able to define more than just References in their `insertAfter` settings.
> feat(settings): Allow insertAfter to contain more than just references.

- pkg/delete/internal/segment/delete.go
- pkg/delete/internal/segment/delete_test.go
This PR corrects a few typos and aligned names with go standard
> refactor(segment): fix some typos and formatting

- pkg/client/clientset.go
- pkg/client/dummy_clientset.go
- pkg/client/test_clientset.go
- pkg/delete/delete.go
- pkg/delete/delete_test.go
- pkg/delete/internal/slo/delete.go
- pkg/delete/internal/slo/delete_test.go
This PR brings delete functionality for SLO (`type: slo-v2`). To delete config in `delete.yaml` file add an entry like next for indirect reference:
```
- type: slo-v2
project: my-project
id: monaco-config-id
```
or for direct reference like next:
```
- type: slo-v2
objectId: origin-object-ID
```
> feat(slo-v2): add delete functionality for SLO

- pkg/download/bucket/download.go
- pkg/download/internal/templatetools/template.go
- pkg/download/internal/templatetools/template_test.go
- pkg/download/openpipeline/download.go
- pkg/download/segment/download.go
- pkg/download/slo/download.go
This PR brings small improvement which enables deleting multiple entries at once.
Instead current
```GO
object.Delete("key1")
object.Delete("key2")
```
it is possible to: 
```GO
object.Delete("key1", "key2")
```
> refactor(JSONObject): extend JSONObject.Delete() to delete multiple entries

- cmd/monaco/integrationtest/v2/documents_integration_test.go
- cmd/monaco/integrationtest/v2/test-resources/integration-documents/project/document-launchpad/config.yaml
This PR tightens the check for created launchpads in `cmd/monaco/integrationtest/v2/documents_integration_test.go`.
> test: Improve check for launchpad creation in documents integration test

- cmd/monaco/integrationtest/v2/supportarchive_report_test.go
- cmd/monaco/main.go
- cmd/monaco/runner/runner.go
- internal/featureflags/permanent.go
- internal/log/log.go
- internal/log/log_test.go
- internal/log/memstatlog.go
The memstat file is now only logged if the `MONACO_LOG_MEM_STATS` FF is enabled, AND either the support archive or file logging is activated.
Additionally, we refactored the code to introduce more error checking.
> fix: Introduce FF to enable/disable logging memory statistics

- cmd/monaco/integrationtest/v2/automation_integration_test.go
- cmd/monaco/integrationtest/v2/dry-run_test.go
- cmd/monaco/integrationtest/v2/integration_test_utils.go
- cmd/monaco/integrationtest/v2/references_test.go
- cmd/monaco/integrationtest/v2/scope_paramter_integration_test.go
This PR introduces small changes in the definition of e2e tests, which, in theory, should result in less error-prone coding.
> test: use FeatureFlag instead of string to define wanted FF

- cmd/monaco/integrationtest/rewrite-test-resources/given/rewrite-test-config.yaml
- cmd/monaco/integrationtest/rewrite-test-resources/want/expected-both-postfix.yaml
- cmd/monaco/integrationtest/rewrite-test-resources/want/expected-id-postfix.yaml
- cmd/monaco/integrationtest/rewrite-test-resources/want/expected-name-full.yaml
- cmd/monaco/integrationtest/rewrite-test-resources/want/expected-name-postfix.yaml
- cmd/monaco/integrationtest/rewrite_functions.go
- cmd/monaco/integrationtest/rewrite_functions_test.go
This PR updates name and id rewrite functions to skip lines ending with `#monaco-test:no-replace`
> test: Both name and id rewrite functions should skip lines ending with `#monaco-test:no-replace`

- cmd/monaco/integrationtest/v2/settings_integration_test.go
- cmd/monaco/integrationtest/v2/test-resources/settings-ordered/insert-position/both-back-and-front-are-set/config.yaml
- cmd/monaco/integrationtest/v2/test-resources/settings-ordered/insert-position/both-back-and-front-are-set/url-sampling.json
- cmd/monaco/integrationtest/v2/test-resources/settings-ordered/insert-position/insert-after-not-set/config.yaml
- cmd/monaco/integrationtest/v2/test-resources/settings-ordered/insert-position/insert-after-not-set/url-sampling.json
- cmd/monaco/integrationtest/v2/test-resources/settings-ordered/insert-position/insert-after-set-to-back/config.yaml
- cmd/monaco/integrationtest/v2/test-resources/settings-ordered/insert-position/insert-after-set-to-back/url-sampling.json
- cmd/monaco/integrationtest/v2/test-resources/settings-ordered/insert-position/insert-after-set-to-front/config.yaml
- cmd/monaco/integrationtest/v2/test-resources/settings-ordered/insert-position/insert-after-set-to-front/url-sampling.json
- cmd/monaco/integrationtest/v2/test-resources/settings-ordered/insert-position/manifest.yaml
- pkg/client/dtclient/settings_client.go
- pkg/client/dtclient/settings_client_test.go
- pkg/deploy/internal/setting/setting.go
- pkg/deploy/internal/setting/setting_test.go
Followup to #1714
This change allows users to put settings objects to the very front/back of the list. 
To do that, they must specify either `FRONT` or `BACK` in their `insertAfter` configuration.
> feat(settings): Insert at the very front and back

- pkg/delete/delete.go
This PR skips attempting to delete automation resources when there are none specified for deletion.
While attempting deletion is normally not really harmful, it can result in spurious log messages, such as:
```
2025-02-27T15:08:19+01:00	warn	Skipped deletion of 0 Automation configuration(s) of type "workflow" as API client was unavailable.
2025-02-27T15:08:19+01:00	warn	Skipped deletion of 0 Automation configuration(s) of type "scheduling-rule" as API client was unavailable.
2025-02-27T15:08:19+01:00	warn	Skipped deletion of 0 Automation configuration(s) of type "business-calendar" as API client was unavailable.
```
visible during `TestIntegrationSettings` when deleting with the delete file:
```
delete:
- project: project
type: builtin:tags.auto-tagging
id: …
```
> fix: Skip unneeded automation deletes when not required

- cmd/monaco/integrationtest/v2/supportarchive_report_test.go
- cmd/monaco/supportarchive/supportarchive.go
This PR only includes the memstat log in the support archive if the feature flag is enabled because otherwise it doesnt exist.
This fixes the error:
```
2025-02-27T10:22:48+01:00	error	Encountered error creating support archive. Archive may be missing or incomplete: encountered multiple errors: [ unable to add .logs/20250227-102246-memstat.log file to archive support-archive-20250227-102246.zip: open .logs/20250227-102246-memstat.log: no such file or directory ]
```
> fix: Support archive should only include memstat log if feature flag enabled

- cmd/monaco/integrationtest/v2/config_restore_e2e_test.go
- cmd/monaco/integrationtest/v2/delete_integration_test.go
- cmd/monaco/integrationtest/v2/integration_test_utils.go
- cmd/monaco/integrationtest/v2/non_unique_names_e2e_test.go
- cmd/monaco/integrationtest/v2/settings_integration_test.go
Since the t.Context() is canceled before t.Cleanup registered functions are called, we now use defer instead.
> test:  Use defer instead of t.Cleanup to have a valid context

- cmd/monaco/integrationtest/v2/test-resources/integration-automation/project/common/script.js
- cmd/monaco/integrationtest/v2/test-resources/integration-automation/project/workflow/config.yaml
- pkg/config/parameter/file/file.go
- pkg/config/parameter/file/file_test.go
- pkg/config/parameter/parameters.go
- pkg/persistence/config/loader/parameters.go
This PR allows a file parameter to specify a template file using a relative path. This means the following is now accepted:
```
parameters:
javascript:
type: file
path: ../common/script.js
```
where for example, the `config.yaml` is `./workflow/config.yaml` and the referenced `/script.js` is `../common/script.js`
> fix: Allow relative paths in file parameters

- cmd/monaco/integrationtest/v2/delete_integration_test.go
This PR fixes current issues with `TestDeleteSubPathAPIConfigurations` by waiting after the deployment, preventing us from receiving an 500 Internal server error.
> test: Improve `TestDeleteSubPathAPIConfigurations`

- pkg/client/clientset.go
- pkg/client/dtclient/dummy_settings_client.go
- pkg/client/dtclient/settings_client.go
- pkg/client/dtclient/settings_client_test.go
Introduction of `AccessControl` interface and implementation to the `SettingsClient`.
```
GetPermission(context.Context, string) (dtclient.PermissionObject, error)
UpsertPermission(context.Context, string, dtclient.PermissionObject) error
DeletePermission(context.Context, string) error
```
I decided for an Upsert over Create and Update, since the handling of both is 99% same.
> feat: extend `SettingsClient` with `AccessControl`

- .ci/releasePipeline.groovy
- go.mod
Update Go to v1.24.1 to *maybe* fix a deadlock that sometimes appears in our e2e tests.
Updates: https://github.com/golang/go/issues?q=milestone%3AGo1.24.1+label%3ACherryPickApproved
> chore: Update Go to 1.24.1

- cmd/monaco/integrationtest/v2/loading-report_test.go
- pkg/manifest/loader/manifest_loader.go
Currently `ManifestLoaderError` puts the file path first, then the reason. This PR reverse that to align with other errors. It first puts the reason, then the path. One E2E test is updated because now the first letter of the reason will be uppercase.
> fix: `ManifestLoaderError` should put reason first

- CONTRIBUTING.md
Some links in CONTRIBUTING.md pointed to the organization "dynatrace-oss" instead of "dynatrace" and were essentially broken. They are now corrected.
NONE
> docs: fixes broken links in CONTRIBUTING.md

- pkg/account/deployer/client.go
This PR removes a redundant error check from `pkg/account/deployer/client.go`. This was reported by the linter.
> refactor(account): Remove redundant error check

- pkg/account/delete/client.go
- pkg/account/delete/delete.go
This PR updates our `ResourceNotFoundError` custom error type to use value receivers to be inline with our programming style.
> refactor: Custom error types should use value receivers

- cmd/monaco/integrationtest/assert.go
This PR  updates `AssertBucket(...)`  and `getBucketWithRetry(...)` to  expect and react to API errors that are returned via `err`, and specifically 404s, rather than assuming these are still part of the `bucket.Response`. I also updated `getBucketWithRetry(...)` to be non-recursive, as I find that easier to understand. While it is hard to verify, I suspect this may be responsible for the instability of the bucket integration tests.
I am also increasing the number of bucket get retries to `120`, that is 2 minutes, the same value as used by default in the core library. In my experience Buckets can be slow to appear, so this is a good idea.
I will follow up this PR with one for the core removing `func (r Response) AsAPIError() (APIError, bool)` and some associated functions as we no-longer …
> fix: Correctly handle `APIError` in `AssertBucket(...)`

- cmd/monaco/download/download.go
- cmd/monaco/download/download_configs.go
- cmd/monaco/download/download_configs_test.go
- cmd/monaco/download/download_integration_test.go
- pkg/download/download_writer.go
- pkg/download/download_writer_test.go
If a manifest file is used in the monaco download command and the environment url is given via environment variable, the same variable name is present in the manifest file of the download folder, whereas previously only the value was stored.
Currently, if you use the `monaco download` command with a manifest file, and an environment url in this manifest file is defined via an environment variable, the manifest file generated in the download folder will still contain the constant url string instead of an environment variable name.
So, current behavior is:
Manifest file with environment url defined like so:
```url:
type: environment
value: ENVIRONMENT_URL
```
used in `monaco download`, where `ENVIRONMENT_URL=env.url.com`, will lead to a generated manifest file with the following content: …
> fix: correctly save environment urls in downloaded manifest file

- cmd/monaco/integrationtest/v2/delete_integration_test.go
Currently there is some instability being observed in `TestDeleteSubPathAPIConfigurations`. While we wait for a fix in on the API side, we can mitigate the problem by waiting longer for the application to be available. This PR increases the wait time from 10 to 60 seconds.
> test: Increase delay for application availability in `TestDeleteSubPathAPIConfigurations`

- pkg/client/dtclient/settings_client.go
- pkg/client/dtclient/settings_client_test.go
ACL Download of where all-users is not set
Before:
```yaml
configs:
- id: my-id
config:
template: template.json
skip: false
originObjectId:  o-id
type:
settings:
schema: my-schema
schemaVersion: "1"
scope: environment
```
After:
```yaml
configs:
- id: my-id
config:
template: template.json
skip: false
originObjectId:  o-id
type:
settings:
schema: my-schema
schemaVersion: "1"
scope: environment
permissions:
allUsers: none
```
> fix(settings): write "none" ACL if not found

- cmd/monaco/integrationtest/v2/deprecated_configs_produce_user_warnings_e2e_test.go
- cmd/monaco/integrationtest/v2/test-resources/deprecated-configs/manifest.yaml
- cmd/monaco/integrationtest/v2/test-resources/deprecated-configs/project/auto-tag.json
- cmd/monaco/integrationtest/v2/test-resources/deprecated-configs/project/auto-tag.yaml
- pkg/deploy/internal/classic/classic.go
- pkg/deploy/internal/classic/validation.go
- pkg/deploy/internal/validate/validate.go
This PR aims to reduce log output when using deprecated apis. The deprecation warning is shown only once per api instead of for every deployed object.
Let's consider a test scenario with 2 projects where each project deploys 3 auto-tags each, using the deprecated auto-tag type instead of the settings schema.
The log output for the deployment **without the new logging** is as follows:
```
2025-03-24T15:47:32+01:00	info	Projects to be deployed (2):
2025-03-24T15:47:32+01:00	info	  - test
2025-03-24T15:47:32+01:00	info	  - test-2
2025-03-24T15:47:32+01:00	info	Environments to deploy to (1):
2025-03-24T15:47:32+01:00	info	  - platform_env
2025-03-24T15:47:32+01:00	info	Deploying configurations to environment "platform_env"...
2025-03-24T15:47:32+01:00	info	Deploying 6 independent …
```
> chore: Deprecated apis are only logged once.

- go.mod
- go.sum
- internal/featureflags/temporary.go
- internal/idutils/bucketname.go
- internal/idutils/bucketname_test.go
- pkg/client/clientset.go
- pkg/deploy/internal/bucket/bucket.go
This PR adds sanitization of generated bucket names:
- Bucket names are still generated by concatenating project name with the config id: `[projectName]_[configId]`
- Bucket names are sanitized by:
- converting the name to lower case
- removing characters such that the result must match `([a-z])([a-z0-9])([a-z0-9_-])+`
- truncating to a maximum length of 100 characters.
By default this is enabled, however this can be disabled by setting the feature flag `MONACO_SANITIZE_BUCKET_NAMES` to `false`.
Furthermore, it makes sure the generated bucket name is visible in logs and errors by updating several error messages as well as updating the version of the core library used.
> feat: Sanitize bucket names

- cmd/monaco/integrationtest/assert.go
- pkg/client/dtclient/config_client.go
- pkg/client/dtclient/extension_upload.go
- pkg/client/dtclient/settings_client.go
- pkg/delete/internal/automation/delete.go
- pkg/delete/internal/bucket/delete.go
- pkg/delete/internal/classic/delete.go
- pkg/delete/internal/document/delete.go
- pkg/delete/internal/segment/delete.go
- pkg/delete/internal/slo/delete.go
- pkg/deploy/internal/document/document.go
- pkg/deploy/internal/segment/segment.go
- pkg/deploy/internal/slo/slo.go
We recently added a 404 check in the core.
Now I replaced all existing 404 checks with the one from core to reduce code duplication.
> refactor: use isNotFoundError of core lib for 404 checking

- cmd/monaco/download/download_command.go
- cmd/monaco/download/download_configs.go
If OAuth is in use, the cluster version check is not needed, as it will always be supported.
It did not work anyway because a classic endpoint was used for platform.
The following warning log was printed if OAuth was used on download
```
Unable to determine server version "https://xyz.apps.dynatrace.com":  ...
```
now we aren't checking the version for OAuth anymore and the warning message will not be printed.
There are two other places in the code where the version check happens, but these two are using the classic client and not the platform one.
Tests are not added and would require some refactoring. We want to split the command code in the future to not contain any logic, therefore leaving this out atm.
> fix: don't print version warning for OAuth

- pkg/client/dtclient/list.go
- pkg/client/dtclient/settings_client.go
- pkg/client/dtclient/settings_client_test.go
On deploy the settings client retried on 404 (schema not found) when fetching the objects.
This behavior is removed now because:
1. A schema will not be available at some time during deploy, as we don't deploy schemas.
2. The settings client doesn't need to do a custom retry for LIST and can rely on the core client.
The following log line will not appear anymore
```
Retrying failed GET request https://my-tenant.apps.dynatrace.com/platform/classic/environment-api/v2/settings/objects (HTTP 404)
```
> fix(settings): Don't retry on 404 schema not found

- .github/workflows/build-test.yml
The sonar action commit is detected (false positive) by semgrep, therefore ignoring this one.
No
> fix: security false positive for sonar commit

- pkg/client/dtclient/settings_client.go
- pkg/client/dtclient/settings_client_test.go
When deploying a settings object for which the `permissions` property is set, we first check whether the referenced settings schema is enabled for owner-based access control. If it is not, the settings object will not be deployed.
Without this check, we would deploy the settings object, but afterwards fail to alter the permissions (because there are none)
Example log output:
```
2025-04-02T16:45:52+02:00	info	Projects to be deployed (1):
2025-04-02T16:45:52+02:00	info	  - test
2025-04-02T16:45:52+02:00	info	Environments to deploy to (1):
2025-04-02T16:45:52+02:00	info	  - platform_env
2025-04-02T16:45:52+02:00	info	Deploying configurations to environment "platform_env"...
2025-04-02T16:45:52+02:00	info	Deploying 2 independent configuration sets in parallel...
2025-04-02T16:45:52+02:00 …
```
> feat: checking whether schema is acl-enabled before deploy

- pkg/download/settings/download.go
- pkg/download/settings/download_test.go
Accessing the permission map within a go routine is not thread save, therefore re-writing the implementation, to also align with the one in `settings_client.go`
No
> fix(settings): fixed unsafe access during permission load

- pkg/client/dtclient/config_client_test.go
Define `retrySettings` over the test package and reuse them where needed. Prevent slow tests.
Before:
```
=== RUN   Test_getObjectIdIfAlreadyExists/returns_error_if_API_call_fails
2025/04/03 13:53:26 WARN Retrying failed GET request http://127.0.0.1:51943/test/api (HTTP 400)
2025/04/03 13:53:27 WARN Retrying failed GET request http://127.0.0.1:51943/test/api (HTTP 400)
2025/04/03 13:53:28 WARN Retrying failed GET request http://127.0.0.1:51943/test/api (HTTP 400)
2025/04/03 13:53:29 WARN Retrying failed GET request http://127.0.0.1:51943/test/api (HTTP 400)
2025/04/03 13:53:30 WARN Retrying failed GET request http://127.0.0.1:51943/test/api (HTTP 400)
2025/04/03 13:53:31 WARN Retrying failed GET request http://127.0.0.1:51943/test/api (HTTP 400)
2025/04/03 13:53:32 WARN Retrying failed …
```
> fix(test): define test retry setting to increase performance

- cmd/monaco/deploy/deploy.go
- cmd/monaco/download/download_configs.go
- internal/idutils/numeric_id.go
- internal/json/json.go
- internal/log/log.go
- internal/loggers/zap/console.go
- internal/trafficlogs/logger.go
- pkg/account/delete/loader.go
- pkg/account/delete/persistence.go
- pkg/account/deployer/dispatcher.go
- pkg/account/deployer/ids.go
- pkg/account/persistence/internal/types/types.go
- pkg/client/dtclient/list.go
- pkg/client/dtclient/settings_client.go
- pkg/delete/internal/document/delete.go
- pkg/delete/persistence/delete_persistence.go
- pkg/deploy/deploy.go
- pkg/deploy/internal/document/document.go
- pkg/deploy/internal/setting/validation.go
- pkg/download/bucket/download.go
- pkg/download/dependency_resolution/resolver/ahocorasick_dep_resolver.go
- pkg/graph/graph.go
- pkg/manifest/internal/persistence/manifest_persitence.go
- pkg/manifest/loader/manifest_loader.go
- pkg/persistence/config/loader/parameters.go
- pkg/report/detailer.go
- pkg/report/reporter.go
With https://github.com/Dynatrace/dynatrace-configuration-as-code/pull/1842 some new linting errors are reported.
This PR just fixes the new ones, so that it is equal to V1 of golangci-lint
Part of the linting issues were fixed via `golangci-lint run --fix ./...`
NONE
> refactor: address new linting errors

- cmd/monaco/download/download_command.go
- cmd/monaco/download/download_configs.go
- cmd/monaco/download/download_configs_test.go
- cmd/monaco/download/downloadopts.go
Buckets did not have an `--only-buckets` argument for download. Now we are able to only download buckets
Yes. The user is now able to only download buckets
> feat: introduce only-bucket argument

- cmd/monaco/integrationtest/account/resources/all-resources/accounts/service-users.yaml
- cmd/monaco/integrationtest/account/resources/all-resources/delete.yaml
- cmd/monaco/integrationtest/account/resources/deploy-download/add_user/service-users.yaml
- cmd/monaco/integrationtest/account/resources/deploy-download/delete.yaml
- pkg/account/delete/loader.go
- pkg/account/delete/loader_test.go
- pkg/account/delete/persistence.go
- pkg/account/deployer/testdata/accdata.yaml
- pkg/account/deployer/testdata/service-user-with-name.yaml
- pkg/account/deployer/testdata/service-user-with-origin-object-id.yaml
- pkg/account/deployer/testdata/service-users-with-same-name-but-different-origin-object-ids.yaml
- pkg/account/persistence/internal/types/types.go
- pkg/account/persistence/loader/testdata/configs-accounts-mixed.yaml
- pkg/account/persistence/loader/testdata/duplicate-group.yaml
- pkg/account/persistence/loader/testdata/multi-with-configs/a/b/c/d/d.yaml
- pkg/account/persistence/loader/testdata/multi-with-delete-file/a/b/c/d/d.yaml
- pkg/account/persistence/loader/testdata/multi/a/b/c/d/d.yaml
- pkg/account/persistence/loader/testdata/partial-service-user.yaml
- pkg/account/persistence/loader/testdata/service-users-with-different-name-and-same-origin-object-ids.yaml
- pkg/account/persistence/loader/testdata/service-users-with-same-name-and-different-origin-object-ids.yaml
- pkg/account/persistence/loader/testdata/service-users-with-same-name-and-missing-origin-object-id.yaml
- pkg/account/persistence/loader/testdata/service-users-with-same-name-and-no-origin-object-ids.yaml
- pkg/account/persistence/loader/testdata/service-users-with-same-name-and-same-origin-object-ids.yaml
- pkg/account/persistence/loader/testdata/valid-origin-object-id.yaml
- pkg/account/persistence/loader/testdata/valid.yaml
- pkg/account/persistence/writer/writer_test.go
The PR updates account management to use `serviceUser` or `serviceUsers` in account resource and delete YAML files to be consistent with our usage of camel rather than kebab case in Monaco.
> fix: Use `serviceUser` or `serviceUsers` in account resource and delete YAML files

- cmd/monaco/download/download_integration_test.go
- cmd/monaco/download/test-resources/integration-test-go-templating-expressions-are-escaped/schemas/schema.json
- internal/featureflags/temporary.go
- pkg/account/delete/loader_test.go
- pkg/account/downloader/downloader_test.go
This PR enables the `MONACO_FEAT_SERVICE_USERS` feature flag by default, so that service users can be downloaded and deployed  with other account resources.
It also enables the `MONACO_FEAT_ACCESS_CONTROL_SETTINGS` feature flag by default, so that read/write permissions for settings objects can be managed via Monaco for settings schemas which support it.
> feat: Enable `MONACO_FEAT_SERVICE_USERS` and `MONACO_FEAT_ACCESS_CONTROL_SETTINGS` feature flags by default

- .github/workflows/build-lint-test.yml
- sonar-project.properties
This change automatically populates the Sonar `projectVersion` property based on the latest git tag.
> ci: Set proper projectVersion based on current tag

- go.mod
- go.sum
Update to a version of `github.com/dynatrace/dynatrace-configuration-as-code-core` which has `GroupUuid` made optional within `ExternalServiceUserWithGroupUuidDto`.
As this field is not being used, this change has no consequences other than allowing service users with no group uuid set to be deployed.
> chore(account): Update core library to allow service users with no group uuid set to be deployed

- cmd/monaco/deploy/command.go
- pkg/deploy/deploy.go
Removes the global variable and puts limiter into the context
Coverage check may fail because of these two lines inside the `if`
```go
if options.ConcurrentDeploymentsLimiter != nil {
options.ConcurrentDeploymentsLimiter.Acquire()
defer options.ConcurrentDeploymentsLimiter.Release()
}
```
The question is: do we want to test that?
Add a test that just checks if acquire/release was called? how: replace the limiter struct inside the options with an interface and put a stub into the context, so that the call can be checked.
Should we write an integration test for it? how: stubbed clients that don't respond and we check if upserts were called {limitedConcurrentCount} times
No
> refactor: move deployment limiter into context

- pkg/download/segment/download.go
In segment/download.go, openpipeline.Response was referenced instead of segments.Response. This PR fixes this. It didn't really break anything, though, because both are type aliases for api.Response.
NONE
> refactor(download): fixes Response type reference in segment/download.go

- cmd/monaco/download/download_command.go
- cmd/monaco/download/download_command_test.go
- cmd/monaco/download/download_configs.go
- cmd/monaco/download/download_configs_test.go
- cmd/monaco/download/download_integration_test.go
- cmd/monaco/download/downloadopts.go
- cmd/monaco/download/downloadopts_test.go
- cmd/monaco/download/only_options.go
- cmd/monaco/download/only_options_test.go
Restructures the only* check to be less redundant and a new one would not mean touching each one.
The ability is also added to add several only flags, so that e.g., only segments and SLOs can be downloaded.
I also aligned the behavior of the only flags if OAuth is not provided:
- skips with no error if OAuth/token is not given and it's not the only "only" flag provided and errors if it's the only "only" flag
- added the log info that it's downloading a resource to all resources
- added a warning log if configs were skipped due to missing OAuth/token
For now I went with variables and writing them into a map for the only options.
Another option would have been to initialize the map with the only-flags and set that for the bool flag `cmd.Flags().BoolVar(onlyOptions[OnlyBuckets], ...`. …
> refactor(download): improve only checks for download

- cmd/monaco/account/deploy.go
- pkg/account/deployer/deployer.go
This PR makes small changes to the messages created during deployment of account resources:
- Overall account deployment message includes the accounts UUID
- Info messages use `'` to surround names and emails etc.
- Errors include names and emails
This makes it easier to follow what happens during a deployment, particularly as the info messages and error messages may not follow one another sequentially.
> feat(account): Improve account deploy messages

- .github/workflows/build-lint-test.yml
Regarding golangci-lint:
The golangci-lint action is from the maintainers of golangci-lint; it's the suggested way to use golangci-lint, and because of some incidents in the past, Reviewdog should not be used.
Regarding reporting:
Because Sonar does its reporting, we don't need our lint action to report (and fail) an additional time. Therefore, it's enough if the lint report is generated, which is everything Sonar needs. This also adds the ability to ignore specific errors that are reported not to occur again, once ignored.
- Reviewdog is now removed, and the golangci-lint action is used instead.
- The double reporting is gone, and Sonar will only be reporting.
- Using the golangci-lint action.
- Adding an argument not to fail the pipeline if there are any errors.
- Removing the GitHub …
> ci: use golangci-lint and remove double lint reporting

- pkg/download/dependency_resolution/resolver/ahocorasick_dep_resolver_test.go
- pkg/download/dependency_resolution/resolver/basic_dep_resolver_test.go
It adds some tests for the ahocorasick and basic resolver. The tests inside dependency_resolution are actually not detecting the coverage of the resolvers (probably due to different package/folder). Tests are based on the ones of `dependency_resolution_test`. It's basically a subset of `dependency_resolution_test` and the `ahocorasick resolver` uses the same tests as the `basic resolver`.
There is one thing inside `dependency_resolution_test` that I didn't quite understand. Is it intended that the `Dashboards should not be able to reference...` test uses `dashboard-id` as the config ID for `dashboard 1` AND the same id for the `dashboard-setting`?
NO
> test: add tests for dependency resolvers to increase coverage

- cmd/monaco/dynatrace/dynatrace.go
- cmd/monaco/dynatrace/dynatrace_test.go
- pkg/client/apitoken/client.go
- pkg/client/apitoken/client_test.go
For validating a classic client, the cluster version was retrieved in order to check if the connection is actually working.
The downside of this is, that an additional scope (`DataExport`) is needed for this, which is not optimal.
The connection check is now changed to use the token lookup endpoint. This one doesn't require any specific scopes.
`DataExport` is not required anymore but still optional, as this is still needed for checking deprecated cluster versions that are not compatible with settings.
Tested download and upload of the downloaded items without the DataExport token 👍 
- What exactly happens if a settings object is sent to a cluster that is below the suggested cluster version?
- FYI golangci-lint is a false positive
The `DataExport` scope is not required anymore
> refactor: use different endpoint for classic connection check

- cmd/monaco/download/download_configs.go
- cmd/monaco/download/download_configs_test.go
- pkg/resource/automation/download.go
- pkg/resource/bucket/download.go
- pkg/resource/classic/download.go
- pkg/resource/document/download.go
- pkg/resource/openpipeline/download.go
- pkg/resource/segment/download.go
- pkg/resource/settings/download.go
- pkg/resource/slo/download.go
This PR is another step in refactoring the download code to make it easier to extend it for new resource types. 
The core `downloadConfigs` method does not depend on concrete resource types anymore - it only uses `Downloadable`. This also allowed us to get rid of `downloadFn`. 
A `prepareDownloadables` function is introduced, which constructs all the resource APIs, based on the `ClientSet` and the `downloadConfigsOptions`. In `downloadConfigs`, this factory function is called, we iterate over all `Downloadable` instances, call `Download`, and collect and return the resulting configs. This is in contrast to the previous implementation, where constructing the "client" and downloading the configs all happened in one go. The new implementation would allow for parallel downloading, if we'd …
> refactor(download): downloadFn is removed from download_configs.go 

- pkg/deploy/internal/setting/setting.go
Some endpoints/services use a different endpoint to get/validate the buckets, which could result in a "not found" error, even though our data source tells us the bucket is available.
[Related failed pipeline run](https://github.com/Dynatrace/dynatrace-configuration-as-code/actions/runs/14901283390/job/41853568830)
The number of retries until it stops trying to create/update a setting that has a bucket reference.
By increasing the number of retries from 6 to 12
No additional logic was added; just one constant is increased.
A not-found error is less likely to occur when creating settings objects referencing buckets.
> fix(settings): Fix possible bucket not found error due to not updated datasource

- cmd/monaco/download/auth.go
- cmd/monaco/download/download_command.go
- cmd/monaco/download/download_configs.go
- pkg/resource/settings/download.go
- pkg/resource/settings/download_test.go
While working in the cmd/download package, I came across some low-hanging fruits for refactoring. Following the boy scouts rule, I cleaned up a bit.
There are three distinct commits and improvements:
- There was a check in `download_command.go`, which checked whether upload to the same environment was possible. This function was only ever called from `download_configs.go` and felt out-of-place in `download_command.go`. Therefore I moved it.
- The construction of the `auth` struct from `mapToAuth()` is moved to its own file, `auth.go`.
- `makeSettingTypes` was removed, as it is unnecessary to wrap the schema IDs in `SettingsType` structs when the very next operation unpacks them again to `[]string` 
Three separate commits for each improvement
Tests still work, no new tests were added.
It …
> refactor(download): a set of smaller code improvements

- go.mod
- go.sum
- pkg/client/clientset.go
- pkg/client/dummy_clientset.go
- pkg/client/test_clientset.go
- pkg/delete/internal/segment/delete.go
- pkg/delete/internal/segment/delete_test.go
- pkg/deploy/internal/segment/segment.go
- pkg/deploy/internal/segment/segment_test.go
- pkg/resource/segment/download.go
- pkg/resource/segment/download_test.go
This PR updates the core lib version and removes the `segment.Response` from the code base to unify and standardize our responses.
Updated core lib version where `segment.Response` was removed and the `api/clients/segment` was also removed. This change also needed a change in the monaco codebase as `segment.Response` was used throughout the codebase, and is now replaced by `api.Response`.
All unit tests passed, a deployment for segments was done on the command line.
This is a purely technical update that has no effect on users.
> refactor(segment): Update core lib where `api/clients/segments` is removed

- pkg/client/dtclient/retry.go
- pkg/client/dtclient/retry_test.go
- pkg/client/dtclient/settings_client.go
The settings client had its own retry implementation, leading to duplicated code and more maintenance if a change is needed on both ends. Now it's using the retry logic of core and not using a custom one anymore
The settings client now uses the retry mechanism of core instead of having its own.
It's now using the retry functionality of core.
Current tests cover it
It slightly changes the logs but nothing else
> refactor(settings): use request retry logic of core instead of custom one

- CONTRIBUTING.md
Updates the contributing guide to specify what conventional-commit prefixes are available, and when to use which one. 
I started also updating the contribution guide in regard to the "how to run tests" and "how to build monaco" sections, but stopped myself, in case it's worse then before. This is the 2nd commit. If we want to have it in, we can adopt it, otherwise I have no issues in dropping the 2nd commit.
> chore: Update contributing guide about commits

- go.mod
- go.sum
- pkg/client/dtclient/settings_client.go
- pkg/client/dtclient/settings_client_test.go
The code for interacting with the settings object permission API has moved to the core library, such that it can be shared also with the Terraform provider.
The main change is in settings_client.go, where, instead of calling the permission API directly, the permission client of the core library is used.
When creating a new settings client, the nested rest client is also used to create the core lib permission client.
No new functionality was added. Code was moved and the existing tests still pass.
Actually, the existing tests have been improved to be more specific.
NO user impact.
> refactor(settings): settings client uses permission handling from core lib

- cmd/monaco/deploy/command.go
- cmd/monaco/deploy/deploy.go
- cmd/monaco/integrationtest/v2/config_restore_e2e_test.go
- cmd/monaco/main.go
- cmd/monaco/supportarchive/supportarchive.go
- internal/errutils/error_handling.go
- internal/json/json.go
- internal/log/log.go
- pkg/client/dtclient/dummy_config_client.go
- pkg/delete/loader.go
- pkg/deploy/deploy.go
- pkg/deploy/preload.go
- pkg/download/dependency_resolution/resolver/shared.go
- pkg/resource/bucket/download.go
- pkg/resource/settings/download.go
For Golang 1.24, `go vet` reports `printf`-like calls with non-constant format strings and no arguments as these could cause unpredictable behavior. This PR preemptively fixes this.
Furthermore we remove the extra `Error()` method usage that is not required.
This was found while moving to slog for logging, but it is easier to review these changes independently.
- Log calls now use constant format strings.
- Errors are are now converted to strings implicitly, rather than explicitly via `Error()` method.
Typically a small change, e.g.:
- `log.Info(summary)` becomes `log.Info("%s", summary)`
- `log.Info("%s", err.Error())` becomes `log.Info("%s", err)`
Tests are unchanged.
It has no effect on users.
> refactor: Logging should use constant format strings

- pkg/deploy/preload.go
- pkg/report/record.go
- pkg/report/reporter.go
- pkg/report/reporter_test.go
It's not that easy to see/parse report records related to caching.
- A new record type `CACHE` is added.
- This new type is used for caching related records.
By adding a new type and function, and making use of it.
The existing test is extended to include caching events
The generated report uses CACHE now instead of LOAD for caching related records.
Before
`{"type":"LOAD","time":"2025-05-19T13:42:45+02:00","state":"SUCCESS","message":"Cached settings values for schema builtin:tags.auto-tagging"}`
After
`{"type":"CACHE","time":"2025-05-19T13:42:45+02:00","state":"SUCCESS","message":"Cached settings values for schema builtin:tags.auto-tagging"}`
Because we haven't used the `error` property and state before, I decided to keep it the same (warning and message).
> feat(report): Introduce caching record types

- cmd/monaco/completion/completion.go
- cmd/monaco/delete/command.go
- cmd/monaco/delete/delete.go
- cmd/monaco/deploy/deploy.go
- cmd/monaco/deploy/deploy_test.go
- cmd/monaco/deploy/internal/logging/logging.go
- cmd/monaco/download/download_configs.go
- cmd/monaco/dynatrace/dynatrace.go
- cmd/monaco/dynatrace/dynatrace_test.go
- cmd/monaco/generate/dependencygraph/dependencygraph.go
- cmd/monaco/integrationtest/assert.go
- cmd/monaco/integrationtest/v2/delete_integration_test.go
- cmd/monaco/integrationtest/v2/diff_project_diff_ext_id_test.go
- cmd/monaco/integrationtest/v2/documents_integration_test.go
- cmd/monaco/integrationtest/v2/scoped_configs_test.go
- cmd/monaco/integrationtest/v2/segments_integration_test.go
- cmd/monaco/integrationtest/v2/settings_acl_integration_test.go
- cmd/monaco/integrationtest/v2/settings_integration_test.go
- cmd/monaco/integrationtest/v2/skip_e2e_test.go
- cmd/monaco/integrationtest/v2/slo-v2_integration_test.go
- cmd/monaco/purge/purge.go
- pkg/download/download_writer.go
- pkg/manifest/loader/manifest_loader.go
- pkg/manifest/loader/manifest_loader_test.go
- pkg/manifest/manifest.go
- pkg/manifest/manifest_test.go
- pkg/manifest/writer/manifest_writer.go
- pkg/manifest/writer/manifest_writer_test.go
- pkg/project/project_loader.go
- pkg/project/project_loader_test.go
This PR is an alternative to https://github.com/Dynatrace/dynatrace-configuration-as-code/pull/1876 and this time adds all environment and environment group names seen during loading directly to the manifest data structure.
This PR is more robust because `manifest.Environments.SelectedEnvironments` is identical to the current `manifest.Environments`, meaning it avoids the effort of having to explicitly deal with `Skip`. However, a lot of effort had to be invested in updating the tests.
The `Environments` field of `manifest.Manifest` is now a struct of type `manifest.Environments` that holds selected environments as well as the names of all environments and environment groups seen during loading. This extra information will be used …
> feat(manifest): Loaded manifest includes all environment and group names

- cmd/monaco/download/download_configs.go
- pkg/client/clientset.go
- pkg/client/dtclient/settings_client.go
- pkg/client/dtclient/settings_client_test.go
This is essentially about removing (practically) dead code. Dynatrace server version 1.262 is already quite old, and not supported any longer, so there is no reason to check whether the version of the server monaco connects to is lower than 1.262.
The version check for the settings client is removed. Subsequently, also the version field is removed from the settings client, as it is now not needed any longer.
Some now-obsolete tests have been removed. Other tests still work.
If `monaco download` is used with a Dynatrace server of version lower than 1.262, there won't be a warning printed any longer. Until now there was the following warning:
> Uploading Settings 2.0 objects to the same environment is not possible due to your cluster version being below '1.262.0'. Monaco only reliably …
> feat(settings): remove DT server version check

- internal/trafficlogs/logger.go
Support archive tests on Windows weren't working (file used by another process)
Files are now correctly closed.
By closing the file after writing.
Tests on Windows are now working
Potential error while writing the support archive on Windows is fixed
> fix: correctly close request and response log files

- pkg/config/errors/loader_errors.go
- pkg/config/loader/config_entry_loader.go
- pkg/config/loader/config_loader.go
- pkg/config/loader/config_loader_test.go
- pkg/config/loader/parameter_integration_test.go
- pkg/config/loader/template_integration_test.go
- pkg/project/project_loader.go
- pkg/project/project_loader_test.go
When copying and pasting configs between projects, it is easy to forget to update any overrides. Currently, this is silent: the overrides simply have no effect, which can have undesirable consequences. 
With this PR, a warning is emitted when an override references an environment or environment group that is not defined in the manifest.
A decision was made not to emit an error, at least for now, as this would be a breaking change.
This PR builds on https://github.com/Dynatrace/dynatrace-configuration-as-code/pull/1897, which adds the names of all environments and groups to the loaded manifest, regardless of whether they're selected to be deployed or not.
In this PR, when a config entry is loaded, the environment or group name of each override is checked against those in the manifest.
- …
> feat(config): Warn when undefined environments or groups are used in overrides

- cmd/monaco/integrationtest/v2/deprecated_schemas_produce_user_warnings_e2e_test.go
- cmd/monaco/integrationtest/v2/invalid_payloads_produce_user_errors_e2e_test.go
The move to slog changes the ordering of some elements in log messages. Some tests that depend on this were not yet updated.
With the move to `slog`, attributes attached to a log message appear after the message itself.
The regular expressions in two E2E tests, `TestAPIErrorsAreReported` and `TestDeprecatedSettingsSchemasProduceWarnings`, are updated to assert the message first and then the coordinate.
Existing tests are updated.
No effect on users.
> test: Update E2E tests to expect coordinates after message in logs

- go.mod
- go.sum
- internal/log/log.go
- internal/log/log_test.go
Colorized logs, particularly the key-value pairs used by slog, are easier to read on the console.
With this PR, the existing environment variable `MONACO_LOG_FORMAT` supports a new value, `color`. In this case, console logs are colorized, while file logs are plain text, without color.
The existing behavior remains unchanged: if set to `json`, console and file logs are JSON, and if set to no value or empty, all logs are the default plain text, no color.
Note: When colorized logs are selected, Monaco uses the `tint.Handler` with `time.Kitchen` time format as demonstrated https://github.com/lmittmann/tint?tab=readme-ov-file#usage.
- Use handler from `github.com/lmittmann/tint` to colorize logs
- Allow this to be enabled via `color` value of `MONACO_LOG_FORMAT` environment variable
Test cases …
> feat: Optionally use colored logs

- pkg/config/config_test.go
- pkg/config/entities/entitymap_test.go
- pkg/config/entities/resolvedentity.go
- pkg/config/parameter/reference/reference_test.go
- pkg/deploy/internal/automation/automation.go
- pkg/deploy/internal/automation/automation_test.go
- pkg/deploy/internal/bucket/bucket.go
- pkg/deploy/internal/bucket/bucket_test.go
- pkg/deploy/internal/classic/classic.go
- pkg/deploy/internal/classic/classic_test.go
- pkg/deploy/internal/document/document.go
- pkg/deploy/internal/openpipeline/openpipeline.go
- pkg/deploy/internal/setting/setting.go
- pkg/deploy/internal/setting/setting_test.go
- sonar-project.properties
- test/internal/assert/assert.go
The property was only read by a single test, no production code read it. So instead of writing it 20 times, let's just remove it.
Removed the property
Doesn't
> refactor: Remove unused `ResolvedEntity::EntityName` property

- cmd/monaco/account/delete.go
- cmd/monaco/dynatrace/dynatrace.go
- cmd/monaco/runner/runner.go
- go.mod
- go.sum
- internal/environment/get_env_value.go
- internal/environment/get_env_value_test.go
- pkg/client/clientset.go
- pkg/client/clientset_test.go
Allowing users to set additional HTTP headers for requests.
The multiline environment variable `MONACO_ADDITIONAL_HTTP_HEADERS` is introduced. Its content is parsed. Each line represents an HTTP header. The key- and value part of the header are separated via `:`. These HTTP headers are appended to all requests sent via Monaco.
The variable is retrieved and parsed at all places where the client factory is used to create REST clients. It is also parsed once at the start of Monaco to log the header keys, if any are present.
To be done.
Currently, only parsing the environment variable contents is tested. Passing it to the clients is not tested yet.
Allowing users to set additional HTTP headers for requests via the environment variable `MONACO_ADDITIONAL_HTTP_HEADERS`.
> feat(clients): allow custom http headers

- cmd/monaco/deploy/deploy.go
- cmd/monaco/deploy/deploy_test.go
- cmd/monaco/download/auth.go
- cmd/monaco/download/download_command.go
- cmd/monaco/download/download_command_test.go
- cmd/monaco/download/download_configs.go
- cmd/monaco/download/download_configs_test.go
- cmd/monaco/download/download_integration_test.go
- cmd/monaco/dynatrace/dynatrace.go
- cmd/monaco/dynatrace/dynatrace_test.go
- pkg/client/apitoken/client.go
- pkg/client/apitoken/client_test.go
- pkg/client/auth/transport.go
- pkg/client/clientset.go
- pkg/client/clientset_test.go
- pkg/config/loader/config_loader_test.go
- pkg/download/download_writer_test.go
- pkg/manifest/internal/persistence/manifest_persitence.go
- pkg/manifest/loader/manifest_loader.go
- pkg/manifest/loader/manifest_loader_test.go
- pkg/manifest/manifest.go
- pkg/manifest/manifest_test.go
- pkg/manifest/writer/manifest_writer.go
- pkg/manifest/writer/manifest_writer_test.go
- pkg/project/project_loader_test.go
- test/commands/delete_integration_test.go
- test/configtypes/settings/settings_test.go
This ensures that the manifest is still compatible (stays `token`), but the user *might* be less confused.
And also, we might be less confused.
Searched and replaced most `token` mentions with `API-token`. 
Notable exclusions are:
* `--token` in the CLI
* `token: ...` in the manifest
* `TokenEndpoint` (SSO token endpoint)
Users will have a harder time differentiating between `token` and platformToken`. These updated messages could help, at least, they should not confuse more.
> refactor: Rename all `token` mentions in the code and messages to `API token`

- pkg/deploy/deploy.go
- pkg/resource/deployable.go
- pkg/resource/slo/deploy.go
- pkg/resource/slo/deploy_test.go
The deploy checks many config types, so adding new config types always comes with some overhead and several places where adjustments are needed to support a new resource.
A new "Deployable" interface is introduced.
For now, the SLO resource fulfills this interface. Other resources will follow.
By creating an SLO-deployable and making use of it.
At the moment, this is only used for the deploy. Caching and validation are out of scope.
Existing tests cover it, and new ones were added.
NONE
> refactor(deploy): Introduce `Deployable` and generify SLO

- internal/testutils/config.go
- pkg/deploy/deploy_test.go
- pkg/deploy/internal/automation/automation_test.go
- pkg/deploy/internal/classic/classic_test.go
- pkg/deploy/internal/classic/validation_test.go
- pkg/deploy/internal/document/document_test.go
- pkg/deploy/internal/extract/configname_test.go
- pkg/deploy/internal/openpipeline/openpipeline_test.go
- pkg/deploy/internal/setting/setting_test.go
The deploy package has its own internal test utils, which are (re)moved once the deployable interface is introduced. Therefore, moving it now to `internal/testutils/config.go`
> refactor(deploy): move deploy test utils to internal test utils

- pkg/deploy/deploy.go
- pkg/resource/bucket/deploy.go
- pkg/resource/bucket/deploy_test.go
- pkg/resource/bucket/download.go
- pkg/resource/bucket/download_test.go
In order to make the deploy step more generic, the buckets deploy step should satisfy the Deployable interface.
- Deploy moved and modified to satisfy the Deployable interface
- Deploy makes use of the deployable
- Some constants from the downloadable are moved inside the scope where they're needed in order to prevent name shadowing
Existing tests are moved and adjusted
NONE
> refactor(deploy): generify buckets

- pkg/deploy/deploy.go
- pkg/resource/classic/deploy.go
- pkg/resource/classic/deploy_test.go
In order to make the deploy step more generic, the classic deploy step should satisfy the Deployable interface.
- Deploy moved and modified to satisfy the Deployable interface
- Added some tests (coverage was pretty low)
- Refactored some functions to be less complex
- Existing tests are moved and adjusted
- New tests added
NONE
As I commented below, we have some dead code. Let me know, if I should remove or refactor it
> refactor(deploy): generify classic

- pkg/deploy/deploy.go
- pkg/resource/resource.go
This PR makes use of the Deployable interfaces of all resources.
Only the deploy itself is touched, as caching and validation are out of scope.
Instead of a clientSet, a `deployables` is forwarded to the deploy, which contains the generic deployables, identified via config type.
Existing tests cover it
NONE
> refactor(deploy): make use of generic deployable

- cmd/monaco/download/auth.go
- cmd/monaco/download/download_command.go
- cmd/monaco/download/download_command_test.go
Monaco can download configs "directly" by specifying the environment URL and credentials on the CLI. This PR adds support for doing this with a platform token, and adds the necessary `--platform-token PLATFORM_TOKEN` flag.
Direct download is now possible with:
- just an API token
- **new**: just OAuth credentials, something that has worked with a manifest for some time
- **new**: just a platform token
- an API token and OAuth credentials
- **new**: an API token and a platform token
- Some refactoring is done to try to reduce complexity
- A small change to how the manifest file name is handled means that an error is always given if the `--url` flag is used as well as a manifest file name
- The `--platform-token PLATFORM_TOKEN` flag is added
- Logic is updated to add a platform token to the …
> feat(download): Support direct download with platform token

- cmd/monaco/download/download_command.go
- cmd/monaco/download/download_configs.go
- internal/featureflags/temporary.go
- pkg/client/test_clientset.go
- pkg/config/internal/persistence/type_definition.go
- pkg/config/loader/config_loader_test.go
- pkg/config/writer/config_writer_test.go
- pkg/deploy/deploy_test.go
- test/commands/all_configs_integration_test.go
- test/commands/deletefile_test.go
- test/commands/dry-run_test.go
The openpipeline feature flag is removed, and everywhere it was used, it's replaced by the `true` condition of this flag.
Openpipeline FF is removed
**Issue:** CA-15449
> refactor(openpipeline): remove feature flag

- pkg/report/reporter.go
- pkg/report/reporter_test.go
In the scenario where no deployment ever occurred, for example, due to an error in the manifest, the deployment summary contained incorrect values for deployment end and duration.
- Deployment end time and duration are now correct, duration is zero if no reports were made.
- Only the first letter of the first word of each line of the summary is capitalized.
Both deployment start and end are set to `time.Now()` when the reporter is created.
An additional test `TestReporter_CorrectSummaryIfNoReportsMade` is added which asserts on the basic structure of the summary.
Users will see correct values for deployment end time and duration.
**Issue:** NO ISSUE
> fix(report): Deployment summary should have correct end time and duration even if no reports were made

- test/internal/runner/rewrite_functions.go
- test/internal/runner/rewrite_functions_test.go
If config files had a comment in the name line, the test suffix wasn't correctly added
Comments are now ignored/considered when adding the test suffix
**Issue:**
> fix(E2E): ignore comments when adding test suffixes to config names

- test/commands/all_configs_integration_test.go
- test/commands/dry-run_test.go
- test/commands/testdata/integration-all-configs/manifest.yaml
- test/commands/testdata/integration-all-configs/project/openpipeline/config.yaml
Some followup refactorings to #1952
In a manifest which now also contains the environment `platform_token_env`, the other platform environment, called `platform_env`, which depends on OAuth credentials, is renamed to `platform_oauth_env`
**Issue:**
> refactor: rename `platform_env` to `platform_oauth_env`

- cmd/monaco/download/download_command.go
- cmd/monaco/download/download_configs.go
- cmd/monaco/download/download_configs_test.go
- internal/featureflags/temporary.go
- pkg/config/internal/persistence/type_definition.go
- pkg/config/loader/config_loader_test.go
- pkg/config/writer/config_writer_test.go
- pkg/delete/all.go
- pkg/delete/all_test.go
- pkg/delete/delete.go
- pkg/delete/delete_test.go
- pkg/deploy/deploy_test.go
- test/commands/all_configs_integration_test.go
- test/commands/config_restore_e2e_test.go
- test/commands/dry-run_test.go
- test/configtypes/slov2/slo-v2_test.go
- test/configtypes/slov2/slo_request_handling_test.go
The slo-v2 feature flag is removed, and everywhere it was used, it's replaced by the `true` condition of this flag.
SLO-V2 FF is removed
**Issue:** CA-15448
> refactor(slo-v2): remove feature flag

- cmd/monaco/download/download_command_test.go
- internal/featureflags/temporary.go
- pkg/manifest/loader/manifest_loader_test.go
Now that all parts of platform token support are complete, this feature flag should be enabled by default.
If `MONACO_FEAT_ENABLE_PLATFORM_TOKENS` is not set, the platform token feature flag is assumed to be enabled by default.
Changed the default in `internal/featureflags/temporary.go`.
Existing tests cover both the feature flag being turned on and off. Tests are updated to reflect the change in default value.
Yes, platform tokens will be supported by default. Users can disable the functionality by setting  `MONACO_FEAT_ENABLE_PLATFORM_TOKENS` to `false` or `0`.
**Issue:** CA-15415
> feat: Enable `MONACO_FEAT_ENABLE_PLATFORM_TOKENS` feature flag by default

- pkg/config/loader/config_entry_loader.go
- pkg/project/project_loader_test.go
With #1880, the config entry loader began to emit warnings for environment and group overrides referencing environments and groups not defined in the manifest. Unfortunately, this had a bug, leading to lots of log spam with erroneous warnings.
`warnForUndefinedEnvironments(...)` now works correctly.
With this commit, the check for undefined environments in `warnForUndefinedEnvironments(...)` correctly uses `AllEnvironmentNames` rather than `AllGroupNames`. 
Tests for this are refactored into `TestLoadProjects_OverridesWithUndefinedElements`:
- Explicit test cases check that no warnings are generated for overrides referencing known environments and groups.
- The test cases are tightened up with different names for environments (e.g., `devEnv` and `prodEnv`) and groups (e.g., `devGroup` and …
> fix(config): Use environment names rather than group names for check for undefined environments

- go.mod
- go.sum
- pkg/client/clientset.go
- pkg/client/dummy_clientset.go
- pkg/delete/delete_test.go
- pkg/resource/bucket/bucket.go
- pkg/resource/bucket/delete.go
- pkg/resource/bucket/delete_test.go
- pkg/resource/bucket/deploy.go
- pkg/resource/bucket/deploy_test.go
The logic for updating a bucket only when it can be is now handled by Monaco and not the core lib. The core lib also removes upsert, which Monaco depends on.
- The logic for updating a bucket only when it can be, is now handled by Monaco and not the core lib
- The upsert was removed, so Monaco now handles the upsert (create/update) logic.
By splitting Upsert into create & update, and adding some checks before it can be updated/deleted.
New tests are added, existing ones are adapted, and some existing ones are moved closer to the package that is being tested.
NONE
https://github.com/Dynatrace/dynatrace-configuration-as-code-core/pull/235
Only realized later that there were adjustments of other PRs pointing to the same files. Anyway, a bit of refactoring doesn't hurt I guess 😉 
**Issue:** …
> refactor(bucket): use core lib without upsert and active check

- pkg/resource/document/delete.go
- pkg/resource/document/delete_test.go
- pkg/resource/document/deploy.go
- pkg/resource/document/download.go
- pkg/resource/document/types.go
Monaco only supports documents of particular types, however previously it was hard to update these as information about the supported types was not centralized. This lead to launchpad documents not being supported by the purge command.
- The filter used to select documents to delete in  `document.DeleteAll(...)` now includes `launchpad`
- Refactored to have document types supported by Monaco in a centralized file `types.go`, rather than in various places in the `document` package.
- This includes the `launchpad` type
- Refactored `document.DeleteAll(...)` to build the filter string dynamically from the supported document types.  
- Existing tests for `document.DeleteAll(...)` are updated to assert that the filter used to list documents includes the launchpad type.
- The purge command now …
> fix(document): `DeleteAll(...)`  should also delete launchpad documents

- internal/maps/maps.go
- internal/maps/maps_test.go
- pkg/config/parameter/list/list_test.go
- test/configuration/escaping/testdata/special-character-in-config/project/auto-tag/_config.yaml
- test/configuration/escaping/testdata/special-character-in-config/project/auto-tag/auto-tag.json
Given this code example:
```yaml
...
properties:
property:
type: value
value:
subproperty: |
My
string
```
When reading the above property, we read it as a `map[any]any` and convert it to a `map[string]any`. Later, we apply recursive escaping functions to the `any` value.
However, when parsing subproperties, we get a `map[string]map[any]any`, and the recursive functions fail with the second `map[any]any`.
This fix now parses the maps recursively during reading, and thus the later recursive functions work properly, and the multiline strings are escaped correctly.
N/A
Added an e2e test case, as well as unit tests 💪 
Users are not able to use multiline strings in nested properties.
**Issue:** CA-16115
> fix: Nested values now escape correctly.

- cmd/monaco/account/delete.go
- cmd/monaco/dynatrace/dynatrace.go
- cmd/monaco/dynatrace/dynatrace_test.go
Dynatrace Account Management APIs currently enforce a rate limit of 200 requests per minute, however Monaco is unable to react to this. As a workaround, as the limit is reset after a minute, delaying further requests for 60 seconds will allow Monaco to continue using the API. 
First a minor refactoring is made to create account clients in a single function, so that they behave consistently. Secondly, the retry options are changed.
Most importantly the retry options are changed to:
- only retry after a 429 error
- delay for 30 seconds before retrying: this gives a good balance between successfully retrying and providing feedback via log messages.
Basic tests are added for successful account management client creation.
Account management deploy, download and delete operations shouldn't fail …
> fix(account): Increase delay after 429 errors for account management

- test/commands/config_restore_e2e_test.go
Some tests were excluded even though the token endpoint isn't used
Enabled some tests for hardening environments.
By removing the `t.Skip`
They're tests, they're executed.
Doesn't affect users.
**Issue:** CA-14365
> test: remove unnecessary skips

- pkg/account/persistence/schemagenerator_test.go
- pkg/account/persistence/testdata/schema.json
I noticed missing test coverage here. I added this test also, because the schema will change with adding boundaries. Also, since we have a feature flag to toggle boundaries on and off, I will subsequently extend this test case with a case for the boundaries added to the schema.
It was important, however, to capture the current behavior of the schema generator, from main, without any influence from the boundaries feature, to have a state to test against.
A schema generation test case for IAM resources has been added.
Unit test + schema.json testdata file to check against.
It doesn't
**Issue:**
CA-16338
> test(iam): Adds JSON schema generator test

- internal/featureflags/temporary.go
- pkg/account/delete/client.go
- pkg/account/delete/client_test.go
- pkg/account/delete/delete.go
- pkg/account/delete/delete_test.go
- pkg/account/delete/loader.go
- pkg/account/delete/loader_test.go
- pkg/account/delete/persistence.go
- pkg/account/delete/schemagenerator.go
- pkg/account/delete/schemagenerator_test.go
- pkg/account/delete/testdata/schema-with-boundaries.json
- pkg/account/delete/testdata/schema.json
For the boundary support, we also need to support the deletion of boundaries.
The deletefile can now accept entries of the form 
```
- type: boundary
name: My special boundary
```
This deletes a boundary with said name from the account, if it is found and **not in use**
If is is in use, you will get an error message, like the following:
```
time=2025-09-05T21:12:03.067+02:00 level=ERROR msg="Failed to delete boundary \"My special boundary\": failed to delete boundary \"My special boundary\" (HTTP 400): {\"error\":{\"code\":400,\"message\":\"Policy boundary is in use: policy 51ff37c5-7260-4a40-bbe2-488c847b944b to groups: [8ec1efdb-f2b2-4fc7-b49d-4355cf420410]\",\"errorsMap\":{\"boundary_usage_rule\":\"Policy boundary is in use: policy 51ff37c5-7260-4a40-bbe2-488c847b944b to groups: …
```
> feat(boundaries): Adds deletion of boundaries

- README.md
Monaco 1.x documentation is no longer being hosted, but is rather included with each release.
Removed broken link in `README.md`.
Not applicable
They won't be able to click on a broken link.
**Issue:** Not applicable
> docs: Remove broken link to Monaco 1.x documentation

- cmd/monaco/supportarchive/supportarchive.go
- cmd/monaco/supportarchive/supportarchive_test.go
- internal/testutils/support_archive.go
- test/logging/supportarchive_report_test.go
There may be some cases where the response and request files don't exist, like when the manifest YAML is invalid. Therefore, we're removing the error log for these files.
There aren't any errors reported anymore if the request or response file is missing
By first checking if the files exist before adding them to the zip file
New tests added to test that there aren't any errors when creating a zip archive without the request and response files
They will just notice that one log is removed
**Issue:** CA-16549
> fix(support-archive): Don't report missing response and request files

- cmd/monaco/main.go
- cmd/monaco/main_test.go
- cmd/monaco/runner/runner.go
- cmd/monaco/runner/runner_test.go
- internal/testutils/support_archive.go
- test/account/all_resources_integration_test.go
- test/account/utils_test.go
- test/configtypes/slov2/slo_request_handling_test.go
- test/configuration/pagination/pagination_e2e_test.go
- test/configuration/references/references_test.go
- test/errorcases/deprecated_configs_produce_user_warnings_e2e_test.go
- test/errorcases/deprecated_schemas_produce_user_warnings_e2e_test.go
- test/errorcases/duplicate_coordinates_produce_user_errors_e2e_test.go
- test/errorcases/invalid_manifests_produce_user_errors_e2e_test.go
- test/errorcases/invalid_payloads_produce_user_errors_e2e_test.go
- test/internal/monaco/cmd.go
- test/logging/supportarchive_report_test.go
- test/logging/version_logged_e2e_test.go
The support archive didn't contain all errors that were reported.
The error returned from the command was not inside the support archive. That was because the errors returned inside the command run weren't logged inside, and the archive is written right after the run via the onFinalize of the command. Therefore, writing the support archive happened before the returned error was handled/logged by the parent that executed the command.
By returning a pointer to the supportArchive flag of the command and checking based on this one after the command execution if the support archive should be written or not.
Users now see every logged error in the support archive.
**Issue:** CA-16548
There is no way to test the missing line in `main.go`, as `os.Exit` leads to a panic in tests
> fix(support-archive): write command errors
