Dynatrace/dynatrace-configuration-as-code

README.md, RELEASE_NOTES.md, pkg/version/version.go
Release Fix for #43: Verbose Logging isn't working
=> Release Version 1.0.1

pkg/config/config.go, pkg/config/config_test.go
name like the config that is being processed at the moment
Resolves: #22
=> Fix issue that loads properties from configs that start with the same

cmd/monaco/test-resources/integration-all-configs/project/request-naming/demorule.json, cmd/monaco/test-resources/integration-all-configs/project/request-naming/requestnamingrules.yaml, pkg/api/api.go
=> Global Service Request Naming Support

README.md
correct delete section and sort table for tokens by first column
fixes #85
=> Update README delete section

RELEASE_NOTES.md, pkg/version/version.go
* ee01baf Fix #77: Enhance log messages for syntax errors detected in JSONs (#88)
* 2dc498d Fix #87: Implement simple strategy to prevent running into rate limit (#89)
* 42cb186 Encapsulate REST code in DynatraceClient (#74)
* cfe9179 Fix #84: Add --version flag (#95)
* 5f82131 Fix #40 and #75: Improve help text (#75)
* 75213b9 Fix #58: Log a warning if project name clashes with API name (#58)
* af1bfba Fix #68: Update Request Naming Folder Name to request-naming-service (#73)
* b0d4f44 Fix #68: Add Global Service Request Naming Support (#69)
* e09bde2 Fix #60: Allow path separators in variables (#83)
* c187ffc Fix #80 and #93: Allow trailing slash in folder on Windows (#94)
* 82bb035 Fix #37: Add Windows handling to Make targets (#72)
* c0f31df Fix #20: Delete configs only if apply …
=> Release version 1.1.0

pkg/config/config.go, pkg/config/config_mock.go, pkg/config/config_test.go, pkg/deploy/deploy.go, pkg/rest/client.go, pkg/rest/client_mock.go, pkg/util/error_handling.go, pkg/util/json.go, pkg/util/json_test.go
I guess this fixes #101 
As a nice side-effect it seems to fix the pretty printing for json errors. 
For whatever reason it was broken.
=> Use map[]interface{} for json unmarshalling

pkg/environment/environment.go, pkg/environment/environment_test.go
Trim trailing slashes from environment URL. Hopefully the final attempt :)
=> Trim trailing slashes + unit test

cmd/monaco/test-resources/integration-multi-project/star-trek/star-wars/dashboard/dashboard.yaml, pkg/config/config.go, pkg/config/config_test.go
- fixes #141
- added tests with dependency resolution withing overrides
=> Fix dependency resolution not working if defined in overrides

README.md
Add requirements for documentation configuration on Dynatrace versions
208 onwards
=> fixes #240

README.md
Add instruction for using a proxy server in documentation
=> fixes #232

README.md
Document questions about custom extension zips and doc examples
=> fixes #113

README.md, cmd/monaco/test-resources/integration-all-configs/project/reports/report.json, cmd/monaco/test-resources/integration-all-configs/project/reports/report.yaml, pkg/api/api.go
see the issue for details.
fixes #123
=> feat: Add reports API for dashboards

.github/workflows/build-test.yml, .github/workflows/fork-integration-test.yml, .github/workflows/release.yml, go.mod, go.sum, tools/check-license-headers.sh
=> Feature/upgrade to go 1.16

pkg/rest/config_upload.go
=> Print warning if two or mode configurations having same name are detected in Dynatrace.

documentation/yarn.lock
this is to address secuirty alerts from depandabot : https://github.com/dynatrace-oss/dynatrace-monitoring-as-code/security/dependabot 
fixes #380
=> update vulnerable security packages 

cmd/monaco/v2/deploy/deploy.go, cmd/monaco/v2/runner/runner.go
=> fix: allow deployment of multiple projects and envs at once

documentation/versioned_docs/version-1.7.0/commands/deploying-projects.md
I'm not sure what line #32 is about.  It looks like it is between the line that discusses the -se flag and the code sample itself.  Nothing explains what the metadata is -- and metadata is the plural of metadatum so "metadatas" is probably not rignt.
=> small edits for your consideration

.github/workflows/build-test.yml, .github/workflows/dependencies-and-licenses.yml, .github/workflows/fork-integration-test.yml, .github/workflows/release.yml
=> build: restrict go version to >= 1.16 and < 1.17

cmd/monaco/test-resources/integration-all-configs/project/slo/slo.json
=> test: fix integration tests

documentation/docs/Get-started/installation.md, documentation/docs/Get-started/intro.md, documentation/docs/Guides/add_new_api.md, documentation/docs/Useful-links/bill-of-materials.md, documentation/docs/commands/Logging.md, documentation/docs/commands/deploying-projects.md, documentation/docs/commands/downloading-configuration.md, documentation/docs/commands/experimental-new-cli.md, documentation/docs/configuration/configuration_structure.md, documentation/docs/configuration/delete_config.md, documentation/docs/configuration/plugin_config.md, documentation/docs/configuration/yaml_config.md
=> docs: Resolve mismatch between latest and 1.7.0

pkg/util/test_utils.go, pkg/util/test_utils_test.go
=> test: skip dependency transformation

pkg/download/jsoncreator/json_creator.go, pkg/download/jsoncreator/json_creator_test.go
=> feat: Download non Dynatrace preset dashboards

pkg/download/jsoncreator/json_creator.go, pkg/download/jsoncreator/json_creator_test.go
- added one helper function to remove a key with specified path in  json_creator
fixes: #668 
fixes: #669
=> Bugfix: download is not removing non standard identifiers #668 & #669 

pkg/deploy/deploy.go, pkg/rest/config_upload.go, pkg/rest/request.go
Extends Debug logging of the delete operation, as well
as making userfacing logging clearer (INFO log for actually executed delition),
and adding error handling where errors where previously ignored.
relates-to: #652
=> feat: Improve error handling and logging of Delete operation

pkg/download/jsoncreator/json_creator.go, pkg/download/jsoncreator/json_creator_test.go
added a filter , which should remove any built-in extensions form download
fixes: #667
=> fix: added filter for extensions not to download built-in ones #667

pkg/rest/config_upload.go, pkg/rest/config_upload_test.go
The addition of an extra query parameter for getting all SLO configurations, lead to discovering that we do not correctly handle pagination if any other query params are set.
Also extend the previously added to tests to fully validate the behaviour of the method getting all configs from the API, encluding what parameters are set based on defined server returns and whether we expect an error or success.
=> fix: Correctly handle pagination when other query parameters are set

cmd/monaco/deploy/command.go, cmd/monaco/deploy/deploy.go, cmd/monaco/deploy/deploy_test.go, internal/throttle/throttle_requests.go, internal/throttle/throttle_requests_test.go, pkg/manifest/manifest.go, pkg/project/v2/project.go
split up responsibilities of functionality in Deploy() into multiple smaller functions that can be unit tested
=> chore: refactored deploy function

Dockerfile
With this fix, make will be able to create sound docker container
=> fix: fix Dockerfile

cmd/monaco/convert/command.go, cmd/monaco/runner/runner.go, internal/errutils/error_handling.go, internal/idutils/external_id.go, internal/idutils/uuid_generator.go, internal/maps/maps.go, internal/regex/regex_patterns.go, internal/template/template_utils.go, pkg/client/client.go, pkg/client/config_client.go, pkg/config/v2/config_persistence.go, pkg/config/v2/config_writer.go, pkg/config/v2/parameter/list/list.go, pkg/converter/converter.go, pkg/delete/delete.go, pkg/deploy/deploy.go, pkg/download/classic/downloader.go, pkg/download/dependency_resolution.go, pkg/project/v1/project_loader.go
This PR contains just tiny bits of cleanup here and there.
=> chore: general cleanup

cmd/monaco/download/download_command.go
After the last changes on the download command, help messages will be printed after every unsuccessful execution. With this PR help messages for unsuccessful execution are going to be suppressed.
=> Silence help message on download error

pkg/deploy/deploy.go
before this change if an error happen, invalid entity was put in entityMap
Before this change if an error happen, invalid entity was put in entityMap
=> Don't write invalid entity data

cmd/monaco/cmdutils/cmdutils.go, cmd/monaco/delete/delete.go, cmd/monaco/deploy/deploy.go, cmd/monaco/download/download_configs.go, cmd/monaco/download/download_entities.go, cmd/monaco/dynatrace/dynatrace.go, cmd/monaco/dynatrace/dynatrace_test.go, cmd/monaco/integrationtest/integration_test_utils.go, cmd/monaco/purge/purge.go, go.mod, go.sum, pkg/deploy/deploy.go
`cmdutils` is a bad name for what it contains.
This Pr introduces a new "dynatrace" package in "cmd" that contains the functions to create a dynatrace client and check the generation of a tenant.
none
none
=> chore: introduce "dynatrace" package and move related functions to it

.golangci.yaml
It instructs `golangci-lint` to exclude/skip go files containing tests as these files potentially contain issues that we won't fix.
=> chore: exclude go test files static code analysis

cmd/monaco/download/download_configs.go, cmd/monaco/download/downloaders.go, cmd/monaco/download/downloaders_test.go, internal/json/json.go, internal/json/json_test.go, pkg/client/automation/client.go, pkg/download/automation/automation.go, pkg/download/automation/automation_test.go, pkg/download/automation/testdata/listBusinessCals.json, pkg/download/automation/testdata/listSchedulingRules.json, pkg/download/automation/testdata/listWorkflows.json, pkg/download/settings/settings.go
This PR adds a `Downloader` that makes use of the automation API client for downloading automation resources.
Feature flag for automation resources needs to be enabled.
This PR does not include special handling of escaping templating inside workflow payloads.
If the user enables the feature flag for automation resources, monaco will go and try to download all (supported types) of automation resources (workflows, business calendars, scheduling rules)
=> feat: Download Automation API resources

pkg/download/automation/automation.go, pkg/download/automation/automation_test.go
Like existing types, Automation payloads contain data that is not needed on upload and just clutters config-as-code files - thus a simple sanitization is added. As these APIs are fewer and more consisten than Classic Config APIs, the full fledged sanitizer code from their download is not reused.
Additionally the 'title' field which all currently supported Automation types contain, is extracted as the config's 'name' if it is found.
To make this resilient, any failure in extraction is just treated as before and will persist the payload as is.
=> feat(download): Sanitize downloaded Automation configurations

pkg/converter/converter.go, pkg/converter/converter_test.go
Fixes a bug while converting v1 config with multiple env var references to a v2 config, e.g.:
```yaml
- name: "{{ .Env.alertgroup }} - {{ .Env.application_name}}"
``` 
 produces only a single Environment type parameter for {{alertgroup}} and loses the {{application_name}} variable reference.
The fix contains the code to detect multiple environment variable references and converts them into a compound parameter, e.g.:
```yaml
- name: "{{ .Env.GOPATH }} - {{ .Env.GOROOT }}"
```
gets converted to:
```yaml
name:
format: '{{ .__ENV_GOPATH__ }} - {{ .__ENV_GOROOT__ }}'
references:
- __ENV_GOPATH__ 
- __ENV_GOROOT__ 
type: compound
parameters:
__ENV_GOPATH__ :
name: GOPATH
type: environment
__ENV_GOROOT__ :
name: GOROOT
type: environment
```
Multiple env var refs in v1 config yaml files are …
=> fix: conversion of environment variables refs does not consider compound cases

pkg/client/automation/client.go, pkg/client/automation/client_test.go
Add `Get` method to fetch a single automation resource by ID:
```go
httpClient := auth.NewOAuthClient(context.TODO(), auth.OauthCredentials{
ClientID:     "######",
ClientSecret: "######",
TokenURL:     "https://sso.dynatrace.com/sso/oauth2/token",
})
automationClient := automation.NewClient("https://####.apps.dynatrace.com", httpClient)
wf, err := automationClient.Get(context.TODO(), "f41f0468-74c7-43e0-a4c4-6770ab336235", automation.Workflows)
if err != nil {
log.Fatal(err.Error())
}
...
```
=> feat: Get single automation resource by ID

cmd/monaco/integrationtest/v2/test-resources/integration-automation/project/business-calendar/config.yaml, cmd/monaco/integrationtest/v2/test-resources/integration-automation/project/combined/business-calendar.json, cmd/monaco/integrationtest/v2/test-resources/integration-automation/project/combined/config.yaml, cmd/monaco/integrationtest/v2/test-resources/integration-automation/project/combined/jira-issue-workflow.json, cmd/monaco/integrationtest/v2/test-resources/integration-automation/project/combined/scheduling-rule.json, cmd/monaco/integrationtest/v2/test-resources/integration-automation/project/scheduling-rule/config.yaml, cmd/monaco/integrationtest/v2/test-resources/integration-automation/project/workflow/config.yaml
Extends the test to include a combination of business calendars, scheduling rules, and workflows that depend in a chain.
=> test: Extend Automation e2e tests to test a combination of resources

pkg/client/dtclient/client.go, pkg/client/dtclient/client_settings.go, pkg/client/dtclient/client_settings_test.go, pkg/client/dtclient/dummy_client.go
Calls to `FetchSchemaConstraints`  are cached.
=> feat: cache schema constraints

Makefile
chore: Use latest addlicense build tool
The version was set one too low to test if dependabot can auto-update these versions.
It sadly can't but a fixed outdated version is still better than always pulling whatever 'latest' may be from a security standpoint. Thus tools are manually set to their current latest version.
nope
=> chore: Use latest addlicense build tool

cmd/monaco/generate/deletefile/command.go, cmd/monaco/generate/deletefile/deletefile.go, cmd/monaco/generate/dependencygraph/dependencygraph.go, pkg/delete/persistence/delete_persistence.go, pkg/manifest/manifest_loader.go, pkg/manifest/manifest_loader_test.go
Fix descriptions and samples in cmd help.
Allow generating files without needing to set URL/Auth environment variables - as they're not needed.
Ensure we don't write useless empty strings into generated delete yamls.
All in "What"
=> Improve Generate Commands

internal/featureflags/featureflags.go
=> feat: Enable Automation resources by default

cmd/monaco/download/download_command.go
Explicitly mention if deprecated APis will be downloaded or not.
More clarity to the user what the flags are doing.
=> chore: Small improvement of download CLI flag descriptions

pkg/deploy/deploy.go, pkg/deploy/entitymap.go, pkg/graph/graph.go, pkg/graph/graph_test.go
=> feat: deploy configs within a component in parallel

pkg/converter/converter.go, pkg/converter/converter_test.go
When a Monaco v1 project used the same env variable both in the template and the config, we used to print an error that there is a collision.
This change compares now not only the name but also the payload of the variable. If the payload's the same, we drop one of the parameters. They're the same afterward and may be reused.
=> fix(conversion): Don't fail when the same env var is referenced

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/config.yml, .github/PULL_REQUEST_TEMPLATE.md, .gitignore, .golangci.yaml, CONTRIBUTING.md
This PR fixes multiple Typos, the .gitignore file, and adds the context linter.
=> chore: Typos, .gitignore, and linter

internal/featureflags/featureflags.go, pkg/config/type_definition_test.go
Disable grail bucket management by default
=> fix: Disable grail bucket management by default

pkg/client/bucket/bucket.go, pkg/client/bucket/bucket_test.go
It can happen that while we update a bucket, the bucket's state changes. In that case, we want to retry again after some timeout.
=> fix: Retry on bucket conflict

cmd/monaco/deploy/command.go
=> docs(deploy): Improve help text of deploy command flags

internal/featureflags/featureflags.go, pkg/deploy/deploy_test.go
Enables parallel deploy by default.
Depends on #1134
=> feat: Enable graph based parallel deploy by default

cmd/monaco/integrationtest/assert.go
It was found that the API does not reliably return buckets that were just modified. To improve resilience of the E2E tests, the GET request for asserting is now retried 5 times to work around this.
=> test(e2e): Retry GET request when asserting buckets

go.mod, go.sum, internal/trafficlogs/logger.go, internal/trafficlogs/logger_test.go, pkg/client/clientset.go, pkg/rest/client.go
Uses `HTTPListener` from configuraiton-as-code-core in order to do traffic logging for buckets API
=> feat: implement traffic logging based on core lib clients (buckets)

go.mod, go.sum
Update `conriguration-as-code-core` library version to 0.1.0
=> chore: update dependency configuration-as-code-core @ 0.1.0

README.md
Minor improvements regarding the README.
=> chore: Improve readme

go.mod, go.sum, internal/automationutils/response_decoder.go, internal/automationutils/response_decoder_test.go, pkg/delete/internal/bucket/delete.go, pkg/deploy/internal/automation/automation.go, pkg/deploy/internal/automation/automation_test.go, pkg/deploy/internal/bucket/bucket.go, pkg/deploy/internal/bucket/bucket_test.go, pkg/download/bucket/bucket.go
Adapts the usage of lib to handle breaking change of https://github.com/Dynatrace/dynatrace-configuration-as-code-core/pull/40
=> chore: adapting code to handle breaking changes in lib

cmd/monaco/download/download_configs.go, cmd/monaco/integrationtest/v2/all_configs_integration_test.go, cmd/monaco/integrationtest/v2/bucket_integration_test.go, cmd/monaco/integrationtest/v2/config_restore_e2e_test.go, cmd/monaco/integrationtest/v2/delete_integration_test.go, internal/featureflags/temporary.go, pkg/persistence/config/internal/persistence/type_definition.go, pkg/persistence/config/internal/persistence/type_definition_test.go, pkg/persistence/config/loader/config_loader_test.go
This reverts commit 7f30f23f5525a9323358f3fffe9fb4464be9462b.
=> Chore: revert deletion of bucket api FF

.gitignore
During the process of developing and testing, a lot of "download_*"  directories are created. To prevent unintentionally committing, let's make git ignore those directories.
=> Ignore downloaded files from monaco

cmd/monaco/download/download_command.go, cmd/monaco/download/download_configs.go, cmd/monaco/dynatrace/dynatrace.go, cmd/monaco/integrationtest/integration_test_utils.go, cmd/monaco/integrationtest/v2/settings_integration_test.go, internal/secret/string.go, internal/secret/string_test.go, pkg/manifest/manifest.go, pkg/manifest/manifest_loader.go
Introducing `MaskedString`type to use for fields that store potentially sensitive information.
=> chore: use `MaskedString`for sensitive fields in AuthSecret

.run/shared/IntegrationTests-all.run.xml, .run/shared/IntegrationTests-cleanup.run.xml, .run/shared/IntegrationTests-download_restore.run.xml, .run/shared/IntegrationTests-v1.run.xml, .run/shared/IntegrationTests-v2.run.xml, .run/shared/deploy.run.xml, .run/shared/deploy_dry-run.run.xml, .run/shared/download.run.xml
Updates the IDE run configurations.
=> chore: update of run configurations

.ci/jenkins/tools/docker.groovy, .ci/jenkins/tools/github.groovy, .ci/releasePipeline.groovy, Dockerfile, Makefile
With these changes, the produced docker container is now multi-arch and contains `linux/amd64` and `linux/arm64` containers.
=> feat: add build for linux/amd container

Dockerfile
Limits the permissions in the docker container and which files are copied into the build container to the smallest possible amount.
=> refactor: minimial docker permissions

cmd/monaco/account/delete.go, cmd/monaco/account/deploy.go, cmd/monaco/dynatrace/dynatrace.go, cmd/monaco/integrationtest/account/all_resources_integration_test.go, cmd/monaco/integrationtest/account/runner.go, cmd/monaco/integrationtest/account/testdata/all-resources/accounts/delete.yaml, cmd/monaco/integrationtest/account/users_test.go, pkg/account/delete/loader.go
This PR enhances the current e2e tests for account management.
It covers
* deploying a user, a group and a policy as well as bindings between them.
* asserting that resources were correctly deployed
* deleting the deployed user, group and policy
* asserting that resources were indeed deleted
=> chore: Account Management e2e tests

pkg/persistence/account/internal/types/types.go, pkg/persistence/account/loader/load.go, pkg/persistence/account/loader/load_test.go, pkg/persistence/account/loader/testdata/partial-group.yaml, pkg/persistence/account/loader/testdata/partial-policy.yaml, pkg/persistence/account/loader/testdata/partial-user.yaml, pkg/persistence/account/loader/testdata/policy-missing-env-id.yaml, pkg/persistence/account/loader/validate.go, pkg/persistence/account/writer/writer.go, pkg/persistence/account/writer/writer_test.go
Fixes the following issues: 
- **loader**: creating wrong defined environment policy passes without error
- **writer**:
- for users without any group, group segment is present
- write process panics for groups without policy
/
no, not released and just bug fixes
=> fix: account resources persistence issues

cmd/monaco/account/deploy.go, pkg/account/deployer/client.go, pkg/account/deployer/client_test.go, pkg/account/deployer/deployer.go, pkg/account/deployer/permissions.go
This PR fixes existing issues in current account management deployment. Primarily: 
* deleting all policy & permission bindings that were previously deployed
no, not released yet
=> fix: account management hardening pt.2

pkg/client/dtclient/settings_client.go, pkg/client/dtclient/settings_client_test.go
When updating a settings config, we try to update or onboard existing configs whenever the originObjectId is set.
However, there may be two objects, one with the expected externalId, and a different one with the expected originalObjectId. In this case, we update the setting with the externalId and print a proper warning.
=> fix: Fix settings update with overlapping ids

cmd/monaco/account/download.go, cmd/monaco/account/download_command.go, pkg/persistence/account/loader/load.go
feat: Create manifest.yaml on account download and align naming of created folders with config downloads
not released
=> feat: Create manifest.yaml on account download and align naming of created folders with config downloads

cmd/monaco/account/download.go, internal/log/log.go, pkg/account/downloader/downloader.go, pkg/account/downloader/environments.go, pkg/account/downloader/groups.go, pkg/account/downloader/internal/http/groups.go, pkg/account/downloader/policies.go, pkg/account/downloader/users.go
This PR improves the error & log messages by adding more context.
Additionally, it fixes a potential `nil` panic.
=> feat(account) Improve error and log messages

pkg/account/downloader/downloader_test.go
Since permissions are an important part of a configuration, this test case covers logic related to downloading it (the majority is inside the first commit).
=> New test that covers groups with permissins

cmd/monaco/integrationtest/account/testdata/all-resources/accounts/groups.yaml, pkg/account/deployer/testdata/accdata.yaml, pkg/persistence/account/internal/types/types.go, pkg/persistence/account/loader/testdata/configs-accounts-mixed.yaml, pkg/persistence/account/loader/testdata/duplicate-group.yaml, pkg/persistence/account/loader/testdata/multi-with-configs/a/b/b.yaml, pkg/persistence/account/loader/testdata/multi-with-delete-file/a/b/b.yaml, pkg/persistence/account/loader/testdata/multi/a/b/b.yaml, pkg/persistence/account/loader/testdata/no-ref-policy-env.yaml, pkg/persistence/account/loader/testdata/partial-group.yaml, pkg/persistence/account/loader/testdata/valid-origin-object-id.yaml, pkg/persistence/account/loader/testdata/valid-with-refs.yaml, pkg/persistence/account/loader/testdata/valid.yaml, pkg/persistence/account/writer/writer_test.go
* environment -> environments
* name -> environment (for environment definition)
* managementZone -> managementZones
Rename a few of the keys in yaml file on the suggestion of the first test users.
=> Adopt new names for config.yaml (account management)

cmd/monaco/dynatrace/dynatrace.go
Similar to config download/deploy this PR adds the feature to create support-archives while using account management with monaco
=> feat: add support-archive feature to account resource management

pkg/persistence/account/writer/writer.go, pkg/persistence/account/writer/writer_test.go
feat(account): Write YAML file content in stable order on download
As we do for config YAMLs, the content of account YAML files created by a download is now sorted in a stable order, so that files can actually be diffed and are only different if data that was downloaded has actually changed.
I've run a limited benchmark of running the download command 5 times on our E2E test account.
For the limited benchmark, there's no significant difference in speed or extra allocations incurred from the added sorting.
Not yet released, and not significant anyway: 
Order of downloaded user.yaml, group.yaml and policy.yaml changes compared to previous downloads, but previous DLs produced different file orders each time anyway.
=> feat(account): Write YAML file content in stable order on download

cmd/monaco/integrationtest/account/all_resources_integration_test.go, cmd/monaco/integrationtest/account/runner.go
This PR adjusts the assertions, so that the test is aborted as soon as an error occurs before executing the test case.
=> chore: fail fast if something errors prior to running the test fn

cmd/monaco/integrationtest/v2/test-resources/integration-all-configs/project/key-user-actions-mobile/config.yaml, cmd/monaco/integrationtest/v2/test-resources/integration-all-configs/project/key-user-actions-mobile/key-user-action.json, pkg/api/api.go, pkg/api/endpoints.go, pkg/client/dtclient/client.go, pkg/client/dtclient/config_client.go, pkg/client/dtclient/entities.go, pkg/config/parameter/parameters.go, pkg/deploy/internal/classic/classic.go, pkg/deploy/internal/extract/configname.go, pkg/deploy/internal/setting/setting.go, pkg/rest/request_test.go, pkg/rest/retry.go
This PR adds support for creating and updating mobile key user actions
=> feat: Deploy mrum key user actions

cmd/monaco/integrationtest/v2/test-resources/integration-all-configs/project/key-user-actions-mobile/key-user-action.json
=> test: fix payload of key-user-action in e2e tests

cmd/monaco/integrationtest/account/deploy-download_test.go, cmd/monaco/integrationtest/account/utils_test.go, cmd/monaco/integrationtest/v2/all_configs_integration_test.go, cmd/monaco/integrationtest/v2/automation_integration_test.go, cmd/monaco/integrationtest/v2/bucket_integration_test.go, cmd/monaco/integrationtest/v2/convert_configs_integration_test.go, cmd/monaco/integrationtest/v2/deprecated_schemas_produce_user_warnings_e2e_test.go, cmd/monaco/integrationtest/v2/diff_project_diff_ext_id_test.go, cmd/monaco/integrationtest/v2/duplicate_coordinates_produce_user_errors_e2e_test.go, cmd/monaco/integrationtest/v2/errors_written_to_file_e2e_test.go, cmd/monaco/integrationtest/v2/invalid_manifests_produce_user_errors_e2e_test.go, cmd/monaco/integrationtest/v2/invalid_payloads_produce_user_errors_e2e_test.go, cmd/monaco/integrationtest/v2/multi_project_integration_test.go, cmd/monaco/integrationtest/v2/multi_type_configs_e2e_test.go, cmd/monaco/integrationtest/v2/special_character_in_config_integration_test.go
Some integration tests fail occasionally or don't clean after.
=> fix failing integration tests

pkg/deploy/internal/automation/automation.go, pkg/download/automation/download.go
This PR adds a timeout (of one minute, without any further reasoning why exactly one minute, please comment if you disagree with that value) to the context passed to the automation http client for deploy and download.
=> fix: timeout for automation client

pkg/project/v2/project_loader_test.go
1) Use testify
2) Use TempFs instead of InMemoryFs
=> refactor: Unify testing code

internal/environment/get_env_value_test.go, internal/json/json_test.go, internal/template/template_integration_test.go, pkg/config/parameter/value/value_test.go, pkg/rest/rate_limit_test.go
=> chore: Unify testing code (ctd.) 

cmd/monaco/integrationtest/account/all_resources_integration_test.go
Previous test code excluded some nil checks and the use of assert instead of require resulted in possible nil pointer dereference when trying to validate the content of response objects that were not actually received in case of an error.
nope, test code
=> test: Ensure Account resources test is nil/error safe

CONTRIBUTING.md
=> docs(CONTRIBUTING): Describe test library and require/assert guideline

cmd/monaco/integrationtest/account/all_resources_integration_test.go, internal/featureflags/temporary.go, pkg/manifest/writer/manifest_writer_test.go
This PR enables AM Resources by default
=> feat: Release Account Management

.github/workflows/snyk.yml
This PR adds the snyk github action to scan for vulnerabilities when opening a PR.
This does not (yet) contain pushing the tag to snyk.io
=> chore: Add snyk security scan

internal/testutils/matcher/api.go, pkg/api/api.go, pkg/download/classic/download_test.go
This matcher is for easier use with gomock.
=> feat: add api matcher (for use with gomock)

cmd/monaco/integrationtest/v2/scoped_configs_test.go, cmd/monaco/integrationtest/v2/test-resources/scoped-configs/manifest.yaml, cmd/monaco/integrationtest/v2/test-resources/scoped-configs/project/application-mobile/app1.json, cmd/monaco/integrationtest/v2/test-resources/scoped-configs/project/application-mobile/app2.json, cmd/monaco/integrationtest/v2/test-resources/scoped-configs/project/application-mobile/config.yaml, cmd/monaco/integrationtest/v2/test-resources/scoped-configs/project/user-action-and-session-properties-mobile/config.yaml, cmd/monaco/integrationtest/v2/test-resources/scoped-configs/project/user-action-and-session-properties-mobile/prop1myapp1.json, cmd/monaco/integrationtest/v2/test-resources/scoped-configs/project/user-action-and-session-properties-mobile/prop1myapp2.json, cmd/monaco/integrationtest/v2/test-resources/scoped-configs/project/user-action-and-session-properties-mobile/prop2myapp2.json, pkg/api/endpoints.go, pkg/client/dtclient/config_client.go, pkg/deploy/internal/classic/validation.go, pkg/download/classic/download_sanitize.go
Fix for how user-actions-and-session-properties api is handled.
Most comments about the "why" are in the commits.
Added a simple integration test that for the moment asserts that expected configs are available.
This should be enhanced!
e2e test works but shows some error due to the fact that automatic cleanup (delete of scoped) configs is not working atm.
=> Fix: Proper handling of user actions and session properties

cmd/monaco/integrationtest/account/deploy-download_test.go, cmd/monaco/integrationtest/account/utils_test.go, cmd/monaco/integrationtest/cleanup.go, cmd/monaco/integrationtest/config_rewrite.go, cmd/monaco/integrationtest/utils/monaco/cmd.go, cmd/monaco/integrationtest/utils/monaco/cmd_test.go, cmd/monaco/integrationtest/v1/integration_test_utils.go, cmd/monaco/integrationtest/v2/config_restore_e2e_test.go, cmd/monaco/integrationtest/v2/integration_test_utils.go, cmd/monaco/integrationtest/v2/settings_integration_test.go
To enable easier debugging of failed tests, more information is added to a log for the cleanup phase of the integration test.
=> print more details in log during test cleanup in integration test

pkg/download/classic/download.go, pkg/download/classic/download_test.go
For key-user-action-web that has the same name but a different domain (or actionType) create a correct template yaml file
=> Fix: for key-user-action-web that has the same name but a different domain (or actionType) create a correct template yaml file

cmd/monaco/purge/purge.go, pkg/api/api.go, pkg/api/apis.go, pkg/api/endpoints.go
I made two changes to
* skip trying to delete disabled api types
* skip trying to delete dashboard share settings
=> Adapt purge command to work with latest additions

.github/workflows/end-to-end-test.yml
It was previously missed that these tests make some environment configuration as well (management zone), so they can not run without these secrets available in CI
no
=> ci: Add platform environment secrets to account management E2E test stage

internal/featureflags/temporary.go
This PR adds the `MONACO_FEAT_DOCUMENTS` feature flag
=> chore: Add `MONACO_FEAT_DOCUMENTS` feature flag

cmd/monaco/download/download_command.go, cmd/monaco/download/download_configs.go, cmd/monaco/integrationtest/v2/delete_integration_test.go
* hide `Documents` specific command flags
* if FF is disabled, prevent download of Document configs
Some of the newly implemented features for `Documents` are not hidden behind FF. During the download process, it is causing next error:
```
2024-04-30T12:49:03+02:00       error   failed to write config :: to file "download_2024-04-30-124806/project_my_env": unknown type: config.DocumentType
2024-04-30T12:49:03+02:00       error   failed to write config :: to file "download_2024-04-30-124806/project_my_env": unknown type: config.DocumentType
2024-04-30T12:49:03+02:00       error   Error: failed to persist downloaded configurations
```
This PR address upper problem.
=> fix: hide `Documents` specific behind FF

cmd/monaco/generate/deletefile/deletefile_test.go, cmd/monaco/generate/deletefile/test-resources/project/automation/business-calendar.json, cmd/monaco/generate/deletefile/test-resources/project/automation/config.yaml, cmd/monaco/generate/deletefile/test-resources/project/automation/jira-issue-workflow.json, cmd/monaco/generate/deletefile/test-resources/project/automation/jiraJs.txt, cmd/monaco/generate/deletefile/test-resources/project/automation/scheduling-rule.json, cmd/monaco/generate/deletefile/test-resources/project/bucket/bucket.json, cmd/monaco/generate/deletefile/test-resources/project/bucket/config.yaml, cmd/monaco/generate/deletefile/test-resources/project/dashboard-document/config.yaml, cmd/monaco/generate/deletefile/test-resources/project/dashboard-document/dashboard.json, cmd/monaco/generate/deletefile/test-resources/project/notebook-document/config.yaml, cmd/monaco/generate/deletefile/test-resources/project/notebook-document/notebook.json
This PR extends `deletefile_test.TestGeneratesValidDeleteFile(...)` with automation, bucket and document configs.
=> test: Extend deletefile generation tests to cover automation, bucket and document configs

pkg/download/settings/download.go, pkg/download/settings/download_test.go
This PR fixes a panic caused by incorrectly referencing the previous configuration when downloading ordered settings objects.
In `settings.convertAllObjects(...)`:
https://github.com/Dynatrace/dynatrace-configuration-as-code/blob/0391f6797926c04d6240d686ecad0dbb15d47f9b/pkg/download/settings/download.go#L213-L216
`i` indexes the settings object being processed. However if an object is discarded (for example due to not being modifiable), `i-1` no longer references the previous configuration created.
This is fixed by maintaining a reference to the previous configuration created.
=> fix: Correctly index previous settings object when downloading ordered settings objects

cmd/monaco/runner/runner.go
Users saw that when using `--support-archive` the very latest log messages are actually not contained in the support archive.
This PR fixes it by moving the code responsible for writing the support archive at the very end of program execution.
=> fix: Close support archive at latest point in time

pkg/persistence/config/internal/persistence/type_definition.go
This PR updates the JSON schema for document configurations to match #1495.
=> chore: Update JSON schema for document configurations

cmd/monaco/integrationtest/v2/all_configs_integration_test.go, cmd/monaco/integrationtest/v2/test-resources/integration-all-configs/project/openpipeline/config.yaml, cmd/monaco/integrationtest/v2/test-resources/integration-all-configs/project/openpipeline/events.json
This PR adds OpenPipeline test resources to the e2e tests
=> OpenPipeline e2e test resources

go.mod, go.sum, pkg/client/clientset.go, pkg/delete/delete_test.go, pkg/delete/internal/document/delete.go, pkg/deploy/internal/document/document.go, pkg/deploy/internal/document/document_test.go
=> Adapt to use changes in core library

cmd/monaco/download/download_configs.go, cmd/monaco/download/download_configs_test.go, go.mod, go.sum, internal/featureflags/temporary.go, pkg/persistence/config/loader/config_loader_test.go
This PR enables document and openpipeline related feature flags
=> chore: enable ff for documents and open pipeline

cmd/monaco/integrationtest/v2/dry-run_test.go, cmd/monaco/integrationtest/v2/test-resources/integration-all-configs/project/document-dashboard/a913d0e0-0349-4f00-8849-076305e31808.json, cmd/monaco/integrationtest/v2/test-resources/integration-all-configs/project/document-dashboard/config.yaml, cmd/monaco/integrationtest/v2/test-resources/integration-all-configs/project/document-notebook/cb6f0c1b-90f0-4819-b822-ae1f2b10df40.json, cmd/monaco/integrationtest/v2/test-resources/integration-all-configs/project/document-notebook/config.yaml, pkg/deploy/internal/document/document.go
=> Fix dummy client for documents

cmd/monaco/generate/dependencygraph/dependencygraph.go, internal/multierror/multierror.go, internal/zip/zip.go, pkg/deploy/deploy.go
=> chore: Fix typo in multierror package name

.github/dependabot.yml
By moving to the the ko container builder and removing the docker file. there is no more need for this job
=> Clean up left behind docker job from the `dependabot.yml` file

pkg/graph/graph.go
This little PR fixes a typo in the spelling of environment
=> chore: Fix typo in spelling of environment

pkg/delete/delete.go
Configs are not reliably deleted on multiple environments. The reason for this is that the map containing delete entries is manipulated inside the function to which that map is passed to.
To avoid this side effect we need to copy the map of delete entries and do the manipulations on the copied map.
=> fix: copy delete file entries after passing them to the Delete function

.ci/jenkins/tools/sbom.groovy, go.mod
Update `toolchan` to include latest go bugfix and `cyclonedx-gomod` to latest version
=> chore: bump toolchain to go1.23.2 and cyclonedx-gomod to v1.8.0

go.mod, go.sum
=> chore: bump core library version to latest main

.github/workflows/end-to-end-test.yml
=> Checkout correct commit in case of iam e2e tests

cmd/monaco/integrationtest/v2/all_configs_integration_test.go, cmd/monaco/integrationtest/v2/supportarchive_report_test.go
=> test: test for deployment report

pkg/download/openpipeline/download.go, pkg/download/openpipeline/download_test.go, pkg/download/openpipeline/testdata/getEvents.json, pkg/download/openpipeline/testdata/getLogs.json
Both fields prevent a re-upload to the target environment, thus we remove them. Neither of them are required to correctly reupload them, the Dynatrace system takes care of it.
=> fix(OpenPipeline): Remove `version` and `updateToken` on download

.ci/jenkins/tools/ko.groovy, .ci/releasePipeline.groovy, Makefile
During the deployment, the process tried to deploy the same file 2x. It closed problems.
=> fix: prevent attempt of double publishing of cosign.pub

pkg/client/dtclient/settings_client.go, pkg/client/dtclient/settings_client_test.go
App-settings work a bit different from builtin-settings. When creating app-settings, the originObjectId must not be set, while the 'normal' settings do allow that.
To fix that, the approach has been changed. We assume that we can't find the correct object that requires updating, and then search for it. First, by the unique-constrains of the schema, then by the legacy-external-id, and finally by the external-id and origin-id.
Note that currently, the later methods potentially overwrite the previous methods. This can be fixed in a later refactoring.
Furthermore, this commit introduces multiple new tests that test the behavior and fixes existing ones (plus correct assert calls).
=> fix(Settings): App settings can now be created

cmd/monaco/download/download.go, cmd/monaco/download/download_command_test.go, cmd/monaco/download/download_configs.go
There is no more need for sharedDownloadCmdOptions.
=> remove sharedDownloadCmdOptions struct

cmd/monaco/integrationtest/v2/config_restore_e2e_test.go, cmd/monaco/integrationtest/v2/integration_test_utils.go, cmd/monaco/integrationtest/v2/segments_integration_test.go, cmd/monaco/integrationtest/v2/test-resources/integration-download-configs-platform/project/segment/config.yaml, cmd/monaco/integrationtest/v2/test-resources/integration-download-configs-platform/project/segment/segment.json, cmd/monaco/integrationtest/v2/test-resources/segments/manifest.yaml, cmd/monaco/integrationtest/v2/test-resources/segments/standalone-segment/config.yaml, cmd/monaco/integrationtest/v2/test-resources/segments/standalone-segment/segment.json, cmd/monaco/integrationtest/v2/test-resources/segments/two-segments/config.yaml, cmd/monaco/integrationtest/v2/test-resources/segments/two-segments/segment.json, go.mod, go.sum
Added some e2e tests to test the following behavior:
* Deploy single
* Deploy single multiple times
* Deploy multiple multiple times
* Without enabled FF it should fail
* Updated download/restore test
=> feat(segments): Add e2e tests

internal/featureflags/temporary.go, pkg/config/types.go, pkg/persistence/config/internal/persistence/type_definition.go, pkg/persistence/config/loader/config_loader_test.go, pkg/persistence/config/writer/config_writer_test.go
This PR introduces the config type `slo` into monaco with the feature flag to toggle it on or off(by default).
=> feat(SLO): create slo, config type and feature flag

cmd/monaco/version/command.go
=> refactor(command): rename version return parameter

pkg/download/settings/download.go, pkg/download/settings/download_test.go
When downloading settings objects, they are returned ordered.
We utilize that to set the `insertAfter` parameter always to the previous setting if the schema supports ordering.
The issue is that we did not take the scope into account. the `insertAfter` only works within the same scope, so referencing an object from another scope will cause an error.
This changeset changes this by 'remembering' the last settings object for the given scope.
Yes, currently, the download breaks for settings.
=> fix(settings): Download ordered settings needs to take scopes into account

go.mod, go.sum
=> chore: update library with the version that supports SLO

pkg/client/clientset.go, pkg/client/dummy_clientset.go, pkg/client/test_clientset.go, pkg/deploy/deploy.go, pkg/deploy/deploy_test.go, pkg/deploy/internal/slo/slo.go, pkg/deploy/internal/slo/slo_test.go
Introduction of the SLO API support in monaco for deployment command.
This implementation introduces some code duplications. The code duplications will be tackled in follow-up refactoring. This is to provide the feature as fast as possible and have a functioning base.
=> feat(SLO): deploy support for SLO API

pkg/deploy/internal/slo/slo_test.go
Improve slo deploy test to and extend the unit test to validate required request payload
=> fix(SLO): Improve SLO deploy test to validate requestPayload

cmd/monaco/account/delete.go, cmd/monaco/account/deploy.go, cmd/monaco/integrationtest/account/all_resources_integration_test.go, cmd/monaco/integrationtest/account/runner.go, pkg/account/delete/client_test.go, pkg/account/delete/delete_test.go, pkg/account/deployer/client_test.go, pkg/account/deployer/deployer.go, pkg/account/deployer/deployer_test.go
Passes the correct context to account related functions
=> chore(account): pass right context

cmd/monaco/account/delete.go, cmd/monaco/dynatrace/dynatrace.go, cmd/monaco/integrationtest/v2/settings_integration_test.go, go.mod, go.sum, pkg/client/clientset.go
Updates core and sets the context that is now needed
=> chore(core): update core and pass context

pkg/delete/delete.go
This PR fixes the warning message for deletion.
=> fix(delete): fix broken warning message for segments and slo

pkg/delete/all.go, pkg/delete/all_test.go, pkg/delete/internal/slo/delete.go, pkg/delete/internal/slo/delete_test.go, pkg/deploy/deploy_test.go
This PR brings purge functionality for SLO.
=> feat(slo-v2): add purge functionality

pkg/client/test_clientset.go
This PR adds two comments that were accidentally left out of #1732.
=> refactor: Update fake client comments

cmd/monaco/integrationtest/v2/supportarchive_report_test.go
This changeset fixes an oversight of PR #1747
=> fix: Fix failing e2e test

cmd/monaco/integrationtest/v2/all_configs_integration_test.go, cmd/monaco/integrationtest/v2/config_restore_e2e_test.go, cmd/monaco/integrationtest/v2/dry-run_test.go, cmd/monaco/integrationtest/v2/slo-v2_integration_test.go, cmd/monaco/integrationtest/v2/test-resources/integration-all-configs/project/slo-v2/config.yaml, cmd/monaco/integrationtest/v2/test-resources/integration-all-configs/project/slo-v2/custom-made.json, cmd/monaco/integrationtest/v2/test-resources/integration-all-configs/project/slo-v2/template-based.json, cmd/monaco/integrationtest/v2/test-resources/integration-download-configs-platform/project/slo-v2/config.yaml, cmd/monaco/integrationtest/v2/test-resources/integration-download-configs-platform/project/slo-v2/custom-sli.json, cmd/monaco/integrationtest/v2/test-resources/integration-download-configs-platform/project/slo-v2/sli-reference.json, cmd/monaco/integrationtest/v2/test-resources/slo-v2/manifest.yaml, cmd/monaco/integrationtest/v2/test-resources/slo-v2/project/config.yaml, cmd/monaco/integrationtest/v2/test-resources/slo-v2/project/custom-sli.json, cmd/monaco/integrationtest/v2/test-resources/slo-v2/project/sli-reference.json
This PR adds e2e tests for slo-v2 configs
=> test(slo-v2): add e2e tests

pkg/client/metadata/metadata.go
This PR adds logging and timeout to the `context.Context` used in `metadata.GetDynatraceClassicURL(...)`
=> fix: Add logging and timeout to context for `GetDynatraceClassicURL()`

cmd/monaco/account/delete.go, pkg/account/delete/client.go, pkg/account/delete/client_test.go, pkg/account/delete/delete.go, pkg/account/delete/delete_test.go, pkg/account/delete/loader.go, pkg/account/delete/loader_test.go, pkg/account/delete/persistence.go
This PR adds the ability to delete service users from accounts.
This PR does the bare minimum to implement the functionality, we should do some follow ups to reduce code duplication etc.
=> feat(account): Delete service users

go.mod, go.sum, pkg/client/dtclient/config_client.go, pkg/client/dtclient/config_client_test.go, pkg/client/dtclient/retry.go, pkg/client/dtclient/retry_test.go
Permission errors (403) should not be retried because the result would not change
Based on https://github.com/Dynatrace/dynatrace-configuration-as-code-core/pull/191
=> chore: do not retry on permission error

.github/workflows/pr-static-code-analysis.yml
This PR introduces a pined version for golangci_lint.
=> fix: pin golangci_lint version

pkg/download/id_extraction/id_extraction.go, pkg/download/id_extraction/id_extraction_test.go
Fixes a small issue where ME IDs accidently included the `n` from `\n` if there were no extra characters in between.
The searching is done after extracting ME IDs, as it can't happen with UUIDs.
=> fix: `\n`, `\t`, `\r` are no longer included in ME ids

.github/workflows/build-test.yml, sonar-project.properties
=> fix: exclude cmd test folder

sonar-project.properties
=> fix: provide sonar with current release version

.github/workflows/semgrep.yml
Update semgrep to the latest release version, pined to a commit.
NO
=> fix: update `semgrep` to latest release, pined to a version

pkg/client/test_clientset.go, pkg/deploy/deploy_test.go, sonar-project.properties
This PR adds test-cases to increase code coverage in deploy package.
=> refactor(deploy): add test cases to increase coverage in `deploy.go` 

.github/workflows/build-test.yml, pkg/deploy/deploy.go
Fix issues detected by SonarCloud:
https://sonarcloud.io/project/issues?fileUuids=AYcjuluWrEeRk76GqkNN&issueStatuses=OPEN%2CCONFIRMED&impactSoftwareQualities=MAINTAINABILITY&id=Dynatrace_dynatrace-configuration-as-code
NO
=> refactor(deploy): fix SonarCloud issues on the `deployment.go`

cmd/monaco/integrationtest/account/all_resources_integration_test.go, cmd/monaco/integrationtest/account/deploy-download_test.go, cmd/monaco/integrationtest/account/resources/all-resources/accounts/service-users.yaml, cmd/monaco/integrationtest/account/resources/all-resources/delete.yaml, cmd/monaco/integrationtest/account/resources/deploy-download/add_user/service-users.yaml, cmd/monaco/integrationtest/account/resources/deploy-download/delete.yaml, cmd/monaco/integrationtest/account/utils_test.go
This PR updates the existing account management E2E tests to include service users.
=> test(account): Update existing E2E tests to include service users

cmd/monaco/download/download_configs_test.go
Fixing a minor copy-paste error in a test message
NONE
=> fix(test): Corrects minor copy-paste error in a test message

.github/PULL_REQUEST_TEMPLATE.md
As we feel the current one is a bit cumbersome, we update the pull request template to something simpler and more developer friendly, based on the ideas presented in Google's 'Writing a Good Pull Request' article: https://developers.google.com/blockly/guides/contribute/get-started/write_a_good_pr#communicate-2
Having a better template will make us more likely to use it.
Please check the wording carefully, we want to be friendly.
Yes, this will make users want to write more PRs.
=> chore: Simplify pull request template

cmd/monaco/download/download_configs.go
Reduce code duplications.
In 'download_configs.go', code that was basically duplicated in two functions was extracted to its own function.
There are two functions in `download_configs.go` which create the `downloadConfigsOptions` struct: `DownloadConfigsBasedOnManifest` and `DownloadConfigs`. The code is nearly the same for both cases, so I extracted the function `toDownloadConfigsOptions` to have creation of the struct at one place. This function is called by the two formerly mentioned functions.
Existing tests still work
It doesn't
=> refactor(download): Unify `downloadConfigsOptions` creation

internal/throttle/throttle_requests.go, pkg/account/persistence/writer/writer.go, pkg/client/dtclient/config_client.go, pkg/delete/internal/automation/delete.go, pkg/delete/internal/bucket/delete.go, pkg/delete/internal/document/delete.go, pkg/delete/internal/segment/delete.go, pkg/delete/internal/setting/delete.go, pkg/delete/internal/slo/delete.go
This PR contains several improvements I found while working on moving to SLOG. As they are not really related to that work, it makes sense for this to be in a separate PR.
Some log and error messages have been updated,  but not really _what_ is emitted, _when_, or _why_.
Updates the text of some log and error messages. Some light refactoring is performed around this.
Existing tests still work - no change. Code coverage of tests is not addressed in this PR.
Users get to read nicer messages.
=> feat: Improve some log and error messages

.github/PULL_REQUEST_TEMPLATE.md
Make it easy to track correlation between internal issues and PRs.
Adds `**Issue:**` to the template.
Updates the text in `.github/PULL_REQUEST_TEMPLATE.md`
=> chore: Add issue reference to pull request template

cmd/monaco/download/download_command.go, cmd/monaco/download/download_configs.go, cmd/monaco/download/download_configs_test.go, internal/featureflags/featureflag_test.go, internal/featureflags/temporary.go, pkg/config/internal/persistence/type_definition.go, pkg/config/loader/config_loader_test.go, pkg/config/writer/config_writer_test.go, pkg/delete/all.go, pkg/delete/all_test.go, pkg/delete/delete.go, pkg/delete/delete_test.go, pkg/deploy/deploy_test.go, test/commands/config_restore_e2e_test.go, test/commands/deletefile_test.go, test/configtypes/segments/segments_integration_test.go
The segment feature flag is removed, and everywhere it was used, it's replaced by the `true` condition of this flag.
Segments FF is removed
**Issue:** CA-15447
=> refactor(segments): remove feature flag

pkg/manifest/loader/manifest_loader_test.go
As the underlying code has changed over time, update the test name and setup to match the tested function `parseURLDefinition(...)`.
The test setup is modified to test the `parseURLDefinition(...)` function in isolation; the test cases remain largely the same:
- The test setup only provides a `persistence.TypedValue` rather than a whole `persistence.Environment` that wasn't being used
- More plausible URLs are used
No effect on users.
**Issue:** CA-15587
=> test: Update `Test_extractUrlType` to `Test_parseURLDefinition`

cmd/monaco/account/download.go, cmd/monaco/dynatrace/dynatrace.go, go.mod, go.sum, pkg/account/delete/client.go, pkg/account/delete/client_test.go, pkg/account/deployer/client.go, pkg/account/deployer/client_test.go, pkg/account/downloader/downloader.go, pkg/account/downloader/internal/http/client.go, test/account/all_resources_integration_test.go, test/account/runner.go
To be up to date with the core lib and not have several needed changes at once later on.
Core lib updated. account management imports adjusted
Current tests cover it.
Doesn't affect users
**Issue:**
=> chore: update core lib

go.mod
=> chore: update Go to 1.24.6
